# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: c:/Users/dotignore/Desktop/Xilinx/projects/zybo_z7_cam_rpi_v2_5mp/zybo_z7_imx219/zybo_z7_imx219.gen/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_0/bd_d10d_phy_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_d10d_phy_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/dotignore/Desktop/Xilinx/projects/zybo_z7_cam_rpi_v2_5mp/zybo_z7_imx219/zybo_z7_imx219.gen/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_0/bd_d10d_phy_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_d10d_phy_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/dotignore/Desktop/Xilinx/projects/zybo_z7_cam_rpi_v2_5mp/zybo_z7_imx219/zybo_z7_imx219.gen/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_0/bd_d10d_phy_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_d10d_phy_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/dotignore/Desktop/Xilinx/projects/zybo_z7_cam_rpi_v2_5mp/zybo_z7_imx219/zybo_z7_imx219.gen/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_0/bd_d10d_phy_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_d10d_phy_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/dotignore/Desktop/Xilinx/projects/zybo_z7_cam_rpi_v2_5mp/zybo_z7_imx219/zybo_z7_imx219.gen/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_0/bd_d10d_phy_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_d10d_phy_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/dotignore/Desktop/Xilinx/projects/zybo_z7_cam_rpi_v2_5mp/zybo_z7_imx219/zybo_z7_imx219.gen/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_0/bd_d10d_phy_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_d10d_phy_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
