// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module design_1_v_demosaic_0_0_AXIvideo2MultiBayer (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        s_axis_video_TDATA,
        s_axis_video_TVALID,
        s_axis_video_TREADY,
        s_axis_video_TKEEP,
        s_axis_video_TSTRB,
        s_axis_video_TUSER,
        s_axis_video_TLAST,
        s_axis_video_TID,
        s_axis_video_TDEST,
        imgBayer_din,
        imgBayer_full_n,
        imgBayer_write,
        imgBayer_num_data_valid,
        imgBayer_fifo_cap,
        Height_val,
        WidthIn_val
);

parameter    ap_ST_fsm_state1 = 9'd1;
parameter    ap_ST_fsm_state2 = 9'd2;
parameter    ap_ST_fsm_state3 = 9'd4;
parameter    ap_ST_fsm_state4 = 9'd8;
parameter    ap_ST_fsm_state5 = 9'd16;
parameter    ap_ST_fsm_state6 = 9'd32;
parameter    ap_ST_fsm_state7 = 9'd64;
parameter    ap_ST_fsm_state8 = 9'd128;
parameter    ap_ST_fsm_state9 = 9'd256;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [9:0] s_axis_video_TDATA;
input   s_axis_video_TVALID;
output   s_axis_video_TREADY;
input  [1:0] s_axis_video_TKEEP;
input  [1:0] s_axis_video_TSTRB;
input  [0:0] s_axis_video_TUSER;
input  [0:0] s_axis_video_TLAST;
input  [0:0] s_axis_video_TID;
input  [0:0] s_axis_video_TDEST;
output  [9:0] imgBayer_din;
input   imgBayer_full_n;
output   imgBayer_write;
input  [2:0] imgBayer_num_data_valid;
input  [2:0] imgBayer_fifo_cap;
input  [15:0] Height_val;
input  [15:0] WidthIn_val;

reg ap_done;
reg ap_idle;
reg ap_ready;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [10:0] grp_reg_unsigned_short_s_fu_212_ap_return;
reg   [10:0] rows_reg_436;
wire    ap_CS_fsm_state4;
wire   [10:0] grp_reg_unsigned_short_s_fu_218_ap_return;
reg   [10:0] cols_reg_441;
wire   [0:0] icmp_ln166_fu_265_p2;
reg   [0:0] icmp_ln166_reg_449;
wire   [0:0] xor_ln188_fu_271_p2;
reg   [0:0] xor_ln188_reg_454;
wire   [0:0] and_ln188_1_fu_295_p2;
reg   [0:0] and_ln188_1_reg_465;
wire    ap_CS_fsm_state5;
wire   [0:0] and_ln188_fu_351_p2;
reg   [0:0] and_ln188_reg_476;
wire    ap_CS_fsm_state7;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_128_ap_start;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_128_ap_done;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_128_ap_idle;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_128_ap_ready;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_128_s_axis_video_TREADY;
wire   [0:0] grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_128_axi_last_out;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_128_axi_last_out_ap_vld;
wire   [9:0] grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_128_axi_data_promoted278_out;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_128_axi_data_promoted278_out_ap_vld;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_148_ap_start;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_148_ap_done;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_148_ap_idle;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_148_ap_ready;
wire   [9:0] grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_148_imgBayer_din;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_148_imgBayer_write;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_148_s_axis_video_TREADY;
wire   [0:0] grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_148_p_4_0_0_0105271_out;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_148_p_4_0_0_0105271_out_ap_vld;
wire   [9:0] grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_148_p_0_0_0_097262_out;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_148_p_0_0_0_097262_out_ap_vld;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_176_ap_start;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_176_ap_done;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_176_ap_idle;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_176_ap_ready;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_176_s_axis_video_TREADY;
wire   [0:0] grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_176_p_4_0_0_0105270_lcssa295_out;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_176_p_4_0_0_0105270_lcssa295_out_ap_vld;
wire   [9:0] grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_176_p_0_0_0_097263_lcssa279_out;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_176_p_0_0_0_097263_lcssa279_out_ap_vld;
wire    grp_reg_unsigned_short_s_fu_212_ap_start;
wire    grp_reg_unsigned_short_s_fu_212_ap_done;
wire    grp_reg_unsigned_short_s_fu_212_ap_idle;
wire    grp_reg_unsigned_short_s_fu_212_ap_ready;
reg    grp_reg_unsigned_short_s_fu_212_ap_ce;
wire   [10:0] grp_reg_unsigned_short_s_fu_212_d;
wire    ap_CS_fsm_state3;
wire    grp_reg_unsigned_short_s_fu_218_ap_start;
wire    grp_reg_unsigned_short_s_fu_218_ap_done;
wire    grp_reg_unsigned_short_s_fu_218_ap_idle;
wire    grp_reg_unsigned_short_s_fu_218_ap_ready;
reg    grp_reg_unsigned_short_s_fu_218_ap_ce;
wire   [10:0] grp_reg_unsigned_short_s_fu_218_d;
reg   [0:0] p_4_0_0_0105270_lcssa297_reg_106;
wire    ap_CS_fsm_state9;
reg   [0:0] sof_reg_116;
reg    grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_128_ap_start_reg;
wire    ap_CS_fsm_state2;
reg   [0:0] axi_last_loc_fu_90;
reg   [9:0] p_0_0_0_097263_lcssa281_fu_74;
reg    grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_148_ap_start_reg;
wire   [0:0] icmp_ln163_fu_280_p2;
wire    ap_CS_fsm_state6;
reg    grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_176_ap_start_reg;
wire    ap_CS_fsm_state8;
reg   [0:0] p_4_0_0_0105270_lcssa295_loc_fu_78;
reg    grp_reg_unsigned_short_s_fu_212_ap_start_reg;
reg   [8:0] ap_NS_fsm;
wire    ap_NS_fsm_state3;
reg    grp_reg_unsigned_short_s_fu_218_ap_start_reg;
reg   [10:0] i_fu_70;
wire   [10:0] i_4_fu_285_p2;
reg    ap_block_state1;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    regslice_both_s_axis_video_V_data_V_U_apdone_blk;
wire   [9:0] s_axis_video_TDATA_int_regslice;
wire    s_axis_video_TVALID_int_regslice;
reg    s_axis_video_TREADY_int_regslice;
wire    regslice_both_s_axis_video_V_data_V_U_ack_in;
wire    regslice_both_s_axis_video_V_keep_V_U_apdone_blk;
wire   [1:0] s_axis_video_TKEEP_int_regslice;
wire    regslice_both_s_axis_video_V_keep_V_U_vld_out;
wire    regslice_both_s_axis_video_V_keep_V_U_ack_in;
wire    regslice_both_s_axis_video_V_strb_V_U_apdone_blk;
wire   [1:0] s_axis_video_TSTRB_int_regslice;
wire    regslice_both_s_axis_video_V_strb_V_U_vld_out;
wire    regslice_both_s_axis_video_V_strb_V_U_ack_in;
wire    regslice_both_s_axis_video_V_user_V_U_apdone_blk;
wire   [0:0] s_axis_video_TUSER_int_regslice;
wire    regslice_both_s_axis_video_V_user_V_U_vld_out;
wire    regslice_both_s_axis_video_V_user_V_U_ack_in;
wire    regslice_both_s_axis_video_V_last_V_U_apdone_blk;
wire   [0:0] s_axis_video_TLAST_int_regslice;
wire    regslice_both_s_axis_video_V_last_V_U_vld_out;
wire    regslice_both_s_axis_video_V_last_V_U_ack_in;
wire    regslice_both_s_axis_video_V_id_V_U_apdone_blk;
wire   [0:0] s_axis_video_TID_int_regslice;
wire    regslice_both_s_axis_video_V_id_V_U_vld_out;
wire    regslice_both_s_axis_video_V_id_V_U_ack_in;
wire    regslice_both_s_axis_video_V_dest_V_U_apdone_blk;
wire   [0:0] s_axis_video_TDEST_int_regslice;
wire    regslice_both_s_axis_video_V_dest_V_U_vld_out;
wire    regslice_both_s_axis_video_V_dest_V_U_ack_in;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 9'd1;
#0 grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_128_ap_start_reg = 1'b0;
#0 grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_148_ap_start_reg = 1'b0;
#0 grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_176_ap_start_reg = 1'b0;
#0 grp_reg_unsigned_short_s_fu_212_ap_start_reg = 1'b0;
#0 grp_reg_unsigned_short_s_fu_218_ap_start_reg = 1'b0;
#0 i_fu_70 = 11'd0;
end

design_1_v_demosaic_0_0_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_128(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_128_ap_start),
    .ap_done(grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_128_ap_done),
    .ap_idle(grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_128_ap_idle),
    .ap_ready(grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_128_ap_ready),
    .s_axis_video_TVALID(s_axis_video_TVALID_int_regslice),
    .s_axis_video_TDATA(s_axis_video_TDATA_int_regslice),
    .s_axis_video_TREADY(grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_128_s_axis_video_TREADY),
    .s_axis_video_TKEEP(s_axis_video_TKEEP_int_regslice),
    .s_axis_video_TSTRB(s_axis_video_TSTRB_int_regslice),
    .s_axis_video_TUSER(s_axis_video_TUSER_int_regslice),
    .s_axis_video_TLAST(s_axis_video_TLAST_int_regslice),
    .s_axis_video_TID(s_axis_video_TID_int_regslice),
    .s_axis_video_TDEST(s_axis_video_TDEST_int_regslice),
    .axi_last_out(grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_128_axi_last_out),
    .axi_last_out_ap_vld(grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_128_axi_last_out_ap_vld),
    .axi_data_promoted278_out(grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_128_axi_data_promoted278_out),
    .axi_data_promoted278_out_ap_vld(grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_128_axi_data_promoted278_out_ap_vld)
);

design_1_v_demosaic_0_0_AXIvideo2MultiBayer_Pipeline_loop_width grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_148(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_148_ap_start),
    .ap_done(grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_148_ap_done),
    .ap_idle(grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_148_ap_idle),
    .ap_ready(grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_148_ap_ready),
    .s_axis_video_TVALID(s_axis_video_TVALID_int_regslice),
    .imgBayer_din(grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_148_imgBayer_din),
    .imgBayer_full_n(imgBayer_full_n),
    .imgBayer_write(grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_148_imgBayer_write),
    .imgBayer_num_data_valid(3'd0),
    .imgBayer_fifo_cap(3'd0),
    .p_4_0_0_0105270_lcssa297(p_4_0_0_0105270_lcssa297_reg_106),
    .p_0_0_0_097263_lcssa281(p_0_0_0_097263_lcssa281_fu_74),
    .sof_3(sof_reg_116),
    .cols(cols_reg_441),
    .s_axis_video_TDATA(s_axis_video_TDATA_int_regslice),
    .s_axis_video_TREADY(grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_148_s_axis_video_TREADY),
    .s_axis_video_TKEEP(s_axis_video_TKEEP_int_regslice),
    .s_axis_video_TSTRB(s_axis_video_TSTRB_int_regslice),
    .s_axis_video_TUSER(s_axis_video_TUSER_int_regslice),
    .s_axis_video_TLAST(s_axis_video_TLAST_int_regslice),
    .s_axis_video_TID(s_axis_video_TID_int_regslice),
    .s_axis_video_TDEST(s_axis_video_TDEST_int_regslice),
    .p_4_0_0_0105271_out(grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_148_p_4_0_0_0105271_out),
    .p_4_0_0_0105271_out_ap_vld(grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_148_p_4_0_0_0105271_out_ap_vld),
    .p_0_0_0_097262_out(grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_148_p_0_0_0_097262_out),
    .p_0_0_0_097262_out_ap_vld(grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_148_p_0_0_0_097262_out_ap_vld)
);

design_1_v_demosaic_0_0_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_176(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_176_ap_start),
    .ap_done(grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_176_ap_done),
    .ap_idle(grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_176_ap_idle),
    .ap_ready(grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_176_ap_ready),
    .s_axis_video_TVALID(s_axis_video_TVALID_int_regslice),
    .p_4_0_0_0105271_reload(grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_148_p_4_0_0_0105271_out),
    .p_0_0_0_097262_reload(grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_148_p_0_0_0_097262_out),
    .and_ln188(and_ln188_reg_476),
    .s_axis_video_TDATA(s_axis_video_TDATA_int_regslice),
    .s_axis_video_TREADY(grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_176_s_axis_video_TREADY),
    .s_axis_video_TKEEP(s_axis_video_TKEEP_int_regslice),
    .s_axis_video_TSTRB(s_axis_video_TSTRB_int_regslice),
    .s_axis_video_TUSER(s_axis_video_TUSER_int_regslice),
    .s_axis_video_TLAST(s_axis_video_TLAST_int_regslice),
    .s_axis_video_TID(s_axis_video_TID_int_regslice),
    .s_axis_video_TDEST(s_axis_video_TDEST_int_regslice),
    .p_4_0_0_0105270_lcssa295_out(grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_176_p_4_0_0_0105270_lcssa295_out),
    .p_4_0_0_0105270_lcssa295_out_ap_vld(grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_176_p_4_0_0_0105270_lcssa295_out_ap_vld),
    .p_0_0_0_097263_lcssa279_out(grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_176_p_0_0_0_097263_lcssa279_out),
    .p_0_0_0_097263_lcssa279_out_ap_vld(grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_176_p_0_0_0_097263_lcssa279_out_ap_vld)
);

design_1_v_demosaic_0_0_reg_unsigned_short_s grp_reg_unsigned_short_s_fu_212(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_reg_unsigned_short_s_fu_212_ap_start),
    .ap_done(grp_reg_unsigned_short_s_fu_212_ap_done),
    .ap_idle(grp_reg_unsigned_short_s_fu_212_ap_idle),
    .ap_ready(grp_reg_unsigned_short_s_fu_212_ap_ready),
    .ap_ce(grp_reg_unsigned_short_s_fu_212_ap_ce),
    .d(grp_reg_unsigned_short_s_fu_212_d),
    .ap_return(grp_reg_unsigned_short_s_fu_212_ap_return)
);

design_1_v_demosaic_0_0_reg_unsigned_short_s grp_reg_unsigned_short_s_fu_218(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_reg_unsigned_short_s_fu_218_ap_start),
    .ap_done(grp_reg_unsigned_short_s_fu_218_ap_done),
    .ap_idle(grp_reg_unsigned_short_s_fu_218_ap_idle),
    .ap_ready(grp_reg_unsigned_short_s_fu_218_ap_ready),
    .ap_ce(grp_reg_unsigned_short_s_fu_218_ap_ce),
    .d(grp_reg_unsigned_short_s_fu_218_d),
    .ap_return(grp_reg_unsigned_short_s_fu_218_ap_return)
);

design_1_v_demosaic_0_0_regslice_both #(
    .DataWidth( 10 ))
regslice_both_s_axis_video_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(s_axis_video_TDATA),
    .vld_in(s_axis_video_TVALID),
    .ack_in(regslice_both_s_axis_video_V_data_V_U_ack_in),
    .data_out(s_axis_video_TDATA_int_regslice),
    .vld_out(s_axis_video_TVALID_int_regslice),
    .ack_out(s_axis_video_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video_V_data_V_U_apdone_blk)
);

design_1_v_demosaic_0_0_regslice_both #(
    .DataWidth( 2 ))
regslice_both_s_axis_video_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(s_axis_video_TKEEP),
    .vld_in(s_axis_video_TVALID),
    .ack_in(regslice_both_s_axis_video_V_keep_V_U_ack_in),
    .data_out(s_axis_video_TKEEP_int_regslice),
    .vld_out(regslice_both_s_axis_video_V_keep_V_U_vld_out),
    .ack_out(s_axis_video_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video_V_keep_V_U_apdone_blk)
);

design_1_v_demosaic_0_0_regslice_both #(
    .DataWidth( 2 ))
regslice_both_s_axis_video_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(s_axis_video_TSTRB),
    .vld_in(s_axis_video_TVALID),
    .ack_in(regslice_both_s_axis_video_V_strb_V_U_ack_in),
    .data_out(s_axis_video_TSTRB_int_regslice),
    .vld_out(regslice_both_s_axis_video_V_strb_V_U_vld_out),
    .ack_out(s_axis_video_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video_V_strb_V_U_apdone_blk)
);

design_1_v_demosaic_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_video_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(s_axis_video_TUSER),
    .vld_in(s_axis_video_TVALID),
    .ack_in(regslice_both_s_axis_video_V_user_V_U_ack_in),
    .data_out(s_axis_video_TUSER_int_regslice),
    .vld_out(regslice_both_s_axis_video_V_user_V_U_vld_out),
    .ack_out(s_axis_video_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video_V_user_V_U_apdone_blk)
);

design_1_v_demosaic_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_video_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(s_axis_video_TLAST),
    .vld_in(s_axis_video_TVALID),
    .ack_in(regslice_both_s_axis_video_V_last_V_U_ack_in),
    .data_out(s_axis_video_TLAST_int_regslice),
    .vld_out(regslice_both_s_axis_video_V_last_V_U_vld_out),
    .ack_out(s_axis_video_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video_V_last_V_U_apdone_blk)
);

design_1_v_demosaic_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_video_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(s_axis_video_TID),
    .vld_in(s_axis_video_TVALID),
    .ack_in(regslice_both_s_axis_video_V_id_V_U_ack_in),
    .data_out(s_axis_video_TID_int_regslice),
    .vld_out(regslice_both_s_axis_video_V_id_V_U_vld_out),
    .ack_out(s_axis_video_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video_V_id_V_U_apdone_blk)
);

design_1_v_demosaic_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_video_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(s_axis_video_TDEST),
    .vld_in(s_axis_video_TVALID),
    .ack_in(regslice_both_s_axis_video_V_dest_V_U_ack_in),
    .data_out(s_axis_video_TDEST_int_regslice),
    .vld_out(regslice_both_s_axis_video_V_dest_V_U_vld_out),
    .ack_out(s_axis_video_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video_V_dest_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln163_fu_280_p2 == 1'd1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_176_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_176_ap_start_reg <= 1'b1;
        end else if ((grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_176_ap_ready == 1'b1)) begin
            grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_176_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_128_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_128_ap_start_reg <= 1'b1;
        end else if ((grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_128_ap_ready == 1'b1)) begin
            grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_128_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_148_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln163_fu_280_p2 == 1'd0))) begin
            grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_148_ap_start_reg <= 1'b1;
        end else if ((grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_148_ap_ready == 1'b1)) begin
            grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_148_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_reg_unsigned_short_s_fu_212_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state3) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_reg_unsigned_short_s_fu_212_ap_start_reg <= 1'b1;
        end else if ((grp_reg_unsigned_short_s_fu_212_ap_ready == 1'b1)) begin
            grp_reg_unsigned_short_s_fu_212_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_reg_unsigned_short_s_fu_218_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state3) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_reg_unsigned_short_s_fu_218_ap_start_reg <= 1'b1;
        end else if ((grp_reg_unsigned_short_s_fu_218_ap_ready == 1'b1)) begin
            grp_reg_unsigned_short_s_fu_218_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_fu_70 <= 11'd0;
    end else if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln163_fu_280_p2 == 1'd0))) begin
        i_fu_70 <= i_4_fu_285_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_176_p_0_0_0_097263_lcssa279_out_ap_vld == 1'b1))) begin
        p_0_0_0_097263_lcssa281_fu_74 <= grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_176_p_0_0_0_097263_lcssa279_out;
    end else if (((grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_128_axi_data_promoted278_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        p_0_0_0_097263_lcssa281_fu_74 <= grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_128_axi_data_promoted278_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        p_4_0_0_0105270_lcssa297_reg_106 <= p_4_0_0_0105270_lcssa295_loc_fu_78;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        p_4_0_0_0105270_lcssa297_reg_106 <= axi_last_loc_fu_90;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        sof_reg_116 <= and_ln188_1_reg_465;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        sof_reg_116 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        and_ln188_1_reg_465 <= and_ln188_1_fu_295_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        and_ln188_reg_476 <= and_ln188_fu_351_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_128_axi_last_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        axi_last_loc_fu_90 <= grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_128_axi_last_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        cols_reg_441 <= grp_reg_unsigned_short_s_fu_218_ap_return;
        icmp_ln166_reg_449 <= icmp_ln166_fu_265_p2;
        rows_reg_436 <= grp_reg_unsigned_short_s_fu_212_ap_return;
        xor_ln188_reg_454 <= xor_ln188_fu_271_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_176_p_4_0_0_0105270_lcssa295_out_ap_vld == 1'b1))) begin
        p_4_0_0_0105270_lcssa295_loc_fu_78 <= grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_176_p_4_0_0_0105270_lcssa295_out;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_128_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_148_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_176_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln163_fu_280_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln163_fu_280_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | ((grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_128_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3)))) begin
        grp_reg_unsigned_short_s_fu_212_ap_ce = 1'b1;
    end else begin
        grp_reg_unsigned_short_s_fu_212_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | ((grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_128_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3)))) begin
        grp_reg_unsigned_short_s_fu_218_ap_ce = 1'b1;
    end else begin
        grp_reg_unsigned_short_s_fu_218_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        s_axis_video_TREADY_int_regslice = grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_176_s_axis_video_TREADY;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        s_axis_video_TREADY_int_regslice = grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_148_s_axis_video_TREADY;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        s_axis_video_TREADY_int_regslice = grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_128_s_axis_video_TREADY;
    end else begin
        s_axis_video_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_128_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln163_fu_280_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_148_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_176_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign and_ln188_1_fu_295_p2 = (xor_ln188_reg_454 & sof_reg_116);

assign and_ln188_fu_351_p2 = (icmp_ln166_reg_449 & grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_148_p_4_0_0_0105271_out);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_NS_fsm_state3 = ap_NS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_176_ap_start = grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_176_ap_start_reg;

assign grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_128_ap_start = grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_128_ap_start_reg;

assign grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_148_ap_start = grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_148_ap_start_reg;

assign grp_reg_unsigned_short_s_fu_212_ap_start = grp_reg_unsigned_short_s_fu_212_ap_start_reg;

assign grp_reg_unsigned_short_s_fu_212_d = Height_val[10:0];

assign grp_reg_unsigned_short_s_fu_218_ap_start = grp_reg_unsigned_short_s_fu_218_ap_start_reg;

assign grp_reg_unsigned_short_s_fu_218_d = WidthIn_val[10:0];

assign i_4_fu_285_p2 = (i_fu_70 + 11'd1);

assign icmp_ln163_fu_280_p2 = ((i_fu_70 == rows_reg_436) ? 1'b1 : 1'b0);

assign icmp_ln166_fu_265_p2 = ((grp_reg_unsigned_short_s_fu_218_ap_return != 11'd0) ? 1'b1 : 1'b0);

assign imgBayer_din = grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_148_imgBayer_din;

assign imgBayer_write = grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_148_imgBayer_write;

assign s_axis_video_TREADY = regslice_both_s_axis_video_V_data_V_U_ack_in;

assign xor_ln188_fu_271_p2 = (icmp_ln166_fu_265_p2 ^ 1'd1);

endmodule //design_1_v_demosaic_0_0_AXIvideo2MultiBayer
