// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module design_1_v_demosaic_0_0_MultiPixStream2AXIvideo (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        imgUnzip_dout,
        imgUnzip_empty_n,
        imgUnzip_read,
        imgUnzip_num_data_valid,
        imgUnzip_fifo_cap,
        m_axis_video_TDATA,
        m_axis_video_TVALID,
        m_axis_video_TREADY,
        m_axis_video_TKEEP,
        m_axis_video_TSTRB,
        m_axis_video_TUSER,
        m_axis_video_TLAST,
        m_axis_video_TID,
        m_axis_video_TDEST,
        Height_val,
        WidthOut_val
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [29:0] imgUnzip_dout;
input   imgUnzip_empty_n;
output   imgUnzip_read;
input  [2:0] imgUnzip_num_data_valid;
input  [2:0] imgUnzip_fifo_cap;
output  [29:0] m_axis_video_TDATA;
output   m_axis_video_TVALID;
input   m_axis_video_TREADY;
output  [3:0] m_axis_video_TKEEP;
output  [3:0] m_axis_video_TSTRB;
output  [0:0] m_axis_video_TUSER;
output  [0:0] m_axis_video_TLAST;
output  [0:0] m_axis_video_TID;
output  [0:0] m_axis_video_TDEST;
input  [15:0] Height_val;
input  [15:0] WidthOut_val;

reg ap_done;
reg ap_idle;
reg ap_ready;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [10:0] empty_fu_114_p1;
reg   [10:0] empty_reg_174;
reg    ap_block_state1;
wire   [10:0] empty_132_fu_118_p1;
reg   [10:0] empty_132_reg_179;
wire   [11:0] add_ln240_fu_126_p2;
reg   [11:0] add_ln240_reg_184;
wire   [0:0] icmp_ln228_fu_132_p2;
reg   [0:0] icmp_ln228_reg_189;
wire   [0:0] and_ln228_fu_157_p2;
reg   [0:0] and_ln228_reg_197;
wire    ap_CS_fsm_state2;
wire    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_ap_start;
wire    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_ap_done;
wire    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_ap_idle;
wire    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_ap_ready;
wire    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_imgUnzip_read;
wire    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_m_axis_video_TREADY;
wire   [29:0] grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_m_axis_video_TDATA;
wire    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_m_axis_video_TVALID;
wire   [3:0] grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_m_axis_video_TKEEP;
wire   [3:0] grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_m_axis_video_TSTRB;
wire   [0:0] grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_m_axis_video_TUSER;
wire   [0:0] grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_m_axis_video_TLAST;
wire   [0:0] grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_m_axis_video_TID;
wire   [0:0] grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_m_axis_video_TDEST;
reg   [0:0] sof_reg_78;
wire    ap_CS_fsm_state3;
reg    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_ap_start_reg;
wire   [0:0] icmp_ln228_1_fu_146_p2;
reg   [29:0] m_axis_video_TDATA_reg;
reg   [3:0] m_axis_video_TKEEP_reg;
reg   [3:0] m_axis_video_TSTRB_reg;
reg   [0:0] m_axis_video_TUSER_reg;
reg   [0:0] m_axis_video_TLAST_reg;
reg   [0:0] m_axis_video_TID_reg;
reg   [0:0] m_axis_video_TDEST_reg;
reg   [10:0] i_fu_62;
wire   [10:0] i_2_fu_151_p2;
wire   [11:0] trunc_ln240_fu_122_p1;
wire    ap_CS_fsm_state4;
wire    regslice_both_m_axis_video_V_data_V_U_apdone_blk;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
reg   [29:0] m_axis_video_TDATA_int_regslice;
wire    m_axis_video_TVALID_int_regslice;
wire    m_axis_video_TREADY_int_regslice;
wire    regslice_both_m_axis_video_V_data_V_U_vld_out;
wire    regslice_both_m_axis_video_V_keep_V_U_apdone_blk;
reg   [3:0] m_axis_video_TKEEP_int_regslice;
wire    regslice_both_m_axis_video_V_keep_V_U_ack_in_dummy;
wire    regslice_both_m_axis_video_V_keep_V_U_vld_out;
wire    regslice_both_m_axis_video_V_strb_V_U_apdone_blk;
reg   [3:0] m_axis_video_TSTRB_int_regslice;
wire    regslice_both_m_axis_video_V_strb_V_U_ack_in_dummy;
wire    regslice_both_m_axis_video_V_strb_V_U_vld_out;
wire    regslice_both_m_axis_video_V_user_V_U_apdone_blk;
reg   [0:0] m_axis_video_TUSER_int_regslice;
wire    regslice_both_m_axis_video_V_user_V_U_ack_in_dummy;
wire    regslice_both_m_axis_video_V_user_V_U_vld_out;
wire    regslice_both_m_axis_video_V_last_V_U_apdone_blk;
reg   [0:0] m_axis_video_TLAST_int_regslice;
wire    regslice_both_m_axis_video_V_last_V_U_ack_in_dummy;
wire    regslice_both_m_axis_video_V_last_V_U_vld_out;
wire    regslice_both_m_axis_video_V_id_V_U_apdone_blk;
reg   [0:0] m_axis_video_TID_int_regslice;
wire    regslice_both_m_axis_video_V_id_V_U_ack_in_dummy;
wire    regslice_both_m_axis_video_V_id_V_U_vld_out;
wire    regslice_both_m_axis_video_V_dest_V_U_apdone_blk;
reg   [0:0] m_axis_video_TDEST_int_regslice;
wire    regslice_both_m_axis_video_V_dest_V_U_ack_in_dummy;
wire    regslice_both_m_axis_video_V_dest_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_ap_start_reg = 1'b0;
#0 i_fu_62 = 11'd0;
end

design_1_v_demosaic_0_0_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2 grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_ap_start),
    .ap_done(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_ap_done),
    .ap_idle(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_ap_idle),
    .ap_ready(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_ap_ready),
    .imgUnzip_dout(imgUnzip_dout),
    .imgUnzip_empty_n(imgUnzip_empty_n),
    .imgUnzip_read(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_imgUnzip_read),
    .imgUnzip_num_data_valid(3'd0),
    .imgUnzip_fifo_cap(3'd0),
    .m_axis_video_TREADY(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_m_axis_video_TREADY),
    .sof(sof_reg_78),
    .empty(empty_reg_174),
    .add_ln240(add_ln240_reg_184),
    .m_axis_video_TDATA(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_m_axis_video_TDATA),
    .m_axis_video_TVALID(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_m_axis_video_TVALID),
    .m_axis_video_TKEEP(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_m_axis_video_TKEEP),
    .m_axis_video_TSTRB(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_m_axis_video_TSTRB),
    .m_axis_video_TUSER(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_m_axis_video_TUSER),
    .m_axis_video_TLAST(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_m_axis_video_TLAST),
    .m_axis_video_TID(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_m_axis_video_TID),
    .m_axis_video_TDEST(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_m_axis_video_TDEST)
);

design_1_v_demosaic_0_0_regslice_both #(
    .DataWidth( 30 ))
regslice_both_m_axis_video_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(m_axis_video_TDATA_int_regslice),
    .vld_in(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_m_axis_video_TVALID),
    .ack_in(m_axis_video_TREADY_int_regslice),
    .data_out(m_axis_video_TDATA),
    .vld_out(regslice_both_m_axis_video_V_data_V_U_vld_out),
    .ack_out(m_axis_video_TREADY),
    .apdone_blk(regslice_both_m_axis_video_V_data_V_U_apdone_blk)
);

design_1_v_demosaic_0_0_regslice_both #(
    .DataWidth( 4 ))
regslice_both_m_axis_video_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(m_axis_video_TKEEP_int_regslice),
    .vld_in(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_m_axis_video_TVALID),
    .ack_in(regslice_both_m_axis_video_V_keep_V_U_ack_in_dummy),
    .data_out(m_axis_video_TKEEP),
    .vld_out(regslice_both_m_axis_video_V_keep_V_U_vld_out),
    .ack_out(m_axis_video_TREADY),
    .apdone_blk(regslice_both_m_axis_video_V_keep_V_U_apdone_blk)
);

design_1_v_demosaic_0_0_regslice_both #(
    .DataWidth( 4 ))
regslice_both_m_axis_video_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(m_axis_video_TSTRB_int_regslice),
    .vld_in(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_m_axis_video_TVALID),
    .ack_in(regslice_both_m_axis_video_V_strb_V_U_ack_in_dummy),
    .data_out(m_axis_video_TSTRB),
    .vld_out(regslice_both_m_axis_video_V_strb_V_U_vld_out),
    .ack_out(m_axis_video_TREADY),
    .apdone_blk(regslice_both_m_axis_video_V_strb_V_U_apdone_blk)
);

design_1_v_demosaic_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_m_axis_video_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(m_axis_video_TUSER_int_regslice),
    .vld_in(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_m_axis_video_TVALID),
    .ack_in(regslice_both_m_axis_video_V_user_V_U_ack_in_dummy),
    .data_out(m_axis_video_TUSER),
    .vld_out(regslice_both_m_axis_video_V_user_V_U_vld_out),
    .ack_out(m_axis_video_TREADY),
    .apdone_blk(regslice_both_m_axis_video_V_user_V_U_apdone_blk)
);

design_1_v_demosaic_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_m_axis_video_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(m_axis_video_TLAST_int_regslice),
    .vld_in(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_m_axis_video_TVALID),
    .ack_in(regslice_both_m_axis_video_V_last_V_U_ack_in_dummy),
    .data_out(m_axis_video_TLAST),
    .vld_out(regslice_both_m_axis_video_V_last_V_U_vld_out),
    .ack_out(m_axis_video_TREADY),
    .apdone_blk(regslice_both_m_axis_video_V_last_V_U_apdone_blk)
);

design_1_v_demosaic_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_m_axis_video_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(m_axis_video_TID_int_regslice),
    .vld_in(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_m_axis_video_TVALID),
    .ack_in(regslice_both_m_axis_video_V_id_V_U_ack_in_dummy),
    .data_out(m_axis_video_TID),
    .vld_out(regslice_both_m_axis_video_V_id_V_U_vld_out),
    .ack_out(m_axis_video_TREADY),
    .apdone_blk(regslice_both_m_axis_video_V_id_V_U_apdone_blk)
);

design_1_v_demosaic_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_m_axis_video_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(m_axis_video_TDEST_int_regslice),
    .vld_in(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_m_axis_video_TVALID),
    .ack_in(regslice_both_m_axis_video_V_dest_V_U_ack_in_dummy),
    .data_out(m_axis_video_TDEST),
    .vld_out(regslice_both_m_axis_video_V_dest_V_U_vld_out),
    .ack_out(m_axis_video_TREADY),
    .apdone_blk(regslice_both_m_axis_video_V_dest_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state4) & (regslice_both_m_axis_video_V_data_V_U_apdone_blk == 1'b0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln228_1_fu_146_p2 == 1'd0))) begin
            grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_ap_start_reg <= 1'b1;
        end else if ((grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_ap_ready == 1'b1)) begin
            grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_fu_62 <= 11'd0;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln228_1_fu_146_p2 == 1'd0))) begin
        i_fu_62 <= i_2_fu_151_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        sof_reg_78 <= and_ln228_reg_197;
    end else if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        sof_reg_78 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        add_ln240_reg_184 <= add_ln240_fu_126_p2;
        empty_132_reg_179 <= empty_132_fu_118_p1;
        empty_reg_174 <= empty_fu_114_p1;
        icmp_ln228_reg_189 <= icmp_ln228_fu_132_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        and_ln228_reg_197 <= and_ln228_fu_157_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_m_axis_video_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        m_axis_video_TDATA_reg <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_m_axis_video_TDATA;
        m_axis_video_TDEST_reg <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_m_axis_video_TDEST;
        m_axis_video_TID_reg <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_m_axis_video_TID;
        m_axis_video_TKEEP_reg <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_m_axis_video_TKEEP;
        m_axis_video_TLAST_reg <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_m_axis_video_TLAST;
        m_axis_video_TSTRB_reg <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_m_axis_video_TSTRB;
        m_axis_video_TUSER_reg <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_m_axis_video_TUSER;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_m_axis_video_V_data_V_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (regslice_both_m_axis_video_V_data_V_U_apdone_blk == 1'b0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (regslice_both_m_axis_video_V_data_V_U_apdone_blk == 1'b0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_m_axis_video_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        m_axis_video_TDATA_int_regslice = grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_m_axis_video_TDATA;
    end else begin
        m_axis_video_TDATA_int_regslice = m_axis_video_TDATA_reg;
    end
end

always @ (*) begin
    if (((grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_m_axis_video_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        m_axis_video_TDEST_int_regslice = grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_m_axis_video_TDEST;
    end else begin
        m_axis_video_TDEST_int_regslice = m_axis_video_TDEST_reg;
    end
end

always @ (*) begin
    if (((grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_m_axis_video_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        m_axis_video_TID_int_regslice = grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_m_axis_video_TID;
    end else begin
        m_axis_video_TID_int_regslice = m_axis_video_TID_reg;
    end
end

always @ (*) begin
    if (((grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_m_axis_video_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        m_axis_video_TKEEP_int_regslice = grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_m_axis_video_TKEEP;
    end else begin
        m_axis_video_TKEEP_int_regslice = m_axis_video_TKEEP_reg;
    end
end

always @ (*) begin
    if (((grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_m_axis_video_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        m_axis_video_TLAST_int_regslice = grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_m_axis_video_TLAST;
    end else begin
        m_axis_video_TLAST_int_regslice = m_axis_video_TLAST_reg;
    end
end

always @ (*) begin
    if (((grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_m_axis_video_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        m_axis_video_TSTRB_int_regslice = grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_m_axis_video_TSTRB;
    end else begin
        m_axis_video_TSTRB_int_regslice = m_axis_video_TSTRB_reg;
    end
end

always @ (*) begin
    if (((grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_m_axis_video_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        m_axis_video_TUSER_int_regslice = grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_m_axis_video_TUSER;
    end else begin
        m_axis_video_TUSER_int_regslice = m_axis_video_TUSER_reg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln228_1_fu_146_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (regslice_both_m_axis_video_V_data_V_U_apdone_blk == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln240_fu_126_p2 = ($signed(trunc_ln240_fu_122_p1) + $signed(12'd4095));

assign and_ln228_fu_157_p2 = (sof_reg_78 & icmp_ln228_reg_189);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign empty_132_fu_118_p1 = Height_val[10:0];

assign empty_fu_114_p1 = WidthOut_val[10:0];

assign grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_ap_start = grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_ap_start_reg;

assign grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_m_axis_video_TREADY = (m_axis_video_TREADY_int_regslice & ap_CS_fsm_state3);

assign i_2_fu_151_p2 = (i_fu_62 + 11'd1);

assign icmp_ln228_1_fu_146_p2 = ((i_fu_62 == empty_132_reg_179) ? 1'b1 : 1'b0);

assign icmp_ln228_fu_132_p2 = ((empty_fu_114_p1 == 11'd0) ? 1'b1 : 1'b0);

assign imgUnzip_read = grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_imgUnzip_read;

assign m_axis_video_TVALID = regslice_both_m_axis_video_V_data_V_U_vld_out;

assign m_axis_video_TVALID_int_regslice = grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_230_2_fu_90_m_axis_video_TVALID;

assign trunc_ln240_fu_122_p1 = WidthOut_val[11:0];

endmodule //design_1_v_demosaic_0_0_MultiPixStream2AXIvideo
