-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity design_1_v_demosaic_0_0_DebayerRandBatG is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    imgRB_dout : IN STD_LOGIC_VECTOR (29 downto 0);
    imgRB_empty_n : IN STD_LOGIC;
    imgRB_read : OUT STD_LOGIC;
    imgRB_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    imgRB_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    imgRgb_din : OUT STD_LOGIC_VECTOR (29 downto 0);
    imgRgb_full_n : IN STD_LOGIC;
    imgRgb_write : OUT STD_LOGIC;
    imgRgb_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
    imgRgb_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
    height_val4_dout : IN STD_LOGIC_VECTOR (10 downto 0);
    height_val4_empty_n : IN STD_LOGIC;
    height_val4_read : OUT STD_LOGIC;
    height_val4_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    height_val4_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    width_val8_dout : IN STD_LOGIC_VECTOR (10 downto 0);
    width_val8_empty_n : IN STD_LOGIC;
    width_val8_read : OUT STD_LOGIC;
    width_val8_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    width_val8_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    bayerPhase_val11_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    bayerPhase_val11_empty_n : IN STD_LOGIC;
    bayerPhase_val11_read : OUT STD_LOGIC;
    bayerPhase_val11_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    bayerPhase_val11_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0) );
end;


architecture behav of design_1_v_demosaic_0_0_DebayerRandBatG is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal height_val4_blk_n : STD_LOGIC;
    signal width_val8_blk_n : STD_LOGIC;
    signal bayerPhase_val11_blk_n : STD_LOGIC;
    signal width_val8_read_reg_352 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal height_val4_read_reg_357 : STD_LOGIC_VECTOR (10 downto 0);
    signal x_phase_fu_168_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal x_phase_reg_362 : STD_LOGIC_VECTOR (0 downto 0);
    signal loopHeight_fu_172_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal loopHeight_reg_367 : STD_LOGIC_VECTOR (10 downto 0);
    signal loopWidth_fu_178_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal loopWidth_reg_372 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln_reg_377 : STD_LOGIC_VECTOR (14 downto 0);
    signal y_5_reg_382 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal p_0_0_0_0_011581703_lcssa1747_i_load_reg_391 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_1_0_0_011591706_lcssa1749_i_load_reg_396 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_2_0_0_011601709_lcssa1751_i_load_reg_401 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_0116617811793_lcssa1829_i_load_reg_406 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_0116517831795_lcssa1831_i_load_reg_411 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_0116417851797_lcssa1833_i_load_reg_416 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_0_0_011521798_lcssa1835_i_load_reg_421 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_1_0_0_011531800_lcssa1837_i_load_reg_426 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_2_0_0_011541802_lcssa1839_i_load_reg_431 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_01179_217751805_lcssa1841_i_load_reg_436 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_01178_217771807_lcssa1843_i_load_reg_441 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_01177_217791809_lcssa1845_i_load_reg_446 : STD_LOGIC_VECTOR (9 downto 0);
    signal xor_ln1014_1_fu_267_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal xor_ln1014_1_reg_451 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_ap_start : STD_LOGIC;
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_ap_done : STD_LOGIC;
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_ap_idle : STD_LOGIC;
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_ap_ready : STD_LOGIC;
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_imgRB_read : STD_LOGIC;
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_imgRgb_din : STD_LOGIC_VECTOR (29 downto 0);
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_imgRgb_write : STD_LOGIC;
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_p_0_0_01177_217791808_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_p_0_0_01177_217791808_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_p_0_0_01178_217771806_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_p_0_0_01178_217771806_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_p_0_0_01179_217751804_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_p_0_0_01179_217751804_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_right_2_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_right_2_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_right_1_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_right_1_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_right_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_right_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_p_0_0_0116417851796_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_p_0_0_0116417851796_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_p_0_0_0116517831794_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_p_0_0_0116517831794_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_p_0_0_0116617811792_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_p_0_0_0116617811792_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_p_0_2_0_0_011601711_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_p_0_2_0_0_011601711_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_p_0_1_0_0_011591708_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_p_0_1_0_0_011591708_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_p_0_0_0_0_011581705_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_p_0_0_0_0_011581705_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal p_0_0_01177_217791809_lcssa1845_i_fu_108 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_01178_217771807_lcssa1843_i_fu_104 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_01179_217751805_lcssa1841_i_fu_100 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_2_0_0_011541802_lcssa1839_i_fu_96 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_1_0_0_011531800_lcssa1837_i_fu_92 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_0_0_011521798_lcssa1835_i_fu_88 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_0116417851797_lcssa1833_i_fu_84 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_0116517831795_lcssa1831_i_fu_80 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_0116617811793_lcssa1829_i_fu_76 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_2_0_0_011601709_lcssa1751_i_fu_72 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_1_0_0_011591706_lcssa1749_i_fu_68 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_0_0_011581703_lcssa1747_i_fu_64 : STD_LOGIC_VECTOR (9 downto 0);
    signal y_fu_60 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    signal y_6_fu_207_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln878_fu_202_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln878_fu_254_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1014_fu_257_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln1014_fu_263_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component design_1_v_demosaic_0_0_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        imgRB_dout : IN STD_LOGIC_VECTOR (29 downto 0);
        imgRB_empty_n : IN STD_LOGIC;
        imgRB_read : OUT STD_LOGIC;
        imgRB_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        imgRB_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        imgRgb_din : OUT STD_LOGIC_VECTOR (29 downto 0);
        imgRgb_full_n : IN STD_LOGIC;
        imgRgb_write : OUT STD_LOGIC;
        imgRgb_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
        imgRgb_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
        p_0_0_01177_217791809_lcssa1845_i : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_01178_217771807_lcssa1843_i : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_01179_217751805_lcssa1841_i : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_2_0_0_011541802_lcssa1839_i : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_1_0_0_011531800_lcssa1837_i : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_0_0_011521798_lcssa1835_i : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_0116417851797_lcssa1833_i : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_0116517831795_lcssa1831_i : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_0116617811793_lcssa1829_i : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_2_0_0_011601709_lcssa1751_i : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_1_0_0_011591706_lcssa1749_i : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_0_0_011581703_lcssa1747_i : IN STD_LOGIC_VECTOR (9 downto 0);
        y : IN STD_LOGIC_VECTOR (10 downto 0);
        height_val4_load : IN STD_LOGIC_VECTOR (10 downto 0);
        loopWidth : IN STD_LOGIC_VECTOR (10 downto 0);
        empty : IN STD_LOGIC_VECTOR (0 downto 0);
        xor_ln1014_1 : IN STD_LOGIC_VECTOR (14 downto 0);
        width_val8_load : IN STD_LOGIC_VECTOR (10 downto 0);
        p_0_0_01177_217791808_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_01177_217791808_i_out_ap_vld : OUT STD_LOGIC;
        p_0_0_01178_217771806_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_01178_217771806_i_out_ap_vld : OUT STD_LOGIC;
        p_0_0_01179_217751804_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_01179_217751804_i_out_ap_vld : OUT STD_LOGIC;
        right_2_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        right_2_out_ap_vld : OUT STD_LOGIC;
        right_1_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        right_1_out_ap_vld : OUT STD_LOGIC;
        right_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        right_out_ap_vld : OUT STD_LOGIC;
        p_0_0_0116417851796_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_0116417851796_i_out_ap_vld : OUT STD_LOGIC;
        p_0_0_0116517831794_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_0116517831794_i_out_ap_vld : OUT STD_LOGIC;
        p_0_0_0116617811792_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_0116617811792_i_out_ap_vld : OUT STD_LOGIC;
        p_0_2_0_0_011601711_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_2_0_0_011601711_i_out_ap_vld : OUT STD_LOGIC;
        p_0_1_0_0_011591708_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_1_0_0_011591708_i_out_ap_vld : OUT STD_LOGIC;
        p_0_0_0_0_011581705_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_0_0_011581705_i_out_ap_vld : OUT STD_LOGIC );
    end component;



begin
    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130 : component design_1_v_demosaic_0_0_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_ap_start,
        ap_done => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_ap_done,
        ap_idle => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_ap_idle,
        ap_ready => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_ap_ready,
        imgRB_dout => imgRB_dout,
        imgRB_empty_n => imgRB_empty_n,
        imgRB_read => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_imgRB_read,
        imgRB_num_data_valid => ap_const_lv3_0,
        imgRB_fifo_cap => ap_const_lv3_0,
        imgRgb_din => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_imgRgb_din,
        imgRgb_full_n => imgRgb_full_n,
        imgRgb_write => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_imgRgb_write,
        imgRgb_num_data_valid => imgRgb_num_data_valid,
        imgRgb_fifo_cap => imgRgb_fifo_cap,
        p_0_0_01177_217791809_lcssa1845_i => p_0_0_01177_217791809_lcssa1845_i_load_reg_446,
        p_0_0_01178_217771807_lcssa1843_i => p_0_0_01178_217771807_lcssa1843_i_load_reg_441,
        p_0_0_01179_217751805_lcssa1841_i => p_0_0_01179_217751805_lcssa1841_i_load_reg_436,
        p_0_2_0_0_011541802_lcssa1839_i => p_0_2_0_0_011541802_lcssa1839_i_load_reg_431,
        p_0_1_0_0_011531800_lcssa1837_i => p_0_1_0_0_011531800_lcssa1837_i_load_reg_426,
        p_0_0_0_0_011521798_lcssa1835_i => p_0_0_0_0_011521798_lcssa1835_i_load_reg_421,
        p_0_0_0116417851797_lcssa1833_i => p_0_0_0116417851797_lcssa1833_i_load_reg_416,
        p_0_0_0116517831795_lcssa1831_i => p_0_0_0116517831795_lcssa1831_i_load_reg_411,
        p_0_0_0116617811793_lcssa1829_i => p_0_0_0116617811793_lcssa1829_i_load_reg_406,
        p_0_2_0_0_011601709_lcssa1751_i => p_0_2_0_0_011601709_lcssa1751_i_load_reg_401,
        p_0_1_0_0_011591706_lcssa1749_i => p_0_1_0_0_011591706_lcssa1749_i_load_reg_396,
        p_0_0_0_0_011581703_lcssa1747_i => p_0_0_0_0_011581703_lcssa1747_i_load_reg_391,
        y => y_5_reg_382,
        height_val4_load => height_val4_read_reg_357,
        loopWidth => loopWidth_reg_372,
        empty => x_phase_reg_362,
        xor_ln1014_1 => xor_ln1014_1_reg_451,
        width_val8_load => width_val8_read_reg_352,
        p_0_0_01177_217791808_i_out => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_p_0_0_01177_217791808_i_out,
        p_0_0_01177_217791808_i_out_ap_vld => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_p_0_0_01177_217791808_i_out_ap_vld,
        p_0_0_01178_217771806_i_out => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_p_0_0_01178_217771806_i_out,
        p_0_0_01178_217771806_i_out_ap_vld => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_p_0_0_01178_217771806_i_out_ap_vld,
        p_0_0_01179_217751804_i_out => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_p_0_0_01179_217751804_i_out,
        p_0_0_01179_217751804_i_out_ap_vld => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_p_0_0_01179_217751804_i_out_ap_vld,
        right_2_out => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_right_2_out,
        right_2_out_ap_vld => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_right_2_out_ap_vld,
        right_1_out => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_right_1_out,
        right_1_out_ap_vld => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_right_1_out_ap_vld,
        right_out => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_right_out,
        right_out_ap_vld => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_right_out_ap_vld,
        p_0_0_0116417851796_i_out => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_p_0_0_0116417851796_i_out,
        p_0_0_0116417851796_i_out_ap_vld => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_p_0_0_0116417851796_i_out_ap_vld,
        p_0_0_0116517831794_i_out => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_p_0_0_0116517831794_i_out,
        p_0_0_0116517831794_i_out_ap_vld => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_p_0_0_0116517831794_i_out_ap_vld,
        p_0_0_0116617811792_i_out => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_p_0_0_0116617811792_i_out,
        p_0_0_0116617811792_i_out_ap_vld => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_p_0_0_0116617811792_i_out_ap_vld,
        p_0_2_0_0_011601711_i_out => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_p_0_2_0_0_011601711_i_out,
        p_0_2_0_0_011601711_i_out_ap_vld => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_p_0_2_0_0_011601711_i_out_ap_vld,
        p_0_1_0_0_011591708_i_out => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_p_0_1_0_0_011591708_i_out,
        p_0_1_0_0_011591708_i_out_ap_vld => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_p_0_1_0_0_011591708_i_out_ap_vld,
        p_0_0_0_0_011581705_i_out => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_p_0_0_0_0_011581705_i_out,
        p_0_0_0_0_011581705_i_out_ap_vld => grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_p_0_0_0_0_011581705_i_out_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((icmp_ln878_fu_202_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_ap_ready = ap_const_logic_1)) then 
                    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    y_fu_60_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                y_fu_60 <= ap_const_lv11_0;
            elsif (((icmp_ln878_fu_202_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                y_fu_60 <= y_6_fu_207_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                height_val4_read_reg_357 <= height_val4_dout;
                loopHeight_reg_367 <= loopHeight_fu_172_p2;
                loopWidth_reg_372 <= loopWidth_fu_178_p2;
                trunc_ln_reg_377 <= bayerPhase_val11_dout(15 downto 1);
                width_val8_read_reg_352 <= width_val8_dout;
                x_phase_reg_362 <= x_phase_fu_168_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_p_0_0_0116417851796_i_out_ap_vld = ap_const_logic_1))) then
                p_0_0_0116417851797_lcssa1833_i_fu_84 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_p_0_0_0116417851796_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                p_0_0_0116417851797_lcssa1833_i_load_reg_416 <= p_0_0_0116417851797_lcssa1833_i_fu_84;
                p_0_0_0116517831795_lcssa1831_i_load_reg_411 <= p_0_0_0116517831795_lcssa1831_i_fu_80;
                p_0_0_0116617811793_lcssa1829_i_load_reg_406 <= p_0_0_0116617811793_lcssa1829_i_fu_76;
                p_0_0_01177_217791809_lcssa1845_i_load_reg_446 <= p_0_0_01177_217791809_lcssa1845_i_fu_108;
                p_0_0_01178_217771807_lcssa1843_i_load_reg_441 <= p_0_0_01178_217771807_lcssa1843_i_fu_104;
                p_0_0_01179_217751805_lcssa1841_i_load_reg_436 <= p_0_0_01179_217751805_lcssa1841_i_fu_100;
                p_0_0_0_0_011521798_lcssa1835_i_load_reg_421 <= p_0_0_0_0_011521798_lcssa1835_i_fu_88;
                p_0_0_0_0_011581703_lcssa1747_i_load_reg_391 <= p_0_0_0_0_011581703_lcssa1747_i_fu_64;
                p_0_1_0_0_011531800_lcssa1837_i_load_reg_426 <= p_0_1_0_0_011531800_lcssa1837_i_fu_92;
                p_0_1_0_0_011591706_lcssa1749_i_load_reg_396 <= p_0_1_0_0_011591706_lcssa1749_i_fu_68;
                p_0_2_0_0_011541802_lcssa1839_i_load_reg_431 <= p_0_2_0_0_011541802_lcssa1839_i_fu_96;
                p_0_2_0_0_011601709_lcssa1751_i_load_reg_401 <= p_0_2_0_0_011601709_lcssa1751_i_fu_72;
                y_5_reg_382 <= y_fu_60;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_p_0_0_0116517831794_i_out_ap_vld = ap_const_logic_1))) then
                p_0_0_0116517831795_lcssa1831_i_fu_80 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_p_0_0_0116517831794_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_p_0_0_0116617811792_i_out_ap_vld = ap_const_logic_1))) then
                p_0_0_0116617811793_lcssa1829_i_fu_76 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_p_0_0_0116617811792_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_p_0_0_01177_217791808_i_out_ap_vld = ap_const_logic_1))) then
                p_0_0_01177_217791809_lcssa1845_i_fu_108 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_p_0_0_01177_217791808_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_p_0_0_01178_217771806_i_out_ap_vld = ap_const_logic_1))) then
                p_0_0_01178_217771807_lcssa1843_i_fu_104 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_p_0_0_01178_217771806_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_p_0_0_01179_217751804_i_out_ap_vld = ap_const_logic_1))) then
                p_0_0_01179_217751805_lcssa1841_i_fu_100 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_p_0_0_01179_217751804_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_right_out_ap_vld = ap_const_logic_1))) then
                p_0_0_0_0_011521798_lcssa1835_i_fu_88 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_right_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_p_0_0_0_0_011581705_i_out_ap_vld = ap_const_logic_1))) then
                p_0_0_0_0_011581703_lcssa1747_i_fu_64 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_p_0_0_0_0_011581705_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_right_1_out_ap_vld = ap_const_logic_1))) then
                p_0_1_0_0_011531800_lcssa1837_i_fu_92 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_right_1_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_p_0_1_0_0_011591708_i_out_ap_vld = ap_const_logic_1))) then
                p_0_1_0_0_011591706_lcssa1749_i_fu_68 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_p_0_1_0_0_011591708_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_right_2_out_ap_vld = ap_const_logic_1))) then
                p_0_2_0_0_011541802_lcssa1839_i_fu_96 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_right_2_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_p_0_2_0_0_011601711_i_out_ap_vld = ap_const_logic_1))) then
                p_0_2_0_0_011601709_lcssa1751_i_fu_72 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_p_0_2_0_0_011601711_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                xor_ln1014_1_reg_451 <= xor_ln1014_1_fu_267_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1, ap_CS_fsm_state2, grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_ap_done, ap_CS_fsm_state4, icmp_ln878_fu_202_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln878_fu_202_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_ap_done)
    begin
        if ((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, height_val4_empty_n, width_val8_empty_n, bayerPhase_val11_empty_n)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (bayerPhase_val11_empty_n = ap_const_logic_0) or (width_val8_empty_n = ap_const_logic_0) or (height_val4_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state2, icmp_ln878_fu_202_p2)
    begin
        if (((icmp_ln878_fu_202_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln878_fu_202_p2)
    begin
        if (((icmp_ln878_fu_202_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    bayerPhase_val11_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, bayerPhase_val11_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            bayerPhase_val11_blk_n <= bayerPhase_val11_empty_n;
        else 
            bayerPhase_val11_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    bayerPhase_val11_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            bayerPhase_val11_read <= ap_const_logic_1;
        else 
            bayerPhase_val11_read <= ap_const_logic_0;
        end if; 
    end process;

    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_ap_start <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_ap_start_reg;

    height_val4_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, height_val4_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            height_val4_blk_n <= height_val4_empty_n;
        else 
            height_val4_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    height_val4_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            height_val4_read <= ap_const_logic_1;
        else 
            height_val4_read <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln878_fu_202_p2 <= "1" when (y_fu_60 = loopHeight_reg_367) else "0";
    imgRB_read <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_imgRB_read;
    imgRgb_din <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_imgRgb_din;
    imgRgb_write <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_130_imgRgb_write;
    loopHeight_fu_172_p2 <= std_logic_vector(unsigned(height_val4_dout) + unsigned(ap_const_lv11_1));
    loopWidth_fu_178_p2 <= std_logic_vector(unsigned(width_val8_dout) + unsigned(ap_const_lv11_1));
    trunc_ln878_fu_254_p1 <= y_5_reg_382(1 - 1 downto 0);

    width_val8_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, width_val8_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            width_val8_blk_n <= width_val8_empty_n;
        else 
            width_val8_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    width_val8_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            width_val8_read <= ap_const_logic_1;
        else 
            width_val8_read <= ap_const_logic_0;
        end if; 
    end process;

    x_phase_fu_168_p1 <= bayerPhase_val11_dout(1 - 1 downto 0);
    xor_ln1014_1_fu_267_p2 <= (zext_ln1014_fu_263_p1 xor trunc_ln_reg_377);
    xor_ln1014_fu_257_p2 <= (trunc_ln878_fu_254_p1 xor ap_const_lv1_1);
    y_6_fu_207_p2 <= std_logic_vector(unsigned(y_fu_60) + unsigned(ap_const_lv11_1));
    zext_ln1014_fu_263_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(xor_ln1014_fu_257_p2),15));
end behav;
