// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module design_1_v_demosaic_0_0_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        imgRB_dout,
        imgRB_empty_n,
        imgRB_read,
        imgRB_num_data_valid,
        imgRB_fifo_cap,
        imgRgb_din,
        imgRgb_full_n,
        imgRgb_write,
        imgRgb_num_data_valid,
        imgRgb_fifo_cap,
        p_0_0_01177_217791809_lcssa1845_i,
        p_0_0_01178_217771807_lcssa1843_i,
        p_0_0_01179_217751805_lcssa1841_i,
        p_0_2_0_0_011541802_lcssa1839_i,
        p_0_1_0_0_011531800_lcssa1837_i,
        p_0_0_0_0_011521798_lcssa1835_i,
        p_0_0_0116417851797_lcssa1833_i,
        p_0_0_0116517831795_lcssa1831_i,
        p_0_0_0116617811793_lcssa1829_i,
        p_0_2_0_0_011601709_lcssa1751_i,
        p_0_1_0_0_011591706_lcssa1749_i,
        p_0_0_0_0_011581703_lcssa1747_i,
        y,
        height_val4_load,
        loopWidth,
        empty,
        xor_ln1014_1,
        width_val8_load,
        p_0_0_01177_217791808_i_out,
        p_0_0_01177_217791808_i_out_ap_vld,
        p_0_0_01178_217771806_i_out,
        p_0_0_01178_217771806_i_out_ap_vld,
        p_0_0_01179_217751804_i_out,
        p_0_0_01179_217751804_i_out_ap_vld,
        right_2_out,
        right_2_out_ap_vld,
        right_1_out,
        right_1_out_ap_vld,
        right_out,
        right_out_ap_vld,
        p_0_0_0116417851796_i_out,
        p_0_0_0116417851796_i_out_ap_vld,
        p_0_0_0116517831794_i_out,
        p_0_0_0116517831794_i_out_ap_vld,
        p_0_0_0116617811792_i_out,
        p_0_0_0116617811792_i_out_ap_vld,
        p_0_2_0_0_011601711_i_out,
        p_0_2_0_0_011601711_i_out_ap_vld,
        p_0_1_0_0_011591708_i_out,
        p_0_1_0_0_011591708_i_out_ap_vld,
        p_0_0_0_0_011581705_i_out,
        p_0_0_0_0_011581705_i_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [29:0] imgRB_dout;
input   imgRB_empty_n;
output   imgRB_read;
input  [2:0] imgRB_num_data_valid;
input  [2:0] imgRB_fifo_cap;
output  [29:0] imgRgb_din;
input   imgRgb_full_n;
output   imgRgb_write;
input  [31:0] imgRgb_num_data_valid;
input  [31:0] imgRgb_fifo_cap;
input  [9:0] p_0_0_01177_217791809_lcssa1845_i;
input  [9:0] p_0_0_01178_217771807_lcssa1843_i;
input  [9:0] p_0_0_01179_217751805_lcssa1841_i;
input  [9:0] p_0_2_0_0_011541802_lcssa1839_i;
input  [9:0] p_0_1_0_0_011531800_lcssa1837_i;
input  [9:0] p_0_0_0_0_011521798_lcssa1835_i;
input  [9:0] p_0_0_0116417851797_lcssa1833_i;
input  [9:0] p_0_0_0116517831795_lcssa1831_i;
input  [9:0] p_0_0_0116617811793_lcssa1829_i;
input  [9:0] p_0_2_0_0_011601709_lcssa1751_i;
input  [9:0] p_0_1_0_0_011591706_lcssa1749_i;
input  [9:0] p_0_0_0_0_011581703_lcssa1747_i;
input  [10:0] y;
input  [10:0] height_val4_load;
input  [10:0] loopWidth;
input  [0:0] empty;
input  [14:0] xor_ln1014_1;
input  [10:0] width_val8_load;
output  [9:0] p_0_0_01177_217791808_i_out;
output   p_0_0_01177_217791808_i_out_ap_vld;
output  [9:0] p_0_0_01178_217771806_i_out;
output   p_0_0_01178_217771806_i_out_ap_vld;
output  [9:0] p_0_0_01179_217751804_i_out;
output   p_0_0_01179_217751804_i_out_ap_vld;
output  [9:0] right_2_out;
output   right_2_out_ap_vld;
output  [9:0] right_1_out;
output   right_1_out_ap_vld;
output  [9:0] right_out;
output   right_out_ap_vld;
output  [9:0] p_0_0_0116417851796_i_out;
output   p_0_0_0116417851796_i_out_ap_vld;
output  [9:0] p_0_0_0116517831794_i_out;
output   p_0_0_0116517831794_i_out_ap_vld;
output  [9:0] p_0_0_0116617811792_i_out;
output   p_0_0_0116617811792_i_out_ap_vld;
output  [9:0] p_0_2_0_0_011601711_i_out;
output   p_0_2_0_0_011601711_i_out_ap_vld;
output  [9:0] p_0_1_0_0_011591708_i_out;
output   p_0_1_0_0_011591708_i_out_ap_vld;
output  [9:0] p_0_0_0_0_011581705_i_out;
output   p_0_0_0_0_011581705_i_out_ap_vld;

reg ap_idle;
reg imgRB_read;
reg imgRgb_write;
reg p_0_0_01177_217791808_i_out_ap_vld;
reg p_0_0_01178_217771806_i_out_ap_vld;
reg p_0_0_01179_217751804_i_out_ap_vld;
reg right_2_out_ap_vld;
reg right_1_out_ap_vld;
reg right_out_ap_vld;
reg p_0_0_0116417851796_i_out_ap_vld;
reg p_0_0_0116517831794_i_out_ap_vld;
reg p_0_0_0116617811792_i_out_ap_vld;
reg p_0_2_0_0_011601711_i_out_ap_vld;
reg p_0_1_0_0_011591708_i_out_ap_vld;
reg p_0_0_0_0_011581705_i_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
reg   [0:0] icmp_ln881_reg_1879;
reg   [0:0] icmp_ln891_reg_1883;
reg   [0:0] icmp_ln911_reg_1868;
reg    ap_predicate_op99_read_state2;
reg    ap_block_state2_pp0_stage0_iter1;
reg   [0:0] and_ln1052_reg_1921;
reg   [0:0] and_ln1052_reg_1921_pp0_iter3_reg;
reg    ap_block_state5_pp0_stage0_iter4_grp1;
reg    ap_block_pp0_stage0_subdone_grp1_done_reg;
reg    ap_block_pp0_stage0_subdone_grp1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln881_fu_581_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    imgRB_blk_n;
wire    ap_block_pp0_stage0;
reg    imgRgb_blk_n;
wire    ap_block_pp0_stage0_grp1;
reg   [9:0] p_0_0_01178_21777_ph_i_reg_362;
reg   [9:0] pix_8_reg_444;
reg   [9:0] pix_8_reg_444_pp0_iter3_reg;
reg    ap_block_pp0_stage0_11001;
reg   [9:0] pix_7_reg_454;
reg   [9:0] pix_7_reg_454_pp0_iter3_reg;
reg   [9:0] pix_reg_464;
reg   [9:0] pix_reg_464_pp0_iter3_reg;
wire    ap_block_pp0_stage0_11001_grp0;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg;
wire    ap_block_pp0_stage0_subdone_grp0;
wire   [0:0] icmp_ln911_fu_501_p2;
wire   [0:0] icmp_ln975_fu_507_p2;
reg   [0:0] icmp_ln975_reg_1872;
reg   [0:0] icmp_ln881_reg_1879_pp0_iter1_reg;
reg   [0:0] icmp_ln881_reg_1879_pp0_iter2_reg;
wire   [0:0] icmp_ln891_fu_603_p2;
reg   [0:0] icmp_ln891_reg_1883_pp0_iter1_reg;
reg   [10:0] lineBuffer_addr_reg_1887;
reg   [10:0] lineBuffer_2_addr_reg_1893;
reg   [10:0] lineBuffer_2_addr_reg_1893_pp0_iter1_reg;
wire   [0:0] icmp_ln957_fu_609_p2;
reg   [0:0] icmp_ln957_reg_1899;
reg   [0:0] icmp_ln957_reg_1899_pp0_iter1_reg;
wire   [0:0] icmp_ln1014_fu_631_p2;
reg   [0:0] icmp_ln1014_reg_1915;
reg   [0:0] icmp_ln1014_reg_1915_pp0_iter1_reg;
reg   [0:0] icmp_ln1014_reg_1915_pp0_iter2_reg;
reg   [0:0] icmp_ln1014_reg_1915_pp0_iter3_reg;
wire   [0:0] and_ln1052_fu_643_p2;
reg   [0:0] and_ln1052_reg_1921_pp0_iter1_reg;
reg   [0:0] and_ln1052_reg_1921_pp0_iter2_reg;
reg   [9:0] p_0_0_0116617811792_i_load_reg_1925;
reg   [9:0] p_0_0_0116617811792_i_load_reg_1925_pp0_iter2_reg;
reg   [9:0] p_0_0_0116517831794_i_load_reg_1931;
reg   [9:0] p_0_0_0116517831794_i_load_reg_1931_pp0_iter2_reg;
reg   [9:0] right_3_reg_1937;
reg   [9:0] right_3_reg_1937_pp0_iter2_reg;
reg   [9:0] right_4_reg_1944;
reg   [9:0] right_4_reg_1944_pp0_iter2_reg;
reg   [9:0] right_5_reg_1951;
reg   [9:0] right_5_reg_1951_pp0_iter2_reg;
reg   [9:0] p_0_0_01179_217751804_i_load_reg_1958;
reg   [9:0] p_0_0_01179_217751804_i_load_reg_1958_pp0_iter2_reg;
reg   [9:0] p_0_0_01178_217771806_i_load_reg_1964;
reg   [9:0] p_0_0_01178_217771806_i_load_reg_1964_pp0_iter2_reg;
wire   [9:0] trunc_ln902_fu_675_p1;
reg   [9:0] trunc_ln902_reg_1970;
reg   [9:0] tmp_i_reg_1976;
reg   [9:0] tmp_1_i_reg_1983;
reg   [9:0] tmp_4_i_reg_1991;
wire   [9:0] select_ln957_7_fu_743_p3;
reg   [9:0] select_ln957_7_reg_2002;
wire   [9:0] select_ln957_8_fu_750_p3;
reg   [9:0] select_ln957_8_reg_2007;
wire   [9:0] select_ln957_10_fu_757_p3;
reg   [9:0] select_ln957_10_reg_2012;
wire   [9:0] select_ln957_11_fu_764_p3;
reg   [9:0] select_ln957_11_reg_2017;
wire   [9:0] select_ln975_fu_771_p3;
reg   [9:0] select_ln975_reg_2022;
reg   [9:0] p_0_0_0116417851796_i_load_reg_2027;
reg   [9:0] p_0_0_01177_217791808_i_load_reg_2032;
reg   [9:0] p_0_0_0_0_011581705_i_load_reg_2037;
reg   [9:0] p_0_1_0_0_011591708_i_load_reg_2042;
reg   [9:0] p_0_2_0_0_011601711_i_load_reg_2047;
wire   [10:0] sub_ln1023_fu_935_p2;
reg   [10:0] sub_ln1023_reg_2052;
wire   [9:0] trunc_ln61_fu_941_p1;
reg   [9:0] trunc_ln61_reg_2057;
wire   [9:0] sub_ln61_fu_945_p2;
reg   [9:0] sub_ln61_reg_2062;
wire   [10:0] sub_ln1025_fu_999_p2;
reg   [10:0] sub_ln1025_reg_2067;
wire   [9:0] trunc_ln61_5_fu_1005_p1;
reg   [9:0] trunc_ln61_5_reg_2072;
wire   [9:0] sub_ln61_5_fu_1009_p2;
reg   [9:0] sub_ln61_5_reg_2077;
wire   [10:0] sub_ln1027_fu_1063_p2;
reg   [10:0] sub_ln1027_reg_2082;
wire   [9:0] trunc_ln61_7_fu_1069_p1;
reg   [9:0] trunc_ln61_7_reg_2087;
wire   [10:0] sub_ln1028_fu_1081_p2;
reg   [10:0] sub_ln1028_reg_2093;
wire   [9:0] trunc_ln61_8_fu_1087_p1;
reg   [9:0] trunc_ln61_8_reg_2098;
wire   [10:0] add_ln1030_2_fu_1099_p2;
reg   [10:0] add_ln1030_2_reg_2104;
wire   [10:0] sub_ln1033_fu_1105_p2;
reg   [10:0] sub_ln1033_reg_2109;
wire   [10:0] sub_ln1033_1_fu_1111_p2;
reg   [10:0] sub_ln1033_1_reg_2114;
wire   [10:0] sub_ln1034_fu_1117_p2;
reg   [10:0] sub_ln1034_reg_2119;
wire   [10:0] sub_ln1034_1_fu_1123_p2;
reg   [10:0] sub_ln1034_1_reg_2124;
wire   [10:0] sub_ln1039_fu_1129_p2;
reg   [10:0] sub_ln1039_reg_2129;
wire   [10:0] sub_ln1039_1_fu_1135_p2;
reg   [10:0] sub_ln1039_1_reg_2134;
wire   [10:0] sub_ln1040_fu_1141_p2;
reg   [10:0] sub_ln1040_reg_2139;
wire   [10:0] sub_ln1040_1_fu_1147_p2;
reg   [10:0] sub_ln1040_1_reg_2144;
wire  signed [11:0] r_0_in_i_fu_1551_p2;
reg  signed [11:0] r_0_in_i_reg_2149;
reg    ap_block_pp0_stage0_11001_grp1;
wire  signed [11:0] b_0_in_i_fu_1569_p2;
reg  signed [11:0] b_0_in_i_reg_2155;
reg   [1:0] tmp_21_reg_2161;
reg   [1:0] tmp_23_reg_2166;
reg    ap_condition_exit_pp0_iter2_stage0;
wire   [10:0] lineBuffer_2_address0;
wire   [10:0] lineBuffer_2_address1;
wire   [29:0] lineBuffer_2_q1;
wire   [10:0] lineBuffer_address0;
wire   [10:0] lineBuffer_address1;
wire   [29:0] lineBuffer_q1;
reg   [9:0] ap_phi_mux_p_0_0_01178_21777_ph_i_phi_fu_365_p4;
wire   [9:0] ap_phi_reg_pp0_iter1_p_0_0_01178_21777_ph_i_reg_362;
reg   [9:0] ap_phi_mux_p_0_0_01179_21775_ph_i_phi_fu_375_p4;
wire   [9:0] trunc_ln913_fu_717_p1;
wire   [9:0] ap_phi_reg_pp0_iter1_p_0_0_01179_21775_ph_i_reg_372;
wire   [9:0] ap_phi_reg_pp0_iter0_p_0_0_01177_21779_ph_i_reg_381;
reg   [9:0] ap_phi_reg_pp0_iter1_p_0_0_01177_21779_ph_i_reg_381;
reg   [9:0] ap_phi_reg_pp0_iter2_p_0_0_01177_21779_ph_i_reg_381;
reg   [9:0] ap_phi_mux_down_2_phi_fu_393_p4;
wire   [9:0] select_ln957_9_fu_879_p3;
wire   [9:0] ap_phi_reg_pp0_iter2_down_2_reg_390;
reg   [9:0] ap_phi_mux_down_1_phi_fu_402_p4;
reg   [9:0] ap_phi_reg_pp0_iter2_down_1_reg_399;
wire   [9:0] ap_phi_reg_pp0_iter0_down_1_reg_399;
reg   [9:0] ap_phi_reg_pp0_iter1_down_1_reg_399;
reg   [9:0] ap_phi_mux_down_phi_fu_411_p4;
reg   [9:0] ap_phi_reg_pp0_iter2_down_reg_408;
wire   [9:0] ap_phi_reg_pp0_iter0_down_reg_408;
reg   [9:0] ap_phi_reg_pp0_iter1_down_reg_408;
reg   [9:0] ap_phi_mux_left_2_phi_fu_420_p4;
wire   [9:0] select_ln957_5_fu_865_p3;
wire   [9:0] ap_phi_reg_pp0_iter2_left_2_reg_417;
reg   [9:0] ap_phi_mux_left_1_phi_fu_429_p4;
wire   [9:0] select_ln957_4_fu_858_p3;
wire   [9:0] ap_phi_reg_pp0_iter2_left_1_reg_426;
reg   [9:0] ap_phi_mux_left_phi_fu_438_p4;
wire   [9:0] select_ln957_3_fu_851_p3;
wire   [9:0] ap_phi_reg_pp0_iter2_left_reg_435;
reg   [9:0] ap_phi_mux_pix_8_phi_fu_447_p4;
wire   [9:0] select_ln957_2_fu_845_p3;
reg   [9:0] ap_phi_reg_pp0_iter2_pix_8_reg_444;
wire   [9:0] ap_phi_reg_pp0_iter0_pix_8_reg_444;
reg   [9:0] ap_phi_reg_pp0_iter1_pix_8_reg_444;
reg   [9:0] ap_phi_mux_pix_7_phi_fu_457_p4;
wire   [9:0] select_ln957_1_fu_839_p3;
reg   [9:0] ap_phi_reg_pp0_iter2_pix_7_reg_454;
wire   [9:0] ap_phi_reg_pp0_iter0_pix_7_reg_454;
reg   [9:0] ap_phi_reg_pp0_iter1_pix_7_reg_454;
reg   [9:0] ap_phi_mux_pix_phi_fu_467_p4;
wire   [9:0] select_ln957_fu_833_p3;
reg   [9:0] ap_phi_reg_pp0_iter2_pix_reg_464;
wire   [9:0] ap_phi_reg_pp0_iter0_pix_reg_464;
reg   [9:0] ap_phi_reg_pp0_iter1_pix_reg_464;
reg   [9:0] ap_phi_mux_up_2_phi_fu_477_p4;
wire   [9:0] select_ln957_6_fu_872_p3;
wire   [9:0] ap_phi_reg_pp0_iter2_up_2_reg_474;
reg   [9:0] ap_phi_mux_up_1_phi_fu_486_p4;
reg   [9:0] ap_phi_reg_pp0_iter2_up_1_reg_483;
wire   [9:0] ap_phi_reg_pp0_iter0_up_1_reg_483;
reg   [9:0] ap_phi_reg_pp0_iter1_up_1_reg_483;
reg   [9:0] ap_phi_mux_up_phi_fu_495_p4;
reg   [9:0] ap_phi_reg_pp0_iter2_up_reg_492;
wire   [9:0] ap_phi_reg_pp0_iter0_up_reg_492;
reg   [9:0] ap_phi_reg_pp0_iter1_up_reg_492;
wire   [63:0] zext_ln881_fu_597_p1;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
wire    ap_block_pp0_stage0_grp0;
reg   [10:0] x_fu_146;
wire   [10:0] x_8_fu_587_p2;
wire    ap_loop_init;
reg   [10:0] ap_sig_allocacmp_z;
reg   [9:0] p_0_0_0116617811792_i_fu_150;
wire   [9:0] trunc_ln902_1_fu_697_p1;
reg   [9:0] p_0_0_0116517831794_i_fu_154;
wire   [9:0] tmp_3_i_fu_701_p3;
reg   [9:0] p_0_0_0116417851796_i_fu_158;
reg   [9:0] right_fu_162;
reg   [9:0] right_1_fu_166;
reg   [9:0] right_2_fu_170;
reg   [9:0] p_0_0_01179_217751804_i_fu_174;
reg   [9:0] p_0_0_01178_217771806_i_fu_178;
reg   [9:0] p_0_0_01177_217791808_i_fu_182;
reg   [9:0] p_0_0_0_0_011581705_i_fu_186;
reg   [9:0] p_0_1_0_0_011591708_i_fu_190;
reg   [9:0] p_0_2_0_0_011601711_i_fu_194;
reg    ap_block_pp0_stage0_01001_grp1;
reg    lineBuffer_ce1_local;
reg    lineBuffer_we0_local;
reg    lineBuffer_ce0_local;
reg    lineBuffer_2_ce1_local;
reg    lineBuffer_2_we0_local;
wire   [29:0] LineBufVal_4_fu_899_p4;
reg    lineBuffer_2_ce0_local;
wire   [0:0] trunc_ln881_fu_593_p1;
wire   [0:0] xor_ln1014_fu_615_p2;
wire   [0:0] xor_ln1014_2_fu_621_p2;
wire   [14:0] zext_ln1014_fu_627_p1;
wire   [0:0] icmp_ln1052_fu_637_p2;
wire   [9:0] select_ln975_2_fu_893_p3;
wire   [9:0] select_ln975_1_fu_887_p3;
wire   [10:0] zext_ln1023_fu_927_p1;
wire   [10:0] zext_ln1023_1_fu_931_p1;
wire   [10:0] zext_ln1024_fu_951_p1;
wire   [10:0] zext_ln1024_1_fu_955_p1;
wire   [10:0] sub_ln1024_fu_959_p2;
wire   [9:0] trunc_ln61_4_fu_965_p1;
wire   [0:0] tmp_11_fu_969_p3;
wire   [9:0] sub_ln61_4_fu_977_p2;
wire   [10:0] zext_ln1025_fu_991_p1;
wire   [10:0] zext_ln1025_1_fu_995_p1;
wire   [10:0] zext_ln1026_fu_1015_p1;
wire   [10:0] zext_ln1026_1_fu_1019_p1;
wire   [10:0] sub_ln1026_fu_1023_p2;
wire   [9:0] trunc_ln61_6_fu_1029_p1;
wire   [0:0] tmp_13_fu_1033_p3;
wire   [9:0] sub_ln61_6_fu_1041_p2;
wire   [10:0] zext_ln1027_fu_1055_p1;
wire   [10:0] zext_ln1027_1_fu_1059_p1;
wire   [10:0] zext_ln1028_fu_1073_p1;
wire   [10:0] zext_ln1028_1_fu_1077_p1;
wire   [9:0] DRv_fu_983_p3;
wire   [9:0] DGv_fu_1047_p3;
wire   [10:0] zext_ln1030_4_fu_1091_p1;
wire   [10:0] zext_ln1030_5_fu_1095_p1;
wire   [0:0] tmp_10_fu_1168_p3;
wire   [0:0] tmp_12_fu_1181_p3;
wire   [0:0] tmp_14_fu_1194_p3;
wire   [9:0] sub_ln61_7_fu_1201_p2;
wire   [0:0] tmp_15_fu_1213_p3;
wire   [9:0] sub_ln61_8_fu_1220_p2;
wire   [9:0] DRh_fu_1175_p3;
wire   [9:0] DGh_fu_1188_p3;
wire   [10:0] zext_ln1030_fu_1232_p1;
wire   [10:0] zext_ln1030_1_fu_1236_p1;
wire   [10:0] add_ln1030_fu_1240_p2;
wire   [9:0] DBh_fu_1206_p3;
wire   [11:0] zext_ln1030_2_fu_1246_p1;
wire   [11:0] zext_ln1030_3_fu_1250_p1;
wire   [9:0] DBv_fu_1225_p3;
wire   [11:0] zext_ln1030_6_fu_1260_p1;
wire   [11:0] zext_ln1030_7_fu_1263_p1;
wire   [11:0] add_ln1030_1_fu_1254_p2;
wire   [11:0] add_ln1030_3_fu_1267_p2;
wire  signed [11:0] sext_ln1033_fu_1279_p1;
wire  signed [11:0] sext_ln1033_1_fu_1282_p1;
wire  signed [11:0] add_ln1033_fu_1285_p2;
wire  signed [12:0] sext_ln1033_2_fu_1291_p1;
wire   [12:0] sub_ln1033_2_fu_1303_p2;
wire   [10:0] lshr_ln1033_1_cast_fu_1309_p4;
wire   [0:0] tmp_16_fu_1295_p3;
wire   [10:0] sub_ln1033_3_fu_1319_p2;
wire   [10:0] zext_ln_fu_1325_p4;
wire  signed [11:0] sext_ln1034_fu_1347_p1;
wire  signed [11:0] sext_ln1034_1_fu_1350_p1;
wire  signed [11:0] add_ln1034_fu_1353_p2;
wire  signed [12:0] sext_ln1034_2_fu_1359_p1;
wire   [12:0] sub_ln1034_2_fu_1371_p2;
wire   [10:0] lshr_ln1034_1_cast_fu_1377_p4;
wire   [0:0] tmp_17_fu_1363_p3;
wire   [10:0] sub_ln1034_3_fu_1387_p2;
wire   [10:0] zext_ln1_fu_1393_p4;
wire  signed [11:0] sext_ln1039_fu_1411_p1;
wire  signed [11:0] sext_ln1039_1_fu_1414_p1;
wire  signed [11:0] add_ln1039_fu_1417_p2;
wire  signed [12:0] sext_ln1039_2_fu_1423_p1;
wire   [12:0] sub_ln1039_2_fu_1435_p2;
wire   [10:0] lshr_ln1039_1_cast_fu_1441_p4;
wire   [0:0] tmp_18_fu_1427_p3;
wire   [10:0] sub_ln1039_3_fu_1451_p2;
wire   [10:0] zext_ln2_fu_1457_p4;
wire  signed [11:0] sext_ln1040_fu_1475_p1;
wire  signed [11:0] sext_ln1040_1_fu_1478_p1;
wire  signed [11:0] add_ln1040_fu_1481_p2;
wire  signed [12:0] sext_ln1040_2_fu_1487_p1;
wire   [12:0] sub_ln1040_2_fu_1499_p2;
wire   [10:0] lshr_ln1040_1_cast_fu_1505_p4;
wire   [0:0] tmp_19_fu_1491_p3;
wire   [10:0] sub_ln1040_3_fu_1515_p2;
wire   [10:0] zext_ln3_fu_1521_p4;
wire   [0:0] icmp_ln1030_fu_1273_p2;
wire   [10:0] select_ln1033_fu_1335_p3;
wire   [10:0] select_ln1039_fu_1467_p3;
wire   [10:0] r_0_in_i_v_v_fu_1539_p3;
wire   [11:0] zext_ln1034_1_fu_1343_p1;
wire  signed [11:0] r_0_in_i_v_v_cast_fu_1547_p1;
wire   [10:0] select_ln1034_fu_1403_p3;
wire   [10:0] select_ln1040_fu_1531_p3;
wire   [10:0] b_0_in_i_v_v_fu_1557_p3;
wire  signed [11:0] b_0_in_i_v_v_cast_fu_1565_p1;
wire  signed [13:0] r_0_in_i_cast1_fu_1595_p1;
wire   [0:0] tmp_20_fu_1607_p3;
wire   [0:0] xor_ln1046_fu_1620_p2;
wire   [0:0] icmp_ln1042_fu_1615_p2;
wire   [0:0] or_ln1042_fu_1634_p2;
wire   [9:0] select_ln1042_fu_1626_p3;
wire   [9:0] trunc_ln1046_fu_1604_p1;
wire  signed [13:0] sext_ln1048_fu_1598_p1;
wire   [0:0] tmp_22_fu_1648_p3;
wire   [0:0] xor_ln1048_fu_1661_p2;
wire   [0:0] icmp_ln1043_fu_1656_p2;
wire   [0:0] or_ln1043_fu_1675_p2;
wire   [9:0] select_ln1043_fu_1667_p3;
wire   [9:0] trunc_ln1048_fu_1601_p1;
wire   [9:0] select_ln1046_fu_1640_p3;
wire   [9:0] select_ln1048_fu_1681_p3;
wire   [9:0] phi_ln1046_fu_1689_p3;
wire   [9:0] phi_ln1048_fu_1696_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_block_pp0;
reg    ap_predicate_op70_load_state1;
reg    ap_enable_operation_70;
reg    ap_enable_state1_pp0_iter0_stage0;
reg    ap_predicate_op91_load_state2;
reg    ap_enable_operation_91;
reg    ap_enable_state2_pp0_iter1_stage0;
reg    ap_predicate_op103_store_state2;
reg    ap_enable_operation_103;
reg    ap_predicate_op72_load_state1;
reg    ap_enable_operation_72;
reg    ap_predicate_op95_load_state2;
reg    ap_enable_operation_95;
reg    ap_predicate_op136_store_state3;
reg    ap_enable_operation_136;
reg    ap_enable_state3_pp0_iter2_stage0;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_266;
reg    ap_condition_60;
reg    ap_condition_411;
reg    ap_condition_1313;
reg    ap_condition_1316;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp1_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg = 1'b0;
#0 x_fu_146 = 11'd0;
#0 p_0_0_0116617811792_i_fu_150 = 10'd0;
#0 p_0_0_0116517831794_i_fu_154 = 10'd0;
#0 p_0_0_0116417851796_i_fu_158 = 10'd0;
#0 right_fu_162 = 10'd0;
#0 right_1_fu_166 = 10'd0;
#0 right_2_fu_170 = 10'd0;
#0 p_0_0_01179_217751804_i_fu_174 = 10'd0;
#0 p_0_0_01178_217771806_i_fu_178 = 10'd0;
#0 p_0_0_01177_217791808_i_fu_182 = 10'd0;
#0 p_0_0_0_0_011581705_i_fu_186 = 10'd0;
#0 p_0_1_0_0_011591708_i_fu_190 = 10'd0;
#0 p_0_2_0_0_011601711_i_fu_194 = 10'd0;
#0 ap_done_reg = 1'b0;
end

design_1_v_demosaic_0_0_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_lineBuffer_1_RAM_AUTO_1R1W #(
    .DataWidth( 30 ),
    .AddressRange( 1921 ),
    .AddressWidth( 11 ))
lineBuffer_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(lineBuffer_2_address0),
    .ce0(lineBuffer_2_ce0_local),
    .we0(lineBuffer_2_we0_local),
    .d0(LineBufVal_4_fu_899_p4),
    .address1(lineBuffer_2_address1),
    .ce1(lineBuffer_2_ce1_local),
    .q1(lineBuffer_2_q1)
);

design_1_v_demosaic_0_0_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_lineBuffer_1_RAM_AUTO_1R1W #(
    .DataWidth( 30 ),
    .AddressRange( 1921 ),
    .AddressWidth( 11 ))
lineBuffer_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(lineBuffer_address0),
    .ce0(lineBuffer_ce0_local),
    .we0(lineBuffer_we0_local),
    .d0(imgRB_dout),
    .address1(lineBuffer_address1),
    .ce1(lineBuffer_ce1_local),
    .q1(lineBuffer_q1)
);

design_1_v_demosaic_0_0_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp1_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp1_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp1)) begin
            ap_block_pp0_stage0_subdone_grp1_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter2_stage0)) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_266)) begin
        if (((icmp_ln891_reg_1883 == 1'd0) & (icmp_ln881_reg_1879 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_down_1_reg_399 <= p_0_0_01178_217771806_i_fu_178;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_down_1_reg_399 <= ap_phi_reg_pp0_iter1_down_1_reg_399;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_266)) begin
        if (((icmp_ln891_reg_1883 == 1'd0) & (icmp_ln881_reg_1879 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_down_reg_408 <= p_0_0_01179_217751804_i_fu_174;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_down_reg_408 <= ap_phi_reg_pp0_iter1_down_reg_408;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_266)) begin
        if ((1'b1 == ap_condition_411)) begin
            ap_phi_reg_pp0_iter2_p_0_0_01177_21779_ph_i_reg_381 <= {{lineBuffer_q1[29:20]}};
        end else if ((1'b1 == ap_condition_60)) begin
            ap_phi_reg_pp0_iter2_p_0_0_01177_21779_ph_i_reg_381 <= {{imgRB_dout[29:20]}};
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_p_0_0_01177_21779_ph_i_reg_381 <= ap_phi_reg_pp0_iter1_p_0_0_01177_21779_ph_i_reg_381;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_266)) begin
        if (((icmp_ln891_reg_1883 == 1'd0) & (icmp_ln881_reg_1879 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_pix_7_reg_454 <= right_1_fu_166;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_pix_7_reg_454 <= ap_phi_reg_pp0_iter1_pix_7_reg_454;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_266)) begin
        if (((icmp_ln891_reg_1883 == 1'd0) & (icmp_ln881_reg_1879 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_pix_8_reg_444 <= right_2_fu_170;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_pix_8_reg_444 <= ap_phi_reg_pp0_iter1_pix_8_reg_444;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_266)) begin
        if (((icmp_ln891_reg_1883 == 1'd0) & (icmp_ln881_reg_1879 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_pix_reg_464 <= right_fu_162;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_pix_reg_464 <= ap_phi_reg_pp0_iter1_pix_reg_464;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_266)) begin
        if (((icmp_ln891_reg_1883 == 1'd0) & (icmp_ln881_reg_1879 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_up_1_reg_483 <= p_0_0_0116517831794_i_fu_154;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_up_1_reg_483 <= ap_phi_reg_pp0_iter1_up_1_reg_483;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_266)) begin
        if (((icmp_ln891_reg_1883 == 1'd0) & (icmp_ln881_reg_1879 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_up_reg_492 <= p_0_0_0116617811792_i_fu_150;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_up_reg_492 <= ap_phi_reg_pp0_iter1_up_reg_492;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_0_0_0116417851796_i_fu_158 <= p_0_0_0116417851797_lcssa1833_i;
        end else if ((1'b1 == ap_condition_1313)) begin
            p_0_0_0116417851796_i_fu_158 <= tmp_4_i_reg_1991;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            p_0_0_0116517831794_i_fu_154 <= p_0_0_0116517831795_lcssa1831_i;
        end else if ((1'b1 == ap_condition_1316)) begin
            p_0_0_0116517831794_i_fu_154 <= {{lineBuffer_2_q1[19:10]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            p_0_0_0116617811792_i_fu_150 <= p_0_0_0116617811793_lcssa1829_i;
        end else if ((1'b1 == ap_condition_1316)) begin
            p_0_0_0116617811792_i_fu_150 <= trunc_ln902_1_fu_697_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_0_0_01177_217791808_i_fu_182 <= p_0_0_01177_217791809_lcssa1845_i;
        end else if ((1'b1 == ap_condition_1313)) begin
            p_0_0_01177_217791808_i_fu_182 <= ap_phi_reg_pp0_iter2_p_0_0_01177_21779_ph_i_reg_381;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            p_0_0_01178_217771806_i_fu_178 <= p_0_0_01178_217771807_lcssa1843_i;
        end else if ((1'b1 == ap_condition_1316)) begin
            p_0_0_01178_217771806_i_fu_178 <= ap_phi_mux_p_0_0_01178_21777_ph_i_phi_fu_365_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_266)) begin
        if ((1'b1 == ap_condition_411)) begin
            p_0_0_01178_21777_ph_i_reg_362 <= {{lineBuffer_q1[19:10]}};
        end else if ((1'b1 == ap_condition_60)) begin
            p_0_0_01178_21777_ph_i_reg_362 <= {{imgRB_dout[19:10]}};
        end else if (~(icmp_ln881_reg_1879 == 1'd1)) begin
            p_0_0_01178_21777_ph_i_reg_362 <= ap_phi_reg_pp0_iter1_p_0_0_01178_21777_ph_i_reg_362;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            p_0_0_01179_217751804_i_fu_174 <= p_0_0_01179_217751805_lcssa1841_i;
        end else if ((1'b1 == ap_condition_1316)) begin
            p_0_0_01179_217751804_i_fu_174 <= ap_phi_mux_p_0_0_01179_21775_ph_i_phi_fu_375_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_0_0_0_0_011581705_i_fu_186 <= p_0_0_0_0_011581703_lcssa1747_i;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln881_reg_1879_pp0_iter1_reg == 1'd0))) begin
            p_0_0_0_0_011581705_i_fu_186 <= ap_phi_mux_pix_phi_fu_467_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_0_1_0_0_011591708_i_fu_190 <= p_0_1_0_0_011591706_lcssa1749_i;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln881_reg_1879_pp0_iter1_reg == 1'd0))) begin
            p_0_1_0_0_011591708_i_fu_190 <= ap_phi_mux_pix_7_phi_fu_457_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_0_2_0_0_011601711_i_fu_194 <= p_0_2_0_0_011601709_lcssa1751_i;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln881_reg_1879_pp0_iter1_reg == 1'd0))) begin
            p_0_2_0_0_011601711_i_fu_194 <= ap_phi_mux_pix_8_phi_fu_447_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if (((icmp_ln891_reg_1883_pp0_iter1_reg == 1'd1) & (icmp_ln881_reg_1879_pp0_iter1_reg == 1'd0))) begin
            pix_7_reg_454 <= select_ln957_1_fu_839_p3;
        end else if ((1'b1 == 1'b1)) begin
            pix_7_reg_454 <= ap_phi_reg_pp0_iter2_pix_7_reg_454;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if (((icmp_ln891_reg_1883_pp0_iter1_reg == 1'd1) & (icmp_ln881_reg_1879_pp0_iter1_reg == 1'd0))) begin
            pix_8_reg_444 <= select_ln957_2_fu_845_p3;
        end else if ((1'b1 == 1'b1)) begin
            pix_8_reg_444 <= ap_phi_reg_pp0_iter2_pix_8_reg_444;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if (((icmp_ln891_reg_1883_pp0_iter1_reg == 1'd1) & (icmp_ln881_reg_1879_pp0_iter1_reg == 1'd0))) begin
            pix_reg_464 <= select_ln957_fu_833_p3;
        end else if ((1'b1 == 1'b1)) begin
            pix_reg_464 <= ap_phi_reg_pp0_iter2_pix_reg_464;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            right_1_fu_166 <= p_0_1_0_0_011531800_lcssa1837_i;
        end else if ((1'b1 == ap_condition_1316)) begin
            right_1_fu_166 <= {{lineBuffer_q1[19:10]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            right_2_fu_170 <= p_0_2_0_0_011541802_lcssa1839_i;
        end else if ((1'b1 == ap_condition_1316)) begin
            right_2_fu_170 <= {{lineBuffer_q1[29:20]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            right_fu_162 <= p_0_0_0_0_011521798_lcssa1835_i;
        end else if ((1'b1 == ap_condition_1316)) begin
            right_fu_162 <= trunc_ln902_fu_675_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln881_fu_581_p2 == 1'd0) & (ap_start_int == 1'b1))) begin
            x_fu_146 <= x_8_fu_587_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            x_fu_146 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln1030_2_reg_2104 <= add_ln1030_2_fu_1099_p2;
        and_ln1052_reg_1921_pp0_iter2_reg <= and_ln1052_reg_1921_pp0_iter1_reg;
        and_ln1052_reg_1921_pp0_iter3_reg <= and_ln1052_reg_1921_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        icmp_ln1014_reg_1915_pp0_iter2_reg <= icmp_ln1014_reg_1915_pp0_iter1_reg;
        icmp_ln1014_reg_1915_pp0_iter3_reg <= icmp_ln1014_reg_1915_pp0_iter2_reg;
        icmp_ln881_reg_1879_pp0_iter2_reg <= icmp_ln881_reg_1879_pp0_iter1_reg;
        p_0_0_0116517831794_i_load_reg_1931_pp0_iter2_reg <= p_0_0_0116517831794_i_load_reg_1931;
        p_0_0_0116617811792_i_load_reg_1925_pp0_iter2_reg <= p_0_0_0116617811792_i_load_reg_1925;
        p_0_0_01178_217771806_i_load_reg_1964_pp0_iter2_reg <= p_0_0_01178_217771806_i_load_reg_1964;
        p_0_0_01179_217751804_i_load_reg_1958_pp0_iter2_reg <= p_0_0_01179_217751804_i_load_reg_1958;
        pix_7_reg_454_pp0_iter3_reg <= pix_7_reg_454;
        pix_8_reg_444_pp0_iter3_reg <= pix_8_reg_444;
        pix_reg_464_pp0_iter3_reg <= pix_reg_464;
        right_3_reg_1937_pp0_iter2_reg <= right_3_reg_1937;
        right_4_reg_1944_pp0_iter2_reg <= right_4_reg_1944;
        right_5_reg_1951_pp0_iter2_reg <= right_5_reg_1951;
        sub_ln1023_reg_2052 <= sub_ln1023_fu_935_p2;
        sub_ln1025_reg_2067 <= sub_ln1025_fu_999_p2;
        sub_ln1027_reg_2082 <= sub_ln1027_fu_1063_p2;
        sub_ln1028_reg_2093 <= sub_ln1028_fu_1081_p2;
        sub_ln1033_1_reg_2114 <= sub_ln1033_1_fu_1111_p2;
        sub_ln1033_reg_2109 <= sub_ln1033_fu_1105_p2;
        sub_ln1034_1_reg_2124 <= sub_ln1034_1_fu_1123_p2;
        sub_ln1034_reg_2119 <= sub_ln1034_fu_1117_p2;
        sub_ln1039_1_reg_2134 <= sub_ln1039_1_fu_1135_p2;
        sub_ln1039_reg_2129 <= sub_ln1039_fu_1129_p2;
        sub_ln1040_1_reg_2144 <= sub_ln1040_1_fu_1147_p2;
        sub_ln1040_reg_2139 <= sub_ln1040_fu_1141_p2;
        sub_ln61_5_reg_2077 <= sub_ln61_5_fu_1009_p2;
        sub_ln61_reg_2062 <= sub_ln61_fu_945_p2;
        trunc_ln61_5_reg_2072 <= trunc_ln61_5_fu_1005_p1;
        trunc_ln61_7_reg_2087 <= trunc_ln61_7_fu_1069_p1;
        trunc_ln61_8_reg_2098 <= trunc_ln61_8_fu_1087_p1;
        trunc_ln61_reg_2057 <= trunc_ln61_fu_941_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        and_ln1052_reg_1921 <= and_ln1052_fu_643_p2;
        and_ln1052_reg_1921_pp0_iter1_reg <= and_ln1052_reg_1921;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln1014_reg_1915 <= icmp_ln1014_fu_631_p2;
        icmp_ln1014_reg_1915_pp0_iter1_reg <= icmp_ln1014_reg_1915;
        icmp_ln881_reg_1879 <= icmp_ln881_fu_581_p2;
        icmp_ln881_reg_1879_pp0_iter1_reg <= icmp_ln881_reg_1879;
        icmp_ln891_reg_1883 <= icmp_ln891_fu_603_p2;
        icmp_ln891_reg_1883_pp0_iter1_reg <= icmp_ln891_reg_1883;
        icmp_ln911_reg_1868 <= icmp_ln911_fu_501_p2;
        icmp_ln957_reg_1899 <= icmp_ln957_fu_609_p2;
        icmp_ln957_reg_1899_pp0_iter1_reg <= icmp_ln957_reg_1899;
        icmp_ln975_reg_1872 <= icmp_ln975_fu_507_p2;
        lineBuffer_2_addr_reg_1893 <= zext_ln881_fu_597_p1;
        lineBuffer_2_addr_reg_1893_pp0_iter1_reg <= lineBuffer_2_addr_reg_1893;
        lineBuffer_addr_reg_1887 <= zext_ln881_fu_597_p1;
        select_ln957_10_reg_2012 <= select_ln957_10_fu_757_p3;
        select_ln957_11_reg_2017 <= select_ln957_11_fu_764_p3;
        select_ln957_7_reg_2002 <= select_ln957_7_fu_743_p3;
        select_ln957_8_reg_2007 <= select_ln957_8_fu_750_p3;
        select_ln975_reg_2022 <= select_ln975_fu_771_p3;
        tmp_1_i_reg_1983 <= {{lineBuffer_q1[29:20]}};
        tmp_4_i_reg_1991 <= {{lineBuffer_2_q1[29:20]}};
        tmp_i_reg_1976 <= {{lineBuffer_q1[19:10]}};
        trunc_ln902_reg_1970 <= trunc_ln902_fu_675_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_down_1_reg_399 <= ap_phi_reg_pp0_iter0_down_1_reg_399;
        ap_phi_reg_pp0_iter1_down_reg_408 <= ap_phi_reg_pp0_iter0_down_reg_408;
        ap_phi_reg_pp0_iter1_p_0_0_01177_21779_ph_i_reg_381 <= ap_phi_reg_pp0_iter0_p_0_0_01177_21779_ph_i_reg_381;
        ap_phi_reg_pp0_iter1_pix_7_reg_454 <= ap_phi_reg_pp0_iter0_pix_7_reg_454;
        ap_phi_reg_pp0_iter1_pix_8_reg_444 <= ap_phi_reg_pp0_iter0_pix_8_reg_444;
        ap_phi_reg_pp0_iter1_pix_reg_464 <= ap_phi_reg_pp0_iter0_pix_reg_464;
        ap_phi_reg_pp0_iter1_up_1_reg_483 <= ap_phi_reg_pp0_iter0_up_1_reg_483;
        ap_phi_reg_pp0_iter1_up_reg_492 <= ap_phi_reg_pp0_iter0_up_reg_492;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        b_0_in_i_reg_2155 <= b_0_in_i_fu_1569_p2;
        r_0_in_i_reg_2149 <= r_0_in_i_fu_1551_p2;
        tmp_21_reg_2161 <= {{r_0_in_i_fu_1551_p2[11:10]}};
        tmp_23_reg_2166 <= {{b_0_in_i_fu_1569_p2[11:10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_0_0_0116417851796_i_load_reg_2027 <= p_0_0_0116417851796_i_fu_158;
        p_0_0_01177_217791808_i_load_reg_2032 <= p_0_0_01177_217791808_i_fu_182;
        p_0_0_0_0_011581705_i_load_reg_2037 <= p_0_0_0_0_011581705_i_fu_186;
        p_0_1_0_0_011591708_i_load_reg_2042 <= p_0_1_0_0_011591708_i_fu_190;
        p_0_2_0_0_011601711_i_load_reg_2047 <= p_0_2_0_0_011601711_i_fu_194;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_0_0116517831794_i_load_reg_1931 <= p_0_0_0116517831794_i_fu_154;
        p_0_0_0116617811792_i_load_reg_1925 <= p_0_0_0116617811792_i_fu_150;
        p_0_0_01178_217771806_i_load_reg_1964 <= p_0_0_01178_217771806_i_fu_178;
        p_0_0_01179_217751804_i_load_reg_1958 <= p_0_0_01179_217751804_i_fu_174;
        right_3_reg_1937 <= right_fu_162;
        right_4_reg_1944 <= right_1_fu_166;
        right_5_reg_1951 <= right_2_fu_170;
    end
end

always @ (*) begin
    if (((icmp_ln881_fu_581_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln881_reg_1879_pp0_iter1_reg == 1'd1))) begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln891_reg_1883_pp0_iter1_reg == 1'd1) & (icmp_ln881_reg_1879_pp0_iter1_reg == 1'd0))) begin
        ap_phi_mux_down_1_phi_fu_402_p4 = select_ln957_10_reg_2012;
    end else begin
        ap_phi_mux_down_1_phi_fu_402_p4 = ap_phi_reg_pp0_iter2_down_1_reg_399;
    end
end

always @ (*) begin
    if ((icmp_ln881_reg_1879_pp0_iter1_reg == 1'd0)) begin
        if ((icmp_ln891_reg_1883_pp0_iter1_reg == 1'd0)) begin
            ap_phi_mux_down_2_phi_fu_393_p4 = p_0_0_01177_217791808_i_fu_182;
        end else if ((icmp_ln891_reg_1883_pp0_iter1_reg == 1'd1)) begin
            ap_phi_mux_down_2_phi_fu_393_p4 = select_ln957_9_fu_879_p3;
        end else begin
            ap_phi_mux_down_2_phi_fu_393_p4 = ap_phi_reg_pp0_iter2_down_2_reg_390;
        end
    end else begin
        ap_phi_mux_down_2_phi_fu_393_p4 = ap_phi_reg_pp0_iter2_down_2_reg_390;
    end
end

always @ (*) begin
    if (((icmp_ln891_reg_1883_pp0_iter1_reg == 1'd1) & (icmp_ln881_reg_1879_pp0_iter1_reg == 1'd0))) begin
        ap_phi_mux_down_phi_fu_411_p4 = select_ln957_11_reg_2017;
    end else begin
        ap_phi_mux_down_phi_fu_411_p4 = ap_phi_reg_pp0_iter2_down_reg_408;
    end
end

always @ (*) begin
    if ((icmp_ln881_reg_1879_pp0_iter1_reg == 1'd0)) begin
        if ((icmp_ln891_reg_1883_pp0_iter1_reg == 1'd0)) begin
            ap_phi_mux_left_1_phi_fu_429_p4 = p_0_1_0_0_011591708_i_fu_190;
        end else if ((icmp_ln891_reg_1883_pp0_iter1_reg == 1'd1)) begin
            ap_phi_mux_left_1_phi_fu_429_p4 = select_ln957_4_fu_858_p3;
        end else begin
            ap_phi_mux_left_1_phi_fu_429_p4 = ap_phi_reg_pp0_iter2_left_1_reg_426;
        end
    end else begin
        ap_phi_mux_left_1_phi_fu_429_p4 = ap_phi_reg_pp0_iter2_left_1_reg_426;
    end
end

always @ (*) begin
    if ((icmp_ln881_reg_1879_pp0_iter1_reg == 1'd0)) begin
        if ((icmp_ln891_reg_1883_pp0_iter1_reg == 1'd0)) begin
            ap_phi_mux_left_2_phi_fu_420_p4 = p_0_2_0_0_011601711_i_fu_194;
        end else if ((icmp_ln891_reg_1883_pp0_iter1_reg == 1'd1)) begin
            ap_phi_mux_left_2_phi_fu_420_p4 = select_ln957_5_fu_865_p3;
        end else begin
            ap_phi_mux_left_2_phi_fu_420_p4 = ap_phi_reg_pp0_iter2_left_2_reg_417;
        end
    end else begin
        ap_phi_mux_left_2_phi_fu_420_p4 = ap_phi_reg_pp0_iter2_left_2_reg_417;
    end
end

always @ (*) begin
    if ((icmp_ln881_reg_1879_pp0_iter1_reg == 1'd0)) begin
        if ((icmp_ln891_reg_1883_pp0_iter1_reg == 1'd0)) begin
            ap_phi_mux_left_phi_fu_438_p4 = p_0_0_0_0_011581705_i_fu_186;
        end else if ((icmp_ln891_reg_1883_pp0_iter1_reg == 1'd1)) begin
            ap_phi_mux_left_phi_fu_438_p4 = select_ln957_3_fu_851_p3;
        end else begin
            ap_phi_mux_left_phi_fu_438_p4 = ap_phi_reg_pp0_iter2_left_reg_435;
        end
    end else begin
        ap_phi_mux_left_phi_fu_438_p4 = ap_phi_reg_pp0_iter2_left_reg_435;
    end
end

always @ (*) begin
    if (((icmp_ln891_reg_1883 == 1'd1) & (icmp_ln881_reg_1879 == 1'd0))) begin
        if ((icmp_ln911_reg_1868 == 1'd0)) begin
            ap_phi_mux_p_0_0_01178_21777_ph_i_phi_fu_365_p4 = {{lineBuffer_q1[19:10]}};
        end else if ((icmp_ln911_reg_1868 == 1'd1)) begin
            ap_phi_mux_p_0_0_01178_21777_ph_i_phi_fu_365_p4 = {{imgRB_dout[19:10]}};
        end else begin
            ap_phi_mux_p_0_0_01178_21777_ph_i_phi_fu_365_p4 = ap_phi_reg_pp0_iter1_p_0_0_01178_21777_ph_i_reg_362;
        end
    end else begin
        ap_phi_mux_p_0_0_01178_21777_ph_i_phi_fu_365_p4 = ap_phi_reg_pp0_iter1_p_0_0_01178_21777_ph_i_reg_362;
    end
end

always @ (*) begin
    if (((icmp_ln891_reg_1883 == 1'd1) & (icmp_ln881_reg_1879 == 1'd0))) begin
        if ((icmp_ln911_reg_1868 == 1'd0)) begin
            ap_phi_mux_p_0_0_01179_21775_ph_i_phi_fu_375_p4 = trunc_ln902_fu_675_p1;
        end else if ((icmp_ln911_reg_1868 == 1'd1)) begin
            ap_phi_mux_p_0_0_01179_21775_ph_i_phi_fu_375_p4 = trunc_ln913_fu_717_p1;
        end else begin
            ap_phi_mux_p_0_0_01179_21775_ph_i_phi_fu_375_p4 = ap_phi_reg_pp0_iter1_p_0_0_01179_21775_ph_i_reg_372;
        end
    end else begin
        ap_phi_mux_p_0_0_01179_21775_ph_i_phi_fu_375_p4 = ap_phi_reg_pp0_iter1_p_0_0_01179_21775_ph_i_reg_372;
    end
end

always @ (*) begin
    if (((icmp_ln891_reg_1883_pp0_iter1_reg == 1'd1) & (icmp_ln881_reg_1879_pp0_iter1_reg == 1'd0))) begin
        ap_phi_mux_pix_7_phi_fu_457_p4 = select_ln957_1_fu_839_p3;
    end else begin
        ap_phi_mux_pix_7_phi_fu_457_p4 = ap_phi_reg_pp0_iter2_pix_7_reg_454;
    end
end

always @ (*) begin
    if (((icmp_ln891_reg_1883_pp0_iter1_reg == 1'd1) & (icmp_ln881_reg_1879_pp0_iter1_reg == 1'd0))) begin
        ap_phi_mux_pix_8_phi_fu_447_p4 = select_ln957_2_fu_845_p3;
    end else begin
        ap_phi_mux_pix_8_phi_fu_447_p4 = ap_phi_reg_pp0_iter2_pix_8_reg_444;
    end
end

always @ (*) begin
    if (((icmp_ln891_reg_1883_pp0_iter1_reg == 1'd1) & (icmp_ln881_reg_1879_pp0_iter1_reg == 1'd0))) begin
        ap_phi_mux_pix_phi_fu_467_p4 = select_ln957_fu_833_p3;
    end else begin
        ap_phi_mux_pix_phi_fu_467_p4 = ap_phi_reg_pp0_iter2_pix_reg_464;
    end
end

always @ (*) begin
    if (((icmp_ln891_reg_1883_pp0_iter1_reg == 1'd1) & (icmp_ln881_reg_1879_pp0_iter1_reg == 1'd0))) begin
        ap_phi_mux_up_1_phi_fu_486_p4 = select_ln957_7_reg_2002;
    end else begin
        ap_phi_mux_up_1_phi_fu_486_p4 = ap_phi_reg_pp0_iter2_up_1_reg_483;
    end
end

always @ (*) begin
    if ((icmp_ln881_reg_1879_pp0_iter1_reg == 1'd0)) begin
        if ((icmp_ln891_reg_1883_pp0_iter1_reg == 1'd0)) begin
            ap_phi_mux_up_2_phi_fu_477_p4 = p_0_0_0116417851796_i_fu_158;
        end else if ((icmp_ln891_reg_1883_pp0_iter1_reg == 1'd1)) begin
            ap_phi_mux_up_2_phi_fu_477_p4 = select_ln957_6_fu_872_p3;
        end else begin
            ap_phi_mux_up_2_phi_fu_477_p4 = ap_phi_reg_pp0_iter2_up_2_reg_474;
        end
    end else begin
        ap_phi_mux_up_2_phi_fu_477_p4 = ap_phi_reg_pp0_iter2_up_2_reg_474;
    end
end

always @ (*) begin
    if (((icmp_ln891_reg_1883_pp0_iter1_reg == 1'd1) & (icmp_ln881_reg_1879_pp0_iter1_reg == 1'd0))) begin
        ap_phi_mux_up_phi_fu_495_p4 = select_ln957_8_reg_2007;
    end else begin
        ap_phi_mux_up_phi_fu_495_p4 = ap_phi_reg_pp0_iter2_up_reg_492;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_z = 11'd0;
    end else begin
        ap_sig_allocacmp_z = x_fu_146;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op99_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        imgRB_blk_n = imgRB_empty_n;
    end else begin
        imgRB_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op99_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        imgRB_read = 1'b1;
    end else begin
        imgRB_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage0_grp1) & (1'd1 == and_ln1052_reg_1921_pp0_iter3_reg) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        imgRgb_blk_n = imgRgb_full_n;
    end else begin
        imgRgb_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'd1 == and_ln1052_reg_1921_pp0_iter3_reg) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        imgRgb_write = 1'b1;
    end else begin
        imgRgb_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        lineBuffer_2_ce0_local = 1'b1;
    end else begin
        lineBuffer_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        lineBuffer_2_ce1_local = 1'b1;
    end else begin
        lineBuffer_2_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln891_reg_1883_pp0_iter1_reg == 1'd1) & (icmp_ln881_reg_1879_pp0_iter1_reg == 1'd0))) begin
        lineBuffer_2_we0_local = 1'b1;
    end else begin
        lineBuffer_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        lineBuffer_ce0_local = 1'b1;
    end else begin
        lineBuffer_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        lineBuffer_ce1_local = 1'b1;
    end else begin
        lineBuffer_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln911_reg_1868 == 1'd1) & (icmp_ln891_reg_1883 == 1'd1) & (icmp_ln881_reg_1879 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        lineBuffer_we0_local = 1'b1;
    end else begin
        lineBuffer_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (icmp_ln881_reg_1879_pp0_iter2_reg == 1'd1))) begin
        p_0_0_0116417851796_i_out_ap_vld = 1'b1;
    end else begin
        p_0_0_0116417851796_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (icmp_ln881_reg_1879_pp0_iter2_reg == 1'd1))) begin
        p_0_0_0116517831794_i_out_ap_vld = 1'b1;
    end else begin
        p_0_0_0116517831794_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (icmp_ln881_reg_1879_pp0_iter2_reg == 1'd1))) begin
        p_0_0_0116617811792_i_out_ap_vld = 1'b1;
    end else begin
        p_0_0_0116617811792_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (icmp_ln881_reg_1879_pp0_iter2_reg == 1'd1))) begin
        p_0_0_01177_217791808_i_out_ap_vld = 1'b1;
    end else begin
        p_0_0_01177_217791808_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (icmp_ln881_reg_1879_pp0_iter2_reg == 1'd1))) begin
        p_0_0_01178_217771806_i_out_ap_vld = 1'b1;
    end else begin
        p_0_0_01178_217771806_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (icmp_ln881_reg_1879_pp0_iter2_reg == 1'd1))) begin
        p_0_0_01179_217751804_i_out_ap_vld = 1'b1;
    end else begin
        p_0_0_01179_217751804_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (icmp_ln881_reg_1879_pp0_iter2_reg == 1'd1))) begin
        p_0_0_0_0_011581705_i_out_ap_vld = 1'b1;
    end else begin
        p_0_0_0_0_011581705_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (icmp_ln881_reg_1879_pp0_iter2_reg == 1'd1))) begin
        p_0_1_0_0_011591708_i_out_ap_vld = 1'b1;
    end else begin
        p_0_1_0_0_011591708_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (icmp_ln881_reg_1879_pp0_iter2_reg == 1'd1))) begin
        p_0_2_0_0_011601711_i_out_ap_vld = 1'b1;
    end else begin
        p_0_2_0_0_011601711_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (icmp_ln881_reg_1879_pp0_iter2_reg == 1'd1))) begin
        right_1_out_ap_vld = 1'b1;
    end else begin
        right_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (icmp_ln881_reg_1879_pp0_iter2_reg == 1'd1))) begin
        right_2_out_ap_vld = 1'b1;
    end else begin
        right_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (icmp_ln881_reg_1879_pp0_iter2_reg == 1'd1))) begin
        right_out_ap_vld = 1'b1;
    end else begin
        right_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign DBh_fu_1206_p3 = ((tmp_14_fu_1194_p3[0:0] == 1'b1) ? sub_ln61_7_fu_1201_p2 : trunc_ln61_7_reg_2087);

assign DBv_fu_1225_p3 = ((tmp_15_fu_1213_p3[0:0] == 1'b1) ? sub_ln61_8_fu_1220_p2 : trunc_ln61_8_reg_2098);

assign DGh_fu_1188_p3 = ((tmp_12_fu_1181_p3[0:0] == 1'b1) ? sub_ln61_5_reg_2077 : trunc_ln61_5_reg_2072);

assign DGv_fu_1047_p3 = ((tmp_13_fu_1033_p3[0:0] == 1'b1) ? sub_ln61_6_fu_1041_p2 : trunc_ln61_6_fu_1029_p1);

assign DRh_fu_1175_p3 = ((tmp_10_fu_1168_p3[0:0] == 1'b1) ? sub_ln61_reg_2062 : trunc_ln61_reg_2057);

assign DRv_fu_983_p3 = ((tmp_11_fu_969_p3[0:0] == 1'b1) ? sub_ln61_4_fu_977_p2 : trunc_ln61_4_fu_965_p1);

assign LineBufVal_4_fu_899_p4 = {{{select_ln975_2_fu_893_p3}, {select_ln975_1_fu_887_p3}}, {select_ln975_reg_2022}};

assign add_ln1030_1_fu_1254_p2 = (zext_ln1030_2_fu_1246_p1 + zext_ln1030_3_fu_1250_p1);

assign add_ln1030_2_fu_1099_p2 = (zext_ln1030_4_fu_1091_p1 + zext_ln1030_5_fu_1095_p1);

assign add_ln1030_3_fu_1267_p2 = (zext_ln1030_6_fu_1260_p1 + zext_ln1030_7_fu_1263_p1);

assign add_ln1030_fu_1240_p2 = (zext_ln1030_fu_1232_p1 + zext_ln1030_1_fu_1236_p1);

assign add_ln1033_fu_1285_p2 = ($signed(sext_ln1033_fu_1279_p1) + $signed(sext_ln1033_1_fu_1282_p1));

assign add_ln1034_fu_1353_p2 = ($signed(sext_ln1034_fu_1347_p1) + $signed(sext_ln1034_1_fu_1350_p1));

assign add_ln1039_fu_1417_p2 = ($signed(sext_ln1039_fu_1411_p1) + $signed(sext_ln1039_1_fu_1414_p1));

assign add_ln1040_fu_1481_p2 = ($signed(sext_ln1040_fu_1475_p1) + $signed(sext_ln1040_1_fu_1478_p1));

assign and_ln1052_fu_643_p2 = (icmp_ln975_fu_507_p2 & icmp_ln1052_fu_637_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_pp0 = ((ap_ST_fsm_pp0_stage0 == ap_CS_fsm) & (1'b1 == ap_block_pp0_stage0_subdone));
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter4_grp1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter4_grp1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter4_grp1));
end

assign ap_block_pp0_stage0_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter4_grp1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp1 = ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter4_grp1));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((ap_predicate_op99_read_state2 == 1'b1) & (imgRB_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state5_pp0_stage0_iter4_grp1 = ((1'd1 == and_ln1052_reg_1921_pp0_iter3_reg) & (imgRgb_full_n == 1'b0));
end

always @ (*) begin
    ap_condition_1313 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln891_reg_1883_pp0_iter1_reg == 1'd1) & (icmp_ln881_reg_1879_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_condition_1316 = ((icmp_ln891_reg_1883 == 1'd1) & (icmp_ln881_reg_1879 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_266 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_411 = ((icmp_ln911_reg_1868 == 1'd0) & (icmp_ln891_reg_1883 == 1'd1) & (icmp_ln881_reg_1879 == 1'd0));
end

always @ (*) begin
    ap_condition_60 = ((icmp_ln911_reg_1868 == 1'd1) & (icmp_ln891_reg_1883 == 1'd1) & (icmp_ln881_reg_1879 == 1'd0));
end

assign ap_done = ap_done_sig;

always @ (*) begin
    ap_enable_operation_103 = (ap_predicate_op103_store_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_136 = (ap_predicate_op136_store_state3 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_70 = (ap_predicate_op70_load_state1 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_72 = (ap_predicate_op72_load_state1 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_91 = (ap_predicate_op91_load_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_95 = (ap_predicate_op95_load_state2 == 1'b1);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

always @ (*) begin
    ap_enable_state1_pp0_iter0_stage0 = ((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_enable_state2_pp0_iter1_stage0 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_enable_state3_pp0_iter2_stage0 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_down_1_reg_399 = 'bx;

assign ap_phi_reg_pp0_iter0_down_reg_408 = 'bx;

assign ap_phi_reg_pp0_iter0_p_0_0_01177_21779_ph_i_reg_381 = 'bx;

assign ap_phi_reg_pp0_iter0_pix_7_reg_454 = 'bx;

assign ap_phi_reg_pp0_iter0_pix_8_reg_444 = 'bx;

assign ap_phi_reg_pp0_iter0_pix_reg_464 = 'bx;

assign ap_phi_reg_pp0_iter0_up_1_reg_483 = 'bx;

assign ap_phi_reg_pp0_iter0_up_reg_492 = 'bx;

assign ap_phi_reg_pp0_iter1_p_0_0_01178_21777_ph_i_reg_362 = 'bx;

assign ap_phi_reg_pp0_iter1_p_0_0_01179_21775_ph_i_reg_372 = 'bx;

assign ap_phi_reg_pp0_iter2_down_2_reg_390 = 'bx;

assign ap_phi_reg_pp0_iter2_left_1_reg_426 = 'bx;

assign ap_phi_reg_pp0_iter2_left_2_reg_417 = 'bx;

assign ap_phi_reg_pp0_iter2_left_reg_435 = 'bx;

assign ap_phi_reg_pp0_iter2_up_2_reg_474 = 'bx;

always @ (*) begin
    ap_predicate_op103_store_state2 = ((icmp_ln911_reg_1868 == 1'd1) & (icmp_ln891_reg_1883 == 1'd1) & (icmp_ln881_reg_1879 == 1'd0));
end

always @ (*) begin
    ap_predicate_op136_store_state3 = ((icmp_ln891_reg_1883_pp0_iter1_reg == 1'd1) & (icmp_ln881_reg_1879_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op70_load_state1 = ((icmp_ln881_fu_581_p2 == 1'd0) & (icmp_ln891_fu_603_p2 == 1'd1));
end

always @ (*) begin
    ap_predicate_op72_load_state1 = ((icmp_ln881_fu_581_p2 == 1'd0) & (icmp_ln891_fu_603_p2 == 1'd1));
end

always @ (*) begin
    ap_predicate_op91_load_state2 = ((icmp_ln891_reg_1883 == 1'd1) & (icmp_ln881_reg_1879 == 1'd0));
end

always @ (*) begin
    ap_predicate_op95_load_state2 = ((icmp_ln891_reg_1883 == 1'd1) & (icmp_ln881_reg_1879 == 1'd0));
end

always @ (*) begin
    ap_predicate_op99_read_state2 = ((icmp_ln911_reg_1868 == 1'd1) & (icmp_ln891_reg_1883 == 1'd1) & (icmp_ln881_reg_1879 == 1'd0));
end

assign ap_ready = ap_ready_sig;

assign b_0_in_i_fu_1569_p2 = ($signed(zext_ln1034_1_fu_1343_p1) - $signed(b_0_in_i_v_v_cast_fu_1565_p1));

assign b_0_in_i_v_v_cast_fu_1565_p1 = $signed(b_0_in_i_v_v_fu_1557_p3);

assign b_0_in_i_v_v_fu_1557_p3 = ((icmp_ln1030_fu_1273_p2[0:0] == 1'b1) ? select_ln1034_fu_1403_p3 : select_ln1040_fu_1531_p3);

assign icmp_ln1014_fu_631_p2 = ((xor_ln1014_1 == zext_ln1014_fu_627_p1) ? 1'b1 : 1'b0);

assign icmp_ln1030_fu_1273_p2 = ((add_ln1030_1_fu_1254_p2 < add_ln1030_3_fu_1267_p2) ? 1'b1 : 1'b0);

assign icmp_ln1042_fu_1615_p2 = ((tmp_21_reg_2161 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln1043_fu_1656_p2 = ((tmp_23_reg_2166 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln1052_fu_637_p2 = ((ap_sig_allocacmp_z != 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln881_fu_581_p2 = ((ap_sig_allocacmp_z == loopWidth) ? 1'b1 : 1'b0);

assign icmp_ln891_fu_603_p2 = ((ap_sig_allocacmp_z < width_val8_load) ? 1'b1 : 1'b0);

assign icmp_ln911_fu_501_p2 = ((y < height_val4_load) ? 1'b1 : 1'b0);

assign icmp_ln957_fu_609_p2 = ((ap_sig_allocacmp_z == 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln975_fu_507_p2 = ((y != 11'd0) ? 1'b1 : 1'b0);

assign imgRgb_din = {{{phi_ln1046_fu_1689_p3}, {phi_ln1048_fu_1696_p3}}, {pix_7_reg_454_pp0_iter3_reg}};

assign lineBuffer_2_address0 = lineBuffer_2_addr_reg_1893_pp0_iter1_reg;

assign lineBuffer_2_address1 = zext_ln881_fu_597_p1;

assign lineBuffer_address0 = lineBuffer_addr_reg_1887;

assign lineBuffer_address1 = zext_ln881_fu_597_p1;

assign lshr_ln1033_1_cast_fu_1309_p4 = {{sub_ln1033_2_fu_1303_p2[11:1]}};

assign lshr_ln1034_1_cast_fu_1377_p4 = {{sub_ln1034_2_fu_1371_p2[11:1]}};

assign lshr_ln1039_1_cast_fu_1441_p4 = {{sub_ln1039_2_fu_1435_p2[11:1]}};

assign lshr_ln1040_1_cast_fu_1505_p4 = {{sub_ln1040_2_fu_1499_p2[11:1]}};

assign or_ln1042_fu_1634_p2 = (tmp_20_fu_1607_p3 | icmp_ln1042_fu_1615_p2);

assign or_ln1043_fu_1675_p2 = (tmp_22_fu_1648_p3 | icmp_ln1043_fu_1656_p2);

assign p_0_0_0116417851796_i_out = p_0_0_0116417851796_i_load_reg_2027;

assign p_0_0_0116517831794_i_out = p_0_0_0116517831794_i_load_reg_1931_pp0_iter2_reg;

assign p_0_0_0116617811792_i_out = p_0_0_0116617811792_i_load_reg_1925_pp0_iter2_reg;

assign p_0_0_01177_217791808_i_out = p_0_0_01177_217791808_i_load_reg_2032;

assign p_0_0_01178_217771806_i_out = p_0_0_01178_217771806_i_load_reg_1964_pp0_iter2_reg;

assign p_0_0_01179_217751804_i_out = p_0_0_01179_217751804_i_load_reg_1958_pp0_iter2_reg;

assign p_0_0_0_0_011581705_i_out = p_0_0_0_0_011581705_i_load_reg_2037;

assign p_0_1_0_0_011591708_i_out = p_0_1_0_0_011591708_i_load_reg_2042;

assign p_0_2_0_0_011601711_i_out = p_0_2_0_0_011601711_i_load_reg_2047;

assign phi_ln1046_fu_1689_p3 = ((icmp_ln1014_reg_1915_pp0_iter3_reg[0:0] == 1'b1) ? pix_reg_464_pp0_iter3_reg : select_ln1046_fu_1640_p3);

assign phi_ln1048_fu_1696_p3 = ((icmp_ln1014_reg_1915_pp0_iter3_reg[0:0] == 1'b1) ? pix_8_reg_444_pp0_iter3_reg : select_ln1048_fu_1681_p3);

assign r_0_in_i_cast1_fu_1595_p1 = r_0_in_i_reg_2149;

assign r_0_in_i_fu_1551_p2 = ($signed(zext_ln1034_1_fu_1343_p1) - $signed(r_0_in_i_v_v_cast_fu_1547_p1));

assign r_0_in_i_v_v_cast_fu_1547_p1 = $signed(r_0_in_i_v_v_fu_1539_p3);

assign r_0_in_i_v_v_fu_1539_p3 = ((icmp_ln1030_fu_1273_p2[0:0] == 1'b1) ? select_ln1033_fu_1335_p3 : select_ln1039_fu_1467_p3);

assign right_1_out = right_4_reg_1944_pp0_iter2_reg;

assign right_2_out = right_5_reg_1951_pp0_iter2_reg;

assign right_out = right_3_reg_1937_pp0_iter2_reg;

assign select_ln1033_fu_1335_p3 = ((tmp_16_fu_1295_p3[0:0] == 1'b1) ? sub_ln1033_3_fu_1319_p2 : zext_ln_fu_1325_p4);

assign select_ln1034_fu_1403_p3 = ((tmp_17_fu_1363_p3[0:0] == 1'b1) ? sub_ln1034_3_fu_1387_p2 : zext_ln1_fu_1393_p4);

assign select_ln1039_fu_1467_p3 = ((tmp_18_fu_1427_p3[0:0] == 1'b1) ? sub_ln1039_3_fu_1451_p2 : zext_ln2_fu_1457_p4);

assign select_ln1040_fu_1531_p3 = ((tmp_19_fu_1491_p3[0:0] == 1'b1) ? sub_ln1040_3_fu_1515_p2 : zext_ln3_fu_1521_p4);

assign select_ln1042_fu_1626_p3 = ((xor_ln1046_fu_1620_p2[0:0] == 1'b1) ? 10'd1023 : 10'd0);

assign select_ln1043_fu_1667_p3 = ((xor_ln1048_fu_1661_p2[0:0] == 1'b1) ? 10'd1023 : 10'd0);

assign select_ln1046_fu_1640_p3 = ((or_ln1042_fu_1634_p2[0:0] == 1'b1) ? select_ln1042_fu_1626_p3 : trunc_ln1046_fu_1604_p1);

assign select_ln1048_fu_1681_p3 = ((or_ln1043_fu_1675_p2[0:0] == 1'b1) ? select_ln1043_fu_1667_p3 : trunc_ln1048_fu_1601_p1);

assign select_ln957_10_fu_757_p3 = ((icmp_ln957_reg_1899[0:0] == 1'b1) ? ap_phi_mux_p_0_0_01178_21777_ph_i_phi_fu_365_p4 : p_0_0_01178_217771806_i_fu_178);

assign select_ln957_11_fu_764_p3 = ((icmp_ln957_reg_1899[0:0] == 1'b1) ? ap_phi_mux_p_0_0_01179_21775_ph_i_phi_fu_375_p4 : p_0_0_01179_217751804_i_fu_174);

assign select_ln957_1_fu_839_p3 = ((icmp_ln957_reg_1899_pp0_iter1_reg[0:0] == 1'b1) ? tmp_i_reg_1976 : right_4_reg_1944);

assign select_ln957_2_fu_845_p3 = ((icmp_ln957_reg_1899_pp0_iter1_reg[0:0] == 1'b1) ? tmp_1_i_reg_1983 : right_5_reg_1951);

assign select_ln957_3_fu_851_p3 = ((icmp_ln957_reg_1899_pp0_iter1_reg[0:0] == 1'b1) ? trunc_ln902_reg_1970 : p_0_0_0_0_011581705_i_fu_186);

assign select_ln957_4_fu_858_p3 = ((icmp_ln957_reg_1899_pp0_iter1_reg[0:0] == 1'b1) ? tmp_i_reg_1976 : p_0_1_0_0_011591708_i_fu_190);

assign select_ln957_5_fu_865_p3 = ((icmp_ln957_reg_1899_pp0_iter1_reg[0:0] == 1'b1) ? tmp_1_i_reg_1983 : p_0_2_0_0_011601711_i_fu_194);

assign select_ln957_6_fu_872_p3 = ((icmp_ln957_reg_1899_pp0_iter1_reg[0:0] == 1'b1) ? tmp_4_i_reg_1991 : p_0_0_0116417851796_i_fu_158);

assign select_ln957_7_fu_743_p3 = ((icmp_ln957_reg_1899[0:0] == 1'b1) ? tmp_3_i_fu_701_p3 : p_0_0_0116517831794_i_fu_154);

assign select_ln957_8_fu_750_p3 = ((icmp_ln957_reg_1899[0:0] == 1'b1) ? trunc_ln902_1_fu_697_p1 : p_0_0_0116617811792_i_fu_150);

assign select_ln957_9_fu_879_p3 = ((icmp_ln957_reg_1899_pp0_iter1_reg[0:0] == 1'b1) ? ap_phi_reg_pp0_iter2_p_0_0_01177_21779_ph_i_reg_381 : p_0_0_01177_217791808_i_fu_182);

assign select_ln957_fu_833_p3 = ((icmp_ln957_reg_1899_pp0_iter1_reg[0:0] == 1'b1) ? trunc_ln902_reg_1970 : right_3_reg_1937);

assign select_ln975_1_fu_887_p3 = ((icmp_ln975_reg_1872[0:0] == 1'b1) ? tmp_i_reg_1976 : p_0_0_01178_21777_ph_i_reg_362);

assign select_ln975_2_fu_893_p3 = ((icmp_ln975_reg_1872[0:0] == 1'b1) ? tmp_1_i_reg_1983 : ap_phi_reg_pp0_iter2_p_0_0_01177_21779_ph_i_reg_381);

assign select_ln975_fu_771_p3 = ((icmp_ln975_reg_1872[0:0] == 1'b1) ? trunc_ln902_fu_675_p1 : ap_phi_mux_p_0_0_01179_21775_ph_i_phi_fu_375_p4);

assign sext_ln1033_1_fu_1282_p1 = $signed(sub_ln1033_1_reg_2114);

assign sext_ln1033_2_fu_1291_p1 = add_ln1033_fu_1285_p2;

assign sext_ln1033_fu_1279_p1 = $signed(sub_ln1033_reg_2109);

assign sext_ln1034_1_fu_1350_p1 = $signed(sub_ln1034_1_reg_2124);

assign sext_ln1034_2_fu_1359_p1 = add_ln1034_fu_1353_p2;

assign sext_ln1034_fu_1347_p1 = $signed(sub_ln1034_reg_2119);

assign sext_ln1039_1_fu_1414_p1 = $signed(sub_ln1039_1_reg_2134);

assign sext_ln1039_2_fu_1423_p1 = add_ln1039_fu_1417_p2;

assign sext_ln1039_fu_1411_p1 = $signed(sub_ln1039_reg_2129);

assign sext_ln1040_1_fu_1478_p1 = $signed(sub_ln1040_1_reg_2144);

assign sext_ln1040_2_fu_1487_p1 = add_ln1040_fu_1481_p2;

assign sext_ln1040_fu_1475_p1 = $signed(sub_ln1040_reg_2139);

assign sext_ln1048_fu_1598_p1 = b_0_in_i_reg_2155;

assign sub_ln1023_fu_935_p2 = (zext_ln1023_fu_927_p1 - zext_ln1023_1_fu_931_p1);

assign sub_ln1024_fu_959_p2 = (zext_ln1024_fu_951_p1 - zext_ln1024_1_fu_955_p1);

assign sub_ln1025_fu_999_p2 = (zext_ln1025_fu_991_p1 - zext_ln1025_1_fu_995_p1);

assign sub_ln1026_fu_1023_p2 = (zext_ln1026_fu_1015_p1 - zext_ln1026_1_fu_1019_p1);

assign sub_ln1027_fu_1063_p2 = (zext_ln1027_fu_1055_p1 - zext_ln1027_1_fu_1059_p1);

assign sub_ln1028_fu_1081_p2 = (zext_ln1028_fu_1073_p1 - zext_ln1028_1_fu_1077_p1);

assign sub_ln1033_1_fu_1111_p2 = (zext_ln1025_1_fu_995_p1 - zext_ln1023_1_fu_931_p1);

assign sub_ln1033_2_fu_1303_p2 = ($signed(13'd0) - $signed(sext_ln1033_2_fu_1291_p1));

assign sub_ln1033_3_fu_1319_p2 = (11'd0 - lshr_ln1033_1_cast_fu_1309_p4);

assign sub_ln1033_fu_1105_p2 = (zext_ln1025_fu_991_p1 - zext_ln1023_fu_927_p1);

assign sub_ln1034_1_fu_1123_p2 = (zext_ln1025_1_fu_995_p1 - zext_ln1027_1_fu_1059_p1);

assign sub_ln1034_2_fu_1371_p2 = ($signed(13'd0) - $signed(sext_ln1034_2_fu_1359_p1));

assign sub_ln1034_3_fu_1387_p2 = (11'd0 - lshr_ln1034_1_cast_fu_1377_p4);

assign sub_ln1034_fu_1117_p2 = (zext_ln1025_fu_991_p1 - zext_ln1027_fu_1055_p1);

assign sub_ln1039_1_fu_1135_p2 = (zext_ln1026_1_fu_1019_p1 - zext_ln1024_1_fu_955_p1);

assign sub_ln1039_2_fu_1435_p2 = ($signed(13'd0) - $signed(sext_ln1039_2_fu_1423_p1));

assign sub_ln1039_3_fu_1451_p2 = (11'd0 - lshr_ln1039_1_cast_fu_1441_p4);

assign sub_ln1039_fu_1129_p2 = (zext_ln1026_fu_1015_p1 - zext_ln1024_fu_951_p1);

assign sub_ln1040_1_fu_1147_p2 = (zext_ln1026_1_fu_1019_p1 - zext_ln1028_1_fu_1077_p1);

assign sub_ln1040_2_fu_1499_p2 = ($signed(13'd0) - $signed(sext_ln1040_2_fu_1487_p1));

assign sub_ln1040_3_fu_1515_p2 = (11'd0 - lshr_ln1040_1_cast_fu_1505_p4);

assign sub_ln1040_fu_1141_p2 = (zext_ln1026_fu_1015_p1 - zext_ln1028_fu_1073_p1);

assign sub_ln61_4_fu_977_p2 = (10'd0 - trunc_ln61_4_fu_965_p1);

assign sub_ln61_5_fu_1009_p2 = (10'd0 - trunc_ln61_5_fu_1005_p1);

assign sub_ln61_6_fu_1041_p2 = (10'd0 - trunc_ln61_6_fu_1029_p1);

assign sub_ln61_7_fu_1201_p2 = (10'd0 - trunc_ln61_7_reg_2087);

assign sub_ln61_8_fu_1220_p2 = (10'd0 - trunc_ln61_8_reg_2098);

assign sub_ln61_fu_945_p2 = (10'd0 - trunc_ln61_fu_941_p1);

assign tmp_10_fu_1168_p3 = sub_ln1023_reg_2052[32'd10];

assign tmp_11_fu_969_p3 = sub_ln1024_fu_959_p2[32'd10];

assign tmp_12_fu_1181_p3 = sub_ln1025_reg_2067[32'd10];

assign tmp_13_fu_1033_p3 = sub_ln1026_fu_1023_p2[32'd10];

assign tmp_14_fu_1194_p3 = sub_ln1027_reg_2082[32'd10];

assign tmp_15_fu_1213_p3 = sub_ln1028_reg_2093[32'd10];

assign tmp_16_fu_1295_p3 = add_ln1033_fu_1285_p2[32'd11];

assign tmp_17_fu_1363_p3 = add_ln1034_fu_1353_p2[32'd11];

assign tmp_18_fu_1427_p3 = add_ln1039_fu_1417_p2[32'd11];

assign tmp_19_fu_1491_p3 = add_ln1040_fu_1481_p2[32'd11];

assign tmp_20_fu_1607_p3 = r_0_in_i_cast1_fu_1595_p1[32'd13];

assign tmp_22_fu_1648_p3 = sext_ln1048_fu_1598_p1[32'd13];

assign tmp_3_i_fu_701_p3 = {{lineBuffer_2_q1[19:10]}};

assign trunc_ln1046_fu_1604_p1 = r_0_in_i_reg_2149[9:0];

assign trunc_ln1048_fu_1601_p1 = b_0_in_i_reg_2155[9:0];

assign trunc_ln61_4_fu_965_p1 = sub_ln1024_fu_959_p2[9:0];

assign trunc_ln61_5_fu_1005_p1 = sub_ln1025_fu_999_p2[9:0];

assign trunc_ln61_6_fu_1029_p1 = sub_ln1026_fu_1023_p2[9:0];

assign trunc_ln61_7_fu_1069_p1 = sub_ln1027_fu_1063_p2[9:0];

assign trunc_ln61_8_fu_1087_p1 = sub_ln1028_fu_1081_p2[9:0];

assign trunc_ln61_fu_941_p1 = sub_ln1023_fu_935_p2[9:0];

assign trunc_ln881_fu_593_p1 = ap_sig_allocacmp_z[0:0];

assign trunc_ln902_1_fu_697_p1 = lineBuffer_2_q1[9:0];

assign trunc_ln902_fu_675_p1 = lineBuffer_q1[9:0];

assign trunc_ln913_fu_717_p1 = imgRB_dout[9:0];

assign x_8_fu_587_p2 = (ap_sig_allocacmp_z + 11'd1);

assign xor_ln1014_2_fu_621_p2 = (xor_ln1014_fu_615_p2 ^ 1'd1);

assign xor_ln1014_fu_615_p2 = (trunc_ln881_fu_593_p1 ^ empty);

assign xor_ln1046_fu_1620_p2 = (tmp_20_fu_1607_p3 ^ 1'd1);

assign xor_ln1048_fu_1661_p2 = (tmp_22_fu_1648_p3 ^ 1'd1);

assign zext_ln1014_fu_627_p1 = xor_ln1014_2_fu_621_p2;

assign zext_ln1023_1_fu_931_p1 = right_fu_162;

assign zext_ln1023_fu_927_p1 = ap_phi_mux_left_phi_fu_438_p4;

assign zext_ln1024_1_fu_955_p1 = ap_phi_mux_down_phi_fu_411_p4;

assign zext_ln1024_fu_951_p1 = ap_phi_mux_up_phi_fu_495_p4;

assign zext_ln1025_1_fu_995_p1 = right_1_fu_166;

assign zext_ln1025_fu_991_p1 = ap_phi_mux_left_1_phi_fu_429_p4;

assign zext_ln1026_1_fu_1019_p1 = ap_phi_mux_down_1_phi_fu_402_p4;

assign zext_ln1026_fu_1015_p1 = ap_phi_mux_up_1_phi_fu_486_p4;

assign zext_ln1027_1_fu_1059_p1 = right_2_fu_170;

assign zext_ln1027_fu_1055_p1 = ap_phi_mux_left_2_phi_fu_420_p4;

assign zext_ln1028_1_fu_1077_p1 = ap_phi_mux_down_2_phi_fu_393_p4;

assign zext_ln1028_fu_1073_p1 = ap_phi_mux_up_2_phi_fu_477_p4;

assign zext_ln1030_1_fu_1236_p1 = DGh_fu_1188_p3;

assign zext_ln1030_2_fu_1246_p1 = add_ln1030_fu_1240_p2;

assign zext_ln1030_3_fu_1250_p1 = DBh_fu_1206_p3;

assign zext_ln1030_4_fu_1091_p1 = DRv_fu_983_p3;

assign zext_ln1030_5_fu_1095_p1 = DGv_fu_1047_p3;

assign zext_ln1030_6_fu_1260_p1 = add_ln1030_2_reg_2104;

assign zext_ln1030_7_fu_1263_p1 = DBv_fu_1225_p3;

assign zext_ln1030_fu_1232_p1 = DRh_fu_1175_p3;

assign zext_ln1034_1_fu_1343_p1 = pix_7_reg_454;

assign zext_ln1_fu_1393_p4 = {{add_ln1034_fu_1353_p2[11:1]}};

assign zext_ln2_fu_1457_p4 = {{add_ln1039_fu_1417_p2[11:1]}};

assign zext_ln3_fu_1521_p4 = {{add_ln1040_fu_1481_p2[11:1]}};

assign zext_ln881_fu_597_p1 = x_8_fu_587_p2;

assign zext_ln_fu_1325_p4 = {{add_ln1033_fu_1285_p2[11:1]}};

endmodule //design_1_v_demosaic_0_0_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2
