// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module design_1_v_demosaic_0_0_Debayer (
        ap_start,
        start_full_n,
        start_out,
        start_write,
        imgBayer_dout,
        imgBayer_empty_n,
        imgBayer_read,
        imgRgb_din,
        imgRgb_full_n,
        imgRgb_write,
        height_val4,
        width_val8,
        bayerPhase_val11_dout,
        bayerPhase_val11_empty_n,
        bayerPhase_val11_read,
        ap_clk,
        ap_rst,
        height_val4_ap_vld,
        width_val8_ap_vld,
        imgRgb_dout,
        imgRgb_empty_n,
        imgRgb_read,
        imgRgb_num_data_valid,
        imgRgb_fifo_cap,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input   ap_start;
input   start_full_n;
output   start_out;
output   start_write;
input  [9:0] imgBayer_dout;
input   imgBayer_empty_n;
output   imgBayer_read;
output  [29:0] imgRgb_din;
input   imgRgb_full_n;
output   imgRgb_write;
input  [15:0] height_val4;
input  [15:0] width_val8;
input  [15:0] bayerPhase_val11_dout;
input   bayerPhase_val11_empty_n;
output   bayerPhase_val11_read;
input   ap_clk;
input   ap_rst;
input   height_val4_ap_vld;
input   width_val8_ap_vld;
input  [29:0] imgRgb_dout;
input   imgRgb_empty_n;
output   imgRgb_read;
input  [31:0] imgRgb_num_data_valid;
input  [31:0] imgRgb_fifo_cap;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

reg start_write;

reg    real_start;
reg    start_once_reg;
wire    internal_ap_ready;
wire    DebayerG_U0_ap_start;
wire    DebayerG_U0_ap_done;
wire    DebayerG_U0_ap_continue;
wire    DebayerG_U0_ap_idle;
wire    DebayerG_U0_ap_ready;
wire    DebayerG_U0_start_out;
wire    DebayerG_U0_start_write;
wire    DebayerG_U0_imgBayer_read;
wire   [29:0] DebayerG_U0_imgG_din;
wire    DebayerG_U0_imgG_write;
wire   [31:0] DebayerG_U0_imgG_num_data_valid;
wire   [31:0] DebayerG_U0_imgG_fifo_cap;
wire    DebayerG_U0_bayerPhase_val_read;
wire   [10:0] DebayerG_U0_height_val4_c3_din;
wire    DebayerG_U0_height_val4_c3_write;
wire   [10:0] DebayerG_U0_width_val8_c4_din;
wire    DebayerG_U0_width_val8_c4_write;
wire   [15:0] DebayerG_U0_bayerPhase_val11_c5_din;
wire    DebayerG_U0_bayerPhase_val11_c5_write;
wire    DebayerRatBorBatR_U0_ap_start;
wire    DebayerRatBorBatR_U0_ap_done;
wire    DebayerRatBorBatR_U0_ap_continue;
wire    DebayerRatBorBatR_U0_ap_idle;
wire    DebayerRatBorBatR_U0_ap_ready;
wire    DebayerRatBorBatR_U0_start_out;
wire    DebayerRatBorBatR_U0_start_write;
wire    DebayerRatBorBatR_U0_imgG_read;
wire   [29:0] DebayerRatBorBatR_U0_imgRB_din;
wire    DebayerRatBorBatR_U0_imgRB_write;
wire   [31:0] DebayerRatBorBatR_U0_imgRB_num_data_valid;
wire   [31:0] DebayerRatBorBatR_U0_imgRB_fifo_cap;
wire    DebayerRatBorBatR_U0_height_val4_read;
wire    DebayerRatBorBatR_U0_width_val8_read;
wire    DebayerRatBorBatR_U0_bayerPhase_val11_read;
wire   [10:0] DebayerRatBorBatR_U0_height_val4_c_din;
wire    DebayerRatBorBatR_U0_height_val4_c_write;
wire   [10:0] DebayerRatBorBatR_U0_width_val8_c_din;
wire    DebayerRatBorBatR_U0_width_val8_c_write;
wire   [15:0] DebayerRatBorBatR_U0_bayerPhase_val11_c_din;
wire    DebayerRatBorBatR_U0_bayerPhase_val11_c_write;
wire    DebayerRandBatG_U0_ap_start;
wire    DebayerRandBatG_U0_ap_done;
wire    DebayerRandBatG_U0_ap_continue;
wire    DebayerRandBatG_U0_ap_idle;
wire    DebayerRandBatG_U0_ap_ready;
wire    DebayerRandBatG_U0_imgRB_read;
wire   [29:0] DebayerRandBatG_U0_imgRgb_din;
wire    DebayerRandBatG_U0_imgRgb_write;
wire    DebayerRandBatG_U0_height_val4_read;
wire    DebayerRandBatG_U0_width_val8_read;
wire    DebayerRandBatG_U0_bayerPhase_val11_read;
wire    imgG_full_n;
wire   [29:0] imgG_dout;
wire    imgG_empty_n;
wire   [2:0] imgG_num_data_valid;
wire   [2:0] imgG_fifo_cap;
wire    height_val4_c3_full_n;
wire   [10:0] height_val4_c3_dout;
wire    height_val4_c3_empty_n;
wire   [2:0] height_val4_c3_num_data_valid;
wire   [2:0] height_val4_c3_fifo_cap;
wire    width_val8_c4_full_n;
wire   [10:0] width_val8_c4_dout;
wire    width_val8_c4_empty_n;
wire   [2:0] width_val8_c4_num_data_valid;
wire   [2:0] width_val8_c4_fifo_cap;
wire    bayerPhase_val11_c5_full_n;
wire   [15:0] bayerPhase_val11_c5_dout;
wire    bayerPhase_val11_c5_empty_n;
wire   [2:0] bayerPhase_val11_c5_num_data_valid;
wire   [2:0] bayerPhase_val11_c5_fifo_cap;
wire    imgRB_full_n;
wire   [29:0] imgRB_dout;
wire    imgRB_empty_n;
wire   [2:0] imgRB_num_data_valid;
wire   [2:0] imgRB_fifo_cap;
wire    height_val4_c_full_n;
wire   [10:0] height_val4_c_dout;
wire    height_val4_c_empty_n;
wire   [2:0] height_val4_c_num_data_valid;
wire   [2:0] height_val4_c_fifo_cap;
wire    width_val8_c_full_n;
wire   [10:0] width_val8_c_dout;
wire    width_val8_c_empty_n;
wire   [2:0] width_val8_c_num_data_valid;
wire   [2:0] width_val8_c_fifo_cap;
wire    bayerPhase_val11_c_full_n;
wire   [15:0] bayerPhase_val11_c_dout;
wire    bayerPhase_val11_c_empty_n;
wire   [2:0] bayerPhase_val11_c_num_data_valid;
wire   [2:0] bayerPhase_val11_c_fifo_cap;
wire    ap_sync_ready;
wire   [0:0] start_for_DebayerRatBorBatR_U0_din;
wire    start_for_DebayerRatBorBatR_U0_full_n;
wire   [0:0] start_for_DebayerRatBorBatR_U0_dout;
wire    start_for_DebayerRatBorBatR_U0_empty_n;
wire   [0:0] start_for_DebayerRandBatG_U0_din;
wire    start_for_DebayerRandBatG_U0_full_n;
wire   [0:0] start_for_DebayerRandBatG_U0_dout;
wire    start_for_DebayerRandBatG_U0_empty_n;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
end

design_1_v_demosaic_0_0_DebayerG DebayerG_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(DebayerG_U0_ap_start),
    .start_full_n(start_for_DebayerRatBorBatR_U0_full_n),
    .ap_done(DebayerG_U0_ap_done),
    .ap_continue(DebayerG_U0_ap_continue),
    .ap_idle(DebayerG_U0_ap_idle),
    .ap_ready(DebayerG_U0_ap_ready),
    .start_out(DebayerG_U0_start_out),
    .start_write(DebayerG_U0_start_write),
    .imgBayer_dout(imgBayer_dout),
    .imgBayer_empty_n(imgBayer_empty_n),
    .imgBayer_read(DebayerG_U0_imgBayer_read),
    .imgBayer_num_data_valid(3'd0),
    .imgBayer_fifo_cap(3'd0),
    .imgG_din(DebayerG_U0_imgG_din),
    .imgG_full_n(imgG_full_n),
    .imgG_write(DebayerG_U0_imgG_write),
    .imgG_num_data_valid(DebayerG_U0_imgG_num_data_valid),
    .imgG_fifo_cap(DebayerG_U0_imgG_fifo_cap),
    .height_val(height_val4),
    .width_val(width_val8),
    .bayerPhase_val_dout(bayerPhase_val11_dout),
    .bayerPhase_val_empty_n(bayerPhase_val11_empty_n),
    .bayerPhase_val_read(DebayerG_U0_bayerPhase_val_read),
    .bayerPhase_val_num_data_valid(3'd0),
    .bayerPhase_val_fifo_cap(3'd0),
    .height_val4_c3_din(DebayerG_U0_height_val4_c3_din),
    .height_val4_c3_full_n(height_val4_c3_full_n),
    .height_val4_c3_write(DebayerG_U0_height_val4_c3_write),
    .height_val4_c3_num_data_valid(height_val4_c3_num_data_valid),
    .height_val4_c3_fifo_cap(height_val4_c3_fifo_cap),
    .width_val8_c4_din(DebayerG_U0_width_val8_c4_din),
    .width_val8_c4_full_n(width_val8_c4_full_n),
    .width_val8_c4_write(DebayerG_U0_width_val8_c4_write),
    .width_val8_c4_num_data_valid(width_val8_c4_num_data_valid),
    .width_val8_c4_fifo_cap(width_val8_c4_fifo_cap),
    .bayerPhase_val11_c5_din(DebayerG_U0_bayerPhase_val11_c5_din),
    .bayerPhase_val11_c5_full_n(bayerPhase_val11_c5_full_n),
    .bayerPhase_val11_c5_write(DebayerG_U0_bayerPhase_val11_c5_write),
    .bayerPhase_val11_c5_num_data_valid(bayerPhase_val11_c5_num_data_valid),
    .bayerPhase_val11_c5_fifo_cap(bayerPhase_val11_c5_fifo_cap)
);

design_1_v_demosaic_0_0_DebayerRatBorBatR DebayerRatBorBatR_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(DebayerRatBorBatR_U0_ap_start),
    .start_full_n(start_for_DebayerRandBatG_U0_full_n),
    .ap_done(DebayerRatBorBatR_U0_ap_done),
    .ap_continue(DebayerRatBorBatR_U0_ap_continue),
    .ap_idle(DebayerRatBorBatR_U0_ap_idle),
    .ap_ready(DebayerRatBorBatR_U0_ap_ready),
    .start_out(DebayerRatBorBatR_U0_start_out),
    .start_write(DebayerRatBorBatR_U0_start_write),
    .imgG_dout(imgG_dout),
    .imgG_empty_n(imgG_empty_n),
    .imgG_read(DebayerRatBorBatR_U0_imgG_read),
    .imgG_num_data_valid(imgG_num_data_valid),
    .imgG_fifo_cap(imgG_fifo_cap),
    .imgRB_din(DebayerRatBorBatR_U0_imgRB_din),
    .imgRB_full_n(imgRB_full_n),
    .imgRB_write(DebayerRatBorBatR_U0_imgRB_write),
    .imgRB_num_data_valid(DebayerRatBorBatR_U0_imgRB_num_data_valid),
    .imgRB_fifo_cap(DebayerRatBorBatR_U0_imgRB_fifo_cap),
    .height_val4_dout(height_val4_c3_dout),
    .height_val4_empty_n(height_val4_c3_empty_n),
    .height_val4_read(DebayerRatBorBatR_U0_height_val4_read),
    .height_val4_num_data_valid(height_val4_c3_num_data_valid),
    .height_val4_fifo_cap(height_val4_c3_fifo_cap),
    .width_val8_dout(width_val8_c4_dout),
    .width_val8_empty_n(width_val8_c4_empty_n),
    .width_val8_read(DebayerRatBorBatR_U0_width_val8_read),
    .width_val8_num_data_valid(width_val8_c4_num_data_valid),
    .width_val8_fifo_cap(width_val8_c4_fifo_cap),
    .bayerPhase_val11_dout(bayerPhase_val11_c5_dout),
    .bayerPhase_val11_empty_n(bayerPhase_val11_c5_empty_n),
    .bayerPhase_val11_read(DebayerRatBorBatR_U0_bayerPhase_val11_read),
    .bayerPhase_val11_num_data_valid(bayerPhase_val11_c5_num_data_valid),
    .bayerPhase_val11_fifo_cap(bayerPhase_val11_c5_fifo_cap),
    .height_val4_c_din(DebayerRatBorBatR_U0_height_val4_c_din),
    .height_val4_c_full_n(height_val4_c_full_n),
    .height_val4_c_write(DebayerRatBorBatR_U0_height_val4_c_write),
    .height_val4_c_num_data_valid(height_val4_c_num_data_valid),
    .height_val4_c_fifo_cap(height_val4_c_fifo_cap),
    .width_val8_c_din(DebayerRatBorBatR_U0_width_val8_c_din),
    .width_val8_c_full_n(width_val8_c_full_n),
    .width_val8_c_write(DebayerRatBorBatR_U0_width_val8_c_write),
    .width_val8_c_num_data_valid(width_val8_c_num_data_valid),
    .width_val8_c_fifo_cap(width_val8_c_fifo_cap),
    .bayerPhase_val11_c_din(DebayerRatBorBatR_U0_bayerPhase_val11_c_din),
    .bayerPhase_val11_c_full_n(bayerPhase_val11_c_full_n),
    .bayerPhase_val11_c_write(DebayerRatBorBatR_U0_bayerPhase_val11_c_write),
    .bayerPhase_val11_c_num_data_valid(bayerPhase_val11_c_num_data_valid),
    .bayerPhase_val11_c_fifo_cap(bayerPhase_val11_c_fifo_cap)
);

design_1_v_demosaic_0_0_DebayerRandBatG DebayerRandBatG_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(DebayerRandBatG_U0_ap_start),
    .ap_done(DebayerRandBatG_U0_ap_done),
    .ap_continue(DebayerRandBatG_U0_ap_continue),
    .ap_idle(DebayerRandBatG_U0_ap_idle),
    .ap_ready(DebayerRandBatG_U0_ap_ready),
    .imgRB_dout(imgRB_dout),
    .imgRB_empty_n(imgRB_empty_n),
    .imgRB_read(DebayerRandBatG_U0_imgRB_read),
    .imgRB_num_data_valid(imgRB_num_data_valid),
    .imgRB_fifo_cap(imgRB_fifo_cap),
    .imgRgb_din(DebayerRandBatG_U0_imgRgb_din),
    .imgRgb_full_n(imgRgb_full_n),
    .imgRgb_write(DebayerRandBatG_U0_imgRgb_write),
    .imgRgb_num_data_valid(imgRgb_num_data_valid),
    .imgRgb_fifo_cap(imgRgb_fifo_cap),
    .height_val4_dout(height_val4_c_dout),
    .height_val4_empty_n(height_val4_c_empty_n),
    .height_val4_read(DebayerRandBatG_U0_height_val4_read),
    .height_val4_num_data_valid(height_val4_c_num_data_valid),
    .height_val4_fifo_cap(height_val4_c_fifo_cap),
    .width_val8_dout(width_val8_c_dout),
    .width_val8_empty_n(width_val8_c_empty_n),
    .width_val8_read(DebayerRandBatG_U0_width_val8_read),
    .width_val8_num_data_valid(width_val8_c_num_data_valid),
    .width_val8_fifo_cap(width_val8_c_fifo_cap),
    .bayerPhase_val11_dout(bayerPhase_val11_c_dout),
    .bayerPhase_val11_empty_n(bayerPhase_val11_c_empty_n),
    .bayerPhase_val11_read(DebayerRandBatG_U0_bayerPhase_val11_read),
    .bayerPhase_val11_num_data_valid(bayerPhase_val11_c_num_data_valid),
    .bayerPhase_val11_fifo_cap(bayerPhase_val11_c_fifo_cap)
);

design_1_v_demosaic_0_0_fifo_w30_d2_S imgG_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(DebayerG_U0_imgG_din),
    .if_full_n(imgG_full_n),
    .if_write(DebayerG_U0_imgG_write),
    .if_dout(imgG_dout),
    .if_empty_n(imgG_empty_n),
    .if_read(DebayerRatBorBatR_U0_imgG_read),
    .if_num_data_valid(imgG_num_data_valid),
    .if_fifo_cap(imgG_fifo_cap)
);

design_1_v_demosaic_0_0_fifo_w11_d2_S height_val4_c3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(DebayerG_U0_height_val4_c3_din),
    .if_full_n(height_val4_c3_full_n),
    .if_write(DebayerG_U0_height_val4_c3_write),
    .if_dout(height_val4_c3_dout),
    .if_empty_n(height_val4_c3_empty_n),
    .if_read(DebayerRatBorBatR_U0_height_val4_read),
    .if_num_data_valid(height_val4_c3_num_data_valid),
    .if_fifo_cap(height_val4_c3_fifo_cap)
);

design_1_v_demosaic_0_0_fifo_w11_d2_S width_val8_c4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(DebayerG_U0_width_val8_c4_din),
    .if_full_n(width_val8_c4_full_n),
    .if_write(DebayerG_U0_width_val8_c4_write),
    .if_dout(width_val8_c4_dout),
    .if_empty_n(width_val8_c4_empty_n),
    .if_read(DebayerRatBorBatR_U0_width_val8_read),
    .if_num_data_valid(width_val8_c4_num_data_valid),
    .if_fifo_cap(width_val8_c4_fifo_cap)
);

design_1_v_demosaic_0_0_fifo_w16_d2_S bayerPhase_val11_c5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(DebayerG_U0_bayerPhase_val11_c5_din),
    .if_full_n(bayerPhase_val11_c5_full_n),
    .if_write(DebayerG_U0_bayerPhase_val11_c5_write),
    .if_dout(bayerPhase_val11_c5_dout),
    .if_empty_n(bayerPhase_val11_c5_empty_n),
    .if_read(DebayerRatBorBatR_U0_bayerPhase_val11_read),
    .if_num_data_valid(bayerPhase_val11_c5_num_data_valid),
    .if_fifo_cap(bayerPhase_val11_c5_fifo_cap)
);

design_1_v_demosaic_0_0_fifo_w30_d2_S imgRB_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(DebayerRatBorBatR_U0_imgRB_din),
    .if_full_n(imgRB_full_n),
    .if_write(DebayerRatBorBatR_U0_imgRB_write),
    .if_dout(imgRB_dout),
    .if_empty_n(imgRB_empty_n),
    .if_read(DebayerRandBatG_U0_imgRB_read),
    .if_num_data_valid(imgRB_num_data_valid),
    .if_fifo_cap(imgRB_fifo_cap)
);

design_1_v_demosaic_0_0_fifo_w11_d2_S height_val4_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(DebayerRatBorBatR_U0_height_val4_c_din),
    .if_full_n(height_val4_c_full_n),
    .if_write(DebayerRatBorBatR_U0_height_val4_c_write),
    .if_dout(height_val4_c_dout),
    .if_empty_n(height_val4_c_empty_n),
    .if_read(DebayerRandBatG_U0_height_val4_read),
    .if_num_data_valid(height_val4_c_num_data_valid),
    .if_fifo_cap(height_val4_c_fifo_cap)
);

design_1_v_demosaic_0_0_fifo_w11_d2_S width_val8_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(DebayerRatBorBatR_U0_width_val8_c_din),
    .if_full_n(width_val8_c_full_n),
    .if_write(DebayerRatBorBatR_U0_width_val8_c_write),
    .if_dout(width_val8_c_dout),
    .if_empty_n(width_val8_c_empty_n),
    .if_read(DebayerRandBatG_U0_width_val8_read),
    .if_num_data_valid(width_val8_c_num_data_valid),
    .if_fifo_cap(width_val8_c_fifo_cap)
);

design_1_v_demosaic_0_0_fifo_w16_d2_S bayerPhase_val11_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(DebayerRatBorBatR_U0_bayerPhase_val11_c_din),
    .if_full_n(bayerPhase_val11_c_full_n),
    .if_write(DebayerRatBorBatR_U0_bayerPhase_val11_c_write),
    .if_dout(bayerPhase_val11_c_dout),
    .if_empty_n(bayerPhase_val11_c_empty_n),
    .if_read(DebayerRandBatG_U0_bayerPhase_val11_read),
    .if_num_data_valid(bayerPhase_val11_c_num_data_valid),
    .if_fifo_cap(bayerPhase_val11_c_fifo_cap)
);

design_1_v_demosaic_0_0_start_for_DebayerRatBorBatR_U0 start_for_DebayerRatBorBatR_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_DebayerRatBorBatR_U0_din),
    .if_full_n(start_for_DebayerRatBorBatR_U0_full_n),
    .if_write(DebayerG_U0_start_write),
    .if_dout(start_for_DebayerRatBorBatR_U0_dout),
    .if_empty_n(start_for_DebayerRatBorBatR_U0_empty_n),
    .if_read(DebayerRatBorBatR_U0_ap_ready)
);

design_1_v_demosaic_0_0_start_for_DebayerRandBatG_U0 start_for_DebayerRandBatG_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_DebayerRandBatG_U0_din),
    .if_full_n(start_for_DebayerRandBatG_U0_full_n),
    .if_write(DebayerRatBorBatR_U0_start_write),
    .if_dout(start_for_DebayerRandBatG_U0_dout),
    .if_empty_n(start_for_DebayerRandBatG_U0_empty_n),
    .if_read(DebayerRandBatG_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

assign DebayerG_U0_ap_continue = 1'b1;

assign DebayerG_U0_ap_start = real_start;

assign DebayerG_U0_imgG_fifo_cap = imgG_fifo_cap;

assign DebayerG_U0_imgG_num_data_valid = imgG_num_data_valid;

assign DebayerRandBatG_U0_ap_continue = ap_continue;

assign DebayerRandBatG_U0_ap_start = start_for_DebayerRandBatG_U0_empty_n;

assign DebayerRatBorBatR_U0_ap_continue = 1'b1;

assign DebayerRatBorBatR_U0_ap_start = start_for_DebayerRatBorBatR_U0_empty_n;

assign DebayerRatBorBatR_U0_imgRB_fifo_cap = imgRB_fifo_cap;

assign DebayerRatBorBatR_U0_imgRB_num_data_valid = imgRB_num_data_valid;

assign ap_done = DebayerRandBatG_U0_ap_done;

assign ap_idle = (DebayerRatBorBatR_U0_ap_idle & DebayerRandBatG_U0_ap_idle & DebayerG_U0_ap_idle);

assign ap_ready = DebayerG_U0_ap_ready;

assign ap_sync_ready = DebayerG_U0_ap_ready;

assign bayerPhase_val11_read = DebayerG_U0_bayerPhase_val_read;

assign imgBayer_read = DebayerG_U0_imgBayer_read;

assign imgRgb_din = DebayerRandBatG_U0_imgRgb_din;

assign imgRgb_read = 1'b0;

assign imgRgb_write = DebayerRandBatG_U0_imgRgb_write;

assign internal_ap_ready = ap_sync_ready;

assign start_for_DebayerRandBatG_U0_din = 1'b1;

assign start_for_DebayerRatBorBatR_U0_din = 1'b1;

assign start_out = real_start;

endmodule //design_1_v_demosaic_0_0_Debayer
