
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2025.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2026 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xaxis_switch.h"

/*
* The configuration table for devices
*/

XAxis_Switch_Config XAxis_Switch_ConfigTable[XPAR_XAXIS_SWITCH_NUM_INSTANCES] =
{
	{
		XPAR_RAW_SWITCH_DEVICE_ID,
		XPAR_RAW_SWITCH_BASEADDR,
		XPAR_RAW_SWITCH_NUM_SI,
		XPAR_RAW_SWITCH_NUM_MI
	}
};


