-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity design_1_v_demosaic_0_0_ZipperRemoval is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    imgRgb_dout : IN STD_LOGIC_VECTOR (29 downto 0);
    imgRgb_empty_n : IN STD_LOGIC;
    imgRgb_read : OUT STD_LOGIC;
    imgRgb_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    imgRgb_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    imgUnzip_din : OUT STD_LOGIC_VECTOR (29 downto 0);
    imgUnzip_full_n : IN STD_LOGIC;
    imgUnzip_write : OUT STD_LOGIC;
    imgUnzip_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
    imgUnzip_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
    height_val : IN STD_LOGIC_VECTOR (15 downto 0);
    width_val : IN STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of design_1_v_demosaic_0_0_ZipperRemoval is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv17_1 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000001";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal width_val_read_reg_261 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal height_val_read_reg_266 : STD_LOGIC_VECTOR (15 downto 0);
    signal loopWidth_fu_120_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal loopWidth_reg_271 : STD_LOGIC_VECTOR (16 downto 0);
    signal conv2_i_i_lcssa735_load_reg_279 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal p_0_0_0503705_lcssa712737_load_reg_284 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_0502701_lcssa714739_load_reg_289 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_0501703_lcssa716741_load_reg_294 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_ap_start : STD_LOGIC;
    signal grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_ap_done : STD_LOGIC;
    signal grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_ap_idle : STD_LOGIC;
    signal grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_ap_ready : STD_LOGIC;
    signal grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_imgRgb_read : STD_LOGIC;
    signal grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_imgUnzip_din : STD_LOGIC_VECTOR (29 downto 0);
    signal grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_imgUnzip_write : STD_LOGIC;
    signal grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0504_1715_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0504_1715_out_ap_vld : STD_LOGIC;
    signal grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0505_1713_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0505_1713_out_ap_vld : STD_LOGIC;
    signal grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0506_1711_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0506_1711_out_ap_vld : STD_LOGIC;
    signal grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0504_1709_out_o : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0504_1709_out_o_ap_vld : STD_LOGIC;
    signal grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0505_1708_out_o : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0505_1708_out_o_ap_vld : STD_LOGIC;
    signal grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0506_1707_out_o : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0506_1707_out_o_ap_vld : STD_LOGIC;
    signal grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0507_1706_out_o : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0507_1706_out_o_ap_vld : STD_LOGIC;
    signal grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_phi_ln1132_out : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_phi_ln1132_out_ap_vld : STD_LOGIC;
    signal grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal p_0_0_0501703_lcssa716741_fu_78 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal p_0_0_0502701_lcssa714739_fu_74 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal p_0_0_0503705_lcssa712737_fu_70 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal p_0_0_0504_1_lcssa733_fu_62 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal p_0_0_0505_1_lcssa731_fu_58 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal p_0_0_0506_1_lcssa729_fu_54 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal p_0_0_0507_1_lcssa727_fu_50 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal conv2_i_i_lcssa735_fu_66 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal y_fu_46 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal y_2_fu_179_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln1099_fu_174_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln1085_fu_116_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component design_1_v_demosaic_0_0_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        imgRgb_dout : IN STD_LOGIC_VECTOR (29 downto 0);
        imgRgb_empty_n : IN STD_LOGIC;
        imgRgb_read : OUT STD_LOGIC;
        imgRgb_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        imgRgb_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        imgUnzip_din : OUT STD_LOGIC_VECTOR (29 downto 0);
        imgUnzip_full_n : IN STD_LOGIC;
        imgUnzip_write : OUT STD_LOGIC;
        imgUnzip_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
        imgUnzip_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
        p_0_0_0501703_lcssa716741 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_0502701_lcssa714739 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_0503705_lcssa712737 : IN STD_LOGIC_VECTOR (9 downto 0);
        conv2_i_i_lcssa735 : IN STD_LOGIC_VECTOR (6 downto 0);
        width_val : IN STD_LOGIC_VECTOR (15 downto 0);
        loopWidth : IN STD_LOGIC_VECTOR (16 downto 0);
        p_0_0_0504_1715_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_0504_1715_out_ap_vld : OUT STD_LOGIC;
        p_0_0_0505_1713_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_0505_1713_out_ap_vld : OUT STD_LOGIC;
        p_0_0_0506_1711_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_0506_1711_out_ap_vld : OUT STD_LOGIC;
        p_0_0_0504_1709_out_i : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_0504_1709_out_o : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_0504_1709_out_o_ap_vld : OUT STD_LOGIC;
        p_0_0_0505_1708_out_i : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_0505_1708_out_o : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_0505_1708_out_o_ap_vld : OUT STD_LOGIC;
        p_0_0_0506_1707_out_i : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_0506_1707_out_o : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_0506_1707_out_o_ap_vld : OUT STD_LOGIC;
        p_0_0_0507_1706_out_i : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_0507_1706_out_o : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_0507_1706_out_o_ap_vld : OUT STD_LOGIC;
        phi_ln1132_out : OUT STD_LOGIC_VECTOR (6 downto 0);
        phi_ln1132_out_ap_vld : OUT STD_LOGIC );
    end component;



begin
    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94 : component design_1_v_demosaic_0_0_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_ap_start,
        ap_done => grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_ap_done,
        ap_idle => grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_ap_idle,
        ap_ready => grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_ap_ready,
        imgRgb_dout => imgRgb_dout,
        imgRgb_empty_n => imgRgb_empty_n,
        imgRgb_read => grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_imgRgb_read,
        imgRgb_num_data_valid => ap_const_lv3_0,
        imgRgb_fifo_cap => ap_const_lv3_0,
        imgUnzip_din => grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_imgUnzip_din,
        imgUnzip_full_n => imgUnzip_full_n,
        imgUnzip_write => grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_imgUnzip_write,
        imgUnzip_num_data_valid => imgUnzip_num_data_valid,
        imgUnzip_fifo_cap => imgUnzip_fifo_cap,
        p_0_0_0501703_lcssa716741 => p_0_0_0501703_lcssa716741_load_reg_294,
        p_0_0_0502701_lcssa714739 => p_0_0_0502701_lcssa714739_load_reg_289,
        p_0_0_0503705_lcssa712737 => p_0_0_0503705_lcssa712737_load_reg_284,
        conv2_i_i_lcssa735 => conv2_i_i_lcssa735_load_reg_279,
        width_val => width_val_read_reg_261,
        loopWidth => loopWidth_reg_271,
        p_0_0_0504_1715_out => grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0504_1715_out,
        p_0_0_0504_1715_out_ap_vld => grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0504_1715_out_ap_vld,
        p_0_0_0505_1713_out => grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0505_1713_out,
        p_0_0_0505_1713_out_ap_vld => grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0505_1713_out_ap_vld,
        p_0_0_0506_1711_out => grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0506_1711_out,
        p_0_0_0506_1711_out_ap_vld => grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0506_1711_out_ap_vld,
        p_0_0_0504_1709_out_i => p_0_0_0504_1_lcssa733_fu_62,
        p_0_0_0504_1709_out_o => grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0504_1709_out_o,
        p_0_0_0504_1709_out_o_ap_vld => grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0504_1709_out_o_ap_vld,
        p_0_0_0505_1708_out_i => p_0_0_0505_1_lcssa731_fu_58,
        p_0_0_0505_1708_out_o => grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0505_1708_out_o,
        p_0_0_0505_1708_out_o_ap_vld => grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0505_1708_out_o_ap_vld,
        p_0_0_0506_1707_out_i => p_0_0_0506_1_lcssa729_fu_54,
        p_0_0_0506_1707_out_o => grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0506_1707_out_o,
        p_0_0_0506_1707_out_o_ap_vld => grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0506_1707_out_o_ap_vld,
        p_0_0_0507_1706_out_i => p_0_0_0507_1_lcssa727_fu_50,
        p_0_0_0507_1706_out_o => grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0507_1706_out_o,
        p_0_0_0507_1706_out_o_ap_vld => grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0507_1706_out_o_ap_vld,
        phi_ln1132_out => grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_phi_ln1132_out,
        phi_ln1132_out_ap_vld => grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_phi_ln1132_out_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln1099_fu_174_p2 = ap_const_lv1_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_ap_ready = ap_const_logic_1)) then 
                    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    conv2_i_i_lcssa735_fu_66_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                conv2_i_i_lcssa735_fu_66 <= ap_const_lv7_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_phi_ln1132_out_ap_vld = ap_const_logic_1))) then 
                conv2_i_i_lcssa735_fu_66 <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_phi_ln1132_out;
            end if; 
        end if;
    end process;

    p_0_0_0501703_lcssa716741_fu_78_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                p_0_0_0501703_lcssa716741_fu_78 <= ap_const_lv10_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0504_1715_out_ap_vld = ap_const_logic_1))) then 
                p_0_0_0501703_lcssa716741_fu_78 <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0504_1715_out;
            end if; 
        end if;
    end process;

    p_0_0_0502701_lcssa714739_fu_74_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                p_0_0_0502701_lcssa714739_fu_74 <= ap_const_lv10_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0505_1713_out_ap_vld = ap_const_logic_1))) then 
                p_0_0_0502701_lcssa714739_fu_74 <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0505_1713_out;
            end if; 
        end if;
    end process;

    p_0_0_0503705_lcssa712737_fu_70_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                p_0_0_0503705_lcssa712737_fu_70 <= ap_const_lv10_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0506_1711_out_ap_vld = ap_const_logic_1))) then 
                p_0_0_0503705_lcssa712737_fu_70 <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0506_1711_out;
            end if; 
        end if;
    end process;

    p_0_0_0504_1_lcssa733_fu_62_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                p_0_0_0504_1_lcssa733_fu_62 <= ap_const_lv10_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0504_1709_out_o_ap_vld = ap_const_logic_1))) then 
                p_0_0_0504_1_lcssa733_fu_62 <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0504_1709_out_o;
            end if; 
        end if;
    end process;

    p_0_0_0505_1_lcssa731_fu_58_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                p_0_0_0505_1_lcssa731_fu_58 <= ap_const_lv10_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0505_1708_out_o_ap_vld = ap_const_logic_1))) then 
                p_0_0_0505_1_lcssa731_fu_58 <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0505_1708_out_o;
            end if; 
        end if;
    end process;

    p_0_0_0506_1_lcssa729_fu_54_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                p_0_0_0506_1_lcssa729_fu_54 <= ap_const_lv10_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0506_1707_out_o_ap_vld = ap_const_logic_1))) then 
                p_0_0_0506_1_lcssa729_fu_54 <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0506_1707_out_o;
            end if; 
        end if;
    end process;

    p_0_0_0507_1_lcssa727_fu_50_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                p_0_0_0507_1_lcssa727_fu_50 <= ap_const_lv10_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0507_1706_out_o_ap_vld = ap_const_logic_1))) then 
                p_0_0_0507_1_lcssa727_fu_50 <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_p_0_0_0507_1706_out_o;
            end if; 
        end if;
    end process;

    y_fu_46_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                y_fu_46 <= ap_const_lv16_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln1099_fu_174_p2 = ap_const_lv1_0))) then 
                y_fu_46 <= y_2_fu_179_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                conv2_i_i_lcssa735_load_reg_279 <= conv2_i_i_lcssa735_fu_66;
                p_0_0_0501703_lcssa716741_load_reg_294 <= p_0_0_0501703_lcssa716741_fu_78;
                p_0_0_0502701_lcssa714739_load_reg_289 <= p_0_0_0502701_lcssa714739_fu_74;
                p_0_0_0503705_lcssa712737_load_reg_284 <= p_0_0_0503705_lcssa712737_fu_70;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                height_val_read_reg_266 <= height_val;
                loopWidth_reg_271 <= loopWidth_fu_120_p2;
                width_val_read_reg_261 <= width_val;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1, ap_CS_fsm_state2, grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_ap_done, ap_CS_fsm_state4, icmp_ln1099_fu_174_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln1099_fu_174_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_ap_done)
    begin
        if ((grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state2, icmp_ln1099_fu_174_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln1099_fu_174_p2 = ap_const_lv1_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_ap_start <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_ap_start_reg;
    icmp_ln1099_fu_174_p2 <= "1" when (y_fu_46 = height_val_read_reg_266) else "0";
    imgRgb_read <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_imgRgb_read;
    imgUnzip_din <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_imgUnzip_din;
    imgUnzip_write <= grp_ZipperRemoval_Pipeline_VITIS_LOOP_1101_2_fu_94_imgUnzip_write;

    internal_ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln1099_fu_174_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln1099_fu_174_p2 = ap_const_lv1_1))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    loopWidth_fu_120_p2 <= std_logic_vector(unsigned(zext_ln1085_fu_116_p1) + unsigned(ap_const_lv17_1));

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    y_2_fu_179_p2 <= std_logic_vector(unsigned(y_fu_46) + unsigned(ap_const_lv16_1));
    zext_ln1085_fu_116_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(width_val),17));
end behav;
