-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity design_1_v_demosaic_0_0_DebayerG is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    imgBayer_dout : IN STD_LOGIC_VECTOR (9 downto 0);
    imgBayer_empty_n : IN STD_LOGIC;
    imgBayer_read : OUT STD_LOGIC;
    imgBayer_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    imgBayer_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    imgG_din : OUT STD_LOGIC_VECTOR (29 downto 0);
    imgG_full_n : IN STD_LOGIC;
    imgG_write : OUT STD_LOGIC;
    imgG_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
    imgG_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
    height_val : IN STD_LOGIC_VECTOR (15 downto 0);
    width_val : IN STD_LOGIC_VECTOR (15 downto 0);
    bayerPhase_val_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    bayerPhase_val_empty_n : IN STD_LOGIC;
    bayerPhase_val_read : OUT STD_LOGIC;
    bayerPhase_val_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    bayerPhase_val_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    height_val4_c3_din : OUT STD_LOGIC_VECTOR (10 downto 0);
    height_val4_c3_full_n : IN STD_LOGIC;
    height_val4_c3_write : OUT STD_LOGIC;
    height_val4_c3_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    height_val4_c3_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    width_val8_c4_din : OUT STD_LOGIC_VECTOR (10 downto 0);
    width_val8_c4_full_n : IN STD_LOGIC;
    width_val8_c4_write : OUT STD_LOGIC;
    width_val8_c4_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    width_val8_c4_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    bayerPhase_val11_c5_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    bayerPhase_val11_c5_full_n : IN STD_LOGIC;
    bayerPhase_val11_c5_write : OUT STD_LOGIC;
    bayerPhase_val11_c5_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    bayerPhase_val11_c5_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0) );
end;


architecture behav of design_1_v_demosaic_0_0_DebayerG is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv17_2 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000010";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv17_1 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000001";
    constant ap_const_lv17_1FFFE : STD_LOGIC_VECTOR (16 downto 0) := "11111111111111110";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal bayerPhase_val_blk_n : STD_LOGIC;
    signal height_val4_c3_blk_n : STD_LOGIC;
    signal width_val8_c4_blk_n : STD_LOGIC;
    signal bayerPhase_val11_c5_blk_n : STD_LOGIC;
    signal width_val_read_reg_537 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal height_val_read_reg_542 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_phase_fu_271_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal x_phase_reg_547 : STD_LOGIC_VECTOR (0 downto 0);
    signal loopHeight_fu_279_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal loopHeight_reg_552 : STD_LOGIC_VECTOR (16 downto 0);
    signal loopWidth_fu_289_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal loopWidth_reg_557 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln_reg_562 : STD_LOGIC_VECTOR (14 downto 0);
    signal y_7_reg_568 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal p_lcssa50495082_load_reg_577 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa50515084_load_reg_582 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa50525086_load_reg_587 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa50535088_load_reg_592 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa50555090_load_reg_597 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa50565092_load_reg_602 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa50575094_load_reg_607 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa50595096_load_reg_612 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa50605098_load_reg_617 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa50615100_load_reg_622 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa50635102_load_reg_627 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa50645104_load_reg_632 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa50655106_load_reg_637 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa50675108_load_reg_642 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa50685110_load_reg_647 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa52275233_load_reg_652 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa52285235_load_reg_657 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa52295237_load_reg_662 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa52305239_load_reg_667 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa52315241_load_reg_672 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln325_fu_389_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln325_reg_677 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal trunc_ln439_fu_395_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln439_reg_682 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln439_fu_404_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal xor_ln439_reg_687 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_ap_start : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_ap_done : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_ap_idle : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_ap_ready : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_imgBayer_read : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_imgG_din : STD_LOGIC_VECTOR (29 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_imgG_write : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out1_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out2 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out2_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out3 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out3_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out4 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out4_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out5 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out5_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out6 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out6_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out7 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out7_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out8 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out8_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out9 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out9_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out10 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out10_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out11 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out11_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out12 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out12_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out13 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out13_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out14 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out14_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out15 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out15_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out16 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out16_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out17 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out17_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out18 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out18_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out19 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out19_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal p_lcssa52315241_fu_156 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa52305239_fu_152 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa52295237_fu_148 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa52285235_fu_144 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa52275233_fu_140 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa50685110_fu_136 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa50675108_fu_132 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa50655106_fu_128 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa50645104_fu_124 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa50635102_fu_120 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa50615100_fu_116 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa50605098_fu_112 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa50595096_fu_108 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa50575094_fu_104 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa50565092_fu_100 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa50555090_fu_96 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa50535088_fu_92 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa50525086_fu_88 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa50515084_fu_84 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa50495082_fu_80 : STD_LOGIC_VECTOR (9 downto 0);
    signal y_fu_76 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    signal y_8_fu_318_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal icmp_ln315_fu_313_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln274_fu_275_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln275_fu_285_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln439_fu_400_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component design_1_v_demosaic_0_0_DebayerG_Pipeline_VITIS_LOOP_318_4 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        imgBayer_dout : IN STD_LOGIC_VECTOR (9 downto 0);
        imgBayer_empty_n : IN STD_LOGIC;
        imgBayer_read : OUT STD_LOGIC;
        imgBayer_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        imgBayer_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        imgG_din : OUT STD_LOGIC_VECTOR (29 downto 0);
        imgG_full_n : IN STD_LOGIC;
        imgG_write : OUT STD_LOGIC;
        imgG_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
        imgG_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
        p_lcssa52315241 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_lcssa52305239 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_lcssa52295237 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_lcssa52285235 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_lcssa52275233 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_lcssa50685110 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_lcssa50675108 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_lcssa50655106 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_lcssa50645104 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_lcssa50635102 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_lcssa50615100 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_lcssa50605098 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_lcssa50595096 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_lcssa50575094 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_lcssa50565092 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_lcssa50555090 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_lcssa50535088 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_lcssa50525086 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_lcssa50515084 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_lcssa50495082 : IN STD_LOGIC_VECTOR (9 downto 0);
        height_val : IN STD_LOGIC_VECTOR (15 downto 0);
        y : IN STD_LOGIC_VECTOR (16 downto 0);
        width_val : IN STD_LOGIC_VECTOR (15 downto 0);
        empty_56 : IN STD_LOGIC_VECTOR (0 downto 0);
        trunc_ln : IN STD_LOGIC_VECTOR (14 downto 0);
        loopWidth : IN STD_LOGIC_VECTOR (16 downto 0);
        empty : IN STD_LOGIC_VECTOR (0 downto 0);
        xor_ln439 : IN STD_LOGIC_VECTOR (14 downto 0);
        out_y : IN STD_LOGIC_VECTOR (16 downto 0);
        p_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_out_ap_vld : OUT STD_LOGIC;
        p_out1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_out1_ap_vld : OUT STD_LOGIC;
        p_out2 : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_out2_ap_vld : OUT STD_LOGIC;
        p_out3 : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_out3_ap_vld : OUT STD_LOGIC;
        p_out4 : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_out4_ap_vld : OUT STD_LOGIC;
        p_out5 : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_out5_ap_vld : OUT STD_LOGIC;
        p_out6 : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_out6_ap_vld : OUT STD_LOGIC;
        p_out7 : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_out7_ap_vld : OUT STD_LOGIC;
        p_out8 : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_out8_ap_vld : OUT STD_LOGIC;
        p_out9 : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_out9_ap_vld : OUT STD_LOGIC;
        p_out10 : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_out10_ap_vld : OUT STD_LOGIC;
        p_out11 : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_out11_ap_vld : OUT STD_LOGIC;
        p_out12 : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_out12_ap_vld : OUT STD_LOGIC;
        p_out13 : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_out13_ap_vld : OUT STD_LOGIC;
        p_out14 : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_out14_ap_vld : OUT STD_LOGIC;
        p_out15 : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_out15_ap_vld : OUT STD_LOGIC;
        p_out16 : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_out16_ap_vld : OUT STD_LOGIC;
        p_out17 : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_out17_ap_vld : OUT STD_LOGIC;
        p_out18 : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_out18_ap_vld : OUT STD_LOGIC;
        p_out19 : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_out19_ap_vld : OUT STD_LOGIC );
    end component;



begin
    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200 : component design_1_v_demosaic_0_0_DebayerG_Pipeline_VITIS_LOOP_318_4
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_ap_start,
        ap_done => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_ap_done,
        ap_idle => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_ap_idle,
        ap_ready => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_ap_ready,
        imgBayer_dout => imgBayer_dout,
        imgBayer_empty_n => imgBayer_empty_n,
        imgBayer_read => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_imgBayer_read,
        imgBayer_num_data_valid => ap_const_lv3_0,
        imgBayer_fifo_cap => ap_const_lv3_0,
        imgG_din => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_imgG_din,
        imgG_full_n => imgG_full_n,
        imgG_write => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_imgG_write,
        imgG_num_data_valid => imgG_num_data_valid,
        imgG_fifo_cap => imgG_fifo_cap,
        p_lcssa52315241 => p_lcssa52315241_load_reg_672,
        p_lcssa52305239 => p_lcssa52305239_load_reg_667,
        p_lcssa52295237 => p_lcssa52295237_load_reg_662,
        p_lcssa52285235 => p_lcssa52285235_load_reg_657,
        p_lcssa52275233 => p_lcssa52275233_load_reg_652,
        p_lcssa50685110 => p_lcssa50685110_load_reg_647,
        p_lcssa50675108 => p_lcssa50675108_load_reg_642,
        p_lcssa50655106 => p_lcssa50655106_load_reg_637,
        p_lcssa50645104 => p_lcssa50645104_load_reg_632,
        p_lcssa50635102 => p_lcssa50635102_load_reg_627,
        p_lcssa50615100 => p_lcssa50615100_load_reg_622,
        p_lcssa50605098 => p_lcssa50605098_load_reg_617,
        p_lcssa50595096 => p_lcssa50595096_load_reg_612,
        p_lcssa50575094 => p_lcssa50575094_load_reg_607,
        p_lcssa50565092 => p_lcssa50565092_load_reg_602,
        p_lcssa50555090 => p_lcssa50555090_load_reg_597,
        p_lcssa50535088 => p_lcssa50535088_load_reg_592,
        p_lcssa50525086 => p_lcssa50525086_load_reg_587,
        p_lcssa50515084 => p_lcssa50515084_load_reg_582,
        p_lcssa50495082 => p_lcssa50495082_load_reg_577,
        height_val => height_val_read_reg_542,
        y => y_7_reg_568,
        width_val => width_val_read_reg_537,
        empty_56 => trunc_ln439_reg_682,
        trunc_ln => trunc_ln_reg_562,
        loopWidth => loopWidth_reg_557,
        empty => x_phase_reg_547,
        xor_ln439 => xor_ln439_reg_687,
        out_y => add_ln325_reg_677,
        p_out => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out,
        p_out_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out_ap_vld,
        p_out1 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out1,
        p_out1_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out1_ap_vld,
        p_out2 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out2,
        p_out2_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out2_ap_vld,
        p_out3 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out3,
        p_out3_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out3_ap_vld,
        p_out4 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out4,
        p_out4_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out4_ap_vld,
        p_out5 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out5,
        p_out5_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out5_ap_vld,
        p_out6 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out6,
        p_out6_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out6_ap_vld,
        p_out7 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out7,
        p_out7_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out7_ap_vld,
        p_out8 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out8,
        p_out8_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out8_ap_vld,
        p_out9 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out9,
        p_out9_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out9_ap_vld,
        p_out10 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out10,
        p_out10_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out10_ap_vld,
        p_out11 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out11,
        p_out11_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out11_ap_vld,
        p_out12 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out12,
        p_out12_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out12_ap_vld,
        p_out13 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out13,
        p_out13_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out13_ap_vld,
        p_out14 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out14,
        p_out14_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out14_ap_vld,
        p_out15 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out15,
        p_out15_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out15_ap_vld,
        p_out16 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out16,
        p_out16_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out16_ap_vld,
        p_out17 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out17,
        p_out17_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out17_ap_vld,
        p_out18 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out18,
        p_out18_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out18_ap_vld,
        p_out19 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out19,
        p_out19_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out19_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((icmp_ln315_fu_313_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_ap_ready = ap_const_logic_1)) then 
                    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    y_fu_76_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                y_fu_76 <= ap_const_lv17_0;
            elsif (((icmp_ln315_fu_313_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                y_fu_76 <= y_8_fu_318_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                add_ln325_reg_677 <= add_ln325_fu_389_p2;
                trunc_ln439_reg_682 <= trunc_ln439_fu_395_p1;
                xor_ln439_reg_687 <= xor_ln439_fu_404_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                height_val_read_reg_542 <= height_val;
                loopHeight_reg_552 <= loopHeight_fu_279_p2;
                loopWidth_reg_557 <= loopWidth_fu_289_p2;
                trunc_ln_reg_562 <= bayerPhase_val_dout(15 downto 1);
                width_val_read_reg_537 <= width_val;
                x_phase_reg_547 <= x_phase_fu_271_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out19_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_lcssa50495082_fu_80 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out19;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                p_lcssa50495082_load_reg_577 <= p_lcssa50495082_fu_80;
                p_lcssa50515084_load_reg_582 <= p_lcssa50515084_fu_84;
                p_lcssa50525086_load_reg_587 <= p_lcssa50525086_fu_88;
                p_lcssa50535088_load_reg_592 <= p_lcssa50535088_fu_92;
                p_lcssa50555090_load_reg_597 <= p_lcssa50555090_fu_96;
                p_lcssa50565092_load_reg_602 <= p_lcssa50565092_fu_100;
                p_lcssa50575094_load_reg_607 <= p_lcssa50575094_fu_104;
                p_lcssa50595096_load_reg_612 <= p_lcssa50595096_fu_108;
                p_lcssa50605098_load_reg_617 <= p_lcssa50605098_fu_112;
                p_lcssa50615100_load_reg_622 <= p_lcssa50615100_fu_116;
                p_lcssa50635102_load_reg_627 <= p_lcssa50635102_fu_120;
                p_lcssa50645104_load_reg_632 <= p_lcssa50645104_fu_124;
                p_lcssa50655106_load_reg_637 <= p_lcssa50655106_fu_128;
                p_lcssa50675108_load_reg_642 <= p_lcssa50675108_fu_132;
                p_lcssa50685110_load_reg_647 <= p_lcssa50685110_fu_136;
                p_lcssa52275233_load_reg_652 <= p_lcssa52275233_fu_140;
                p_lcssa52285235_load_reg_657 <= p_lcssa52285235_fu_144;
                p_lcssa52295237_load_reg_662 <= p_lcssa52295237_fu_148;
                p_lcssa52305239_load_reg_667 <= p_lcssa52305239_fu_152;
                p_lcssa52315241_load_reg_672 <= p_lcssa52315241_fu_156;
                y_7_reg_568 <= y_fu_76;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out18_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_lcssa50515084_fu_84 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out18;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out17_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_lcssa50525086_fu_88 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out17;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out16_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_lcssa50535088_fu_92 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out16;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out15_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_lcssa50555090_fu_96 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out15;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out14_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_lcssa50565092_fu_100 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out14;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out13_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_lcssa50575094_fu_104 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out13;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out12_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_lcssa50595096_fu_108 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out12;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out11_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_lcssa50605098_fu_112 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out11;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out10_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_lcssa50615100_fu_116 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out10;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out9_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_lcssa50635102_fu_120 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out9;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out8_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_lcssa50645104_fu_124 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out8;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out7_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_lcssa50655106_fu_128 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out7;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out6_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_lcssa50675108_fu_132 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out6;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out5_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_lcssa50685110_fu_136 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out5;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out4_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_lcssa52275233_fu_140 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out3_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_lcssa52285235_fu_144 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out2_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_lcssa52295237_fu_148 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out1_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_lcssa52305239_fu_152 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_lcssa52315241_fu_156 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1, ap_CS_fsm_state2, grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_ap_done, ap_CS_fsm_state4, icmp_ln315_fu_313_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln315_fu_313_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    add_ln325_fu_389_p2 <= std_logic_vector(unsigned(y_7_reg_568) + unsigned(ap_const_lv17_1FFFE));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_ap_done)
    begin
        if ((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg, bayerPhase_val_empty_n, height_val4_c3_full_n, width_val8_c4_full_n, bayerPhase_val11_c5_full_n)
    begin
                ap_block_state1 <= ((bayerPhase_val11_c5_full_n = ap_const_logic_0) or (width_val8_c4_full_n = ap_const_logic_0) or (height_val4_c3_full_n = ap_const_logic_0) or (bayerPhase_val_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state2, icmp_ln315_fu_313_p2)
    begin
        if (((icmp_ln315_fu_313_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;

    bayerPhase_val11_c5_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, bayerPhase_val11_c5_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            bayerPhase_val11_c5_blk_n <= bayerPhase_val11_c5_full_n;
        else 
            bayerPhase_val11_c5_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    bayerPhase_val11_c5_din <= bayerPhase_val_dout;

    bayerPhase_val11_c5_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            bayerPhase_val11_c5_write <= ap_const_logic_1;
        else 
            bayerPhase_val11_c5_write <= ap_const_logic_0;
        end if; 
    end process;


    bayerPhase_val_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, bayerPhase_val_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            bayerPhase_val_blk_n <= bayerPhase_val_empty_n;
        else 
            bayerPhase_val_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    bayerPhase_val_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            bayerPhase_val_read <= ap_const_logic_1;
        else 
            bayerPhase_val_read <= ap_const_logic_0;
        end if; 
    end process;

    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_ap_start <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_ap_start_reg;

    height_val4_c3_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, height_val4_c3_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            height_val4_c3_blk_n <= height_val4_c3_full_n;
        else 
            height_val4_c3_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    height_val4_c3_din <= height_val(11 - 1 downto 0);

    height_val4_c3_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            height_val4_c3_write <= ap_const_logic_1;
        else 
            height_val4_c3_write <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln315_fu_313_p2 <= "1" when (y_fu_76 = loopHeight_reg_552) else "0";
    imgBayer_read <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_imgBayer_read;
    imgG_din <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_imgG_din;
    imgG_write <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_imgG_write;

    internal_ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln315_fu_313_p2)
    begin
        if (((icmp_ln315_fu_313_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    loopHeight_fu_279_p2 <= std_logic_vector(unsigned(zext_ln274_fu_275_p1) + unsigned(ap_const_lv17_2));
    loopWidth_fu_289_p2 <= std_logic_vector(unsigned(zext_ln275_fu_285_p1) + unsigned(ap_const_lv17_2));

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln439_fu_395_p1 <= add_ln325_fu_389_p2(1 - 1 downto 0);

    width_val8_c4_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, width_val8_c4_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            width_val8_c4_blk_n <= width_val8_c4_full_n;
        else 
            width_val8_c4_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    width_val8_c4_din <= width_val(11 - 1 downto 0);

    width_val8_c4_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            width_val8_c4_write <= ap_const_logic_1;
        else 
            width_val8_c4_write <= ap_const_logic_0;
        end if; 
    end process;

    x_phase_fu_271_p1 <= bayerPhase_val_dout(1 - 1 downto 0);
    xor_ln439_fu_404_p2 <= (zext_ln439_fu_400_p1 xor trunc_ln_reg_562);
    y_8_fu_318_p2 <= std_logic_vector(unsigned(y_fu_76) + unsigned(ap_const_lv17_1));
    zext_ln274_fu_275_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(height_val),17));
    zext_ln275_fu_285_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(width_val),17));
    zext_ln439_fu_400_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln439_fu_395_p1),15));
end behav;
