# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: v:/zybo_z7_imx219/zybo_z7_imx219.srcs/sources_1/bd/design_1/ip/design_1_rst_display_axis_0/design_1_rst_display_axis_0.xci
# IP: The module: 'design_1_rst_display_axis_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: v:/zybo_z7_imx219/zybo_z7_imx219.gen/sources_1/bd/design_1/ip/design_1_rst_display_axis_0/design_1_rst_display_axis_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_display_axis_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: v:/zybo_z7_imx219/zybo_z7_imx219.gen/sources_1/bd/design_1/ip/design_1_rst_display_axis_0/design_1_rst_display_axis_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_display_axis_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: v:/zybo_z7_imx219/zybo_z7_imx219.srcs/sources_1/bd/design_1/ip/design_1_rst_display_axis_0/design_1_rst_display_axis_0.xci
# IP: The module: 'design_1_rst_display_axis_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: v:/zybo_z7_imx219/zybo_z7_imx219.gen/sources_1/bd/design_1/ip/design_1_rst_display_axis_0/design_1_rst_display_axis_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_display_axis_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: v:/zybo_z7_imx219/zybo_z7_imx219.gen/sources_1/bd/design_1/ip/design_1_rst_display_axis_0/design_1_rst_display_axis_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_display_axis_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
