"""Deterministic RAW10 black-level / sRGB ROM; no image editing."""
from pathlib import Path
import math

ROOT = Path(__file__).resolve().parents[1]

def encode(raw):
    v = max(0, raw - 64) / 959.0
    return min(255, int(math.floor(255 * (12.92*v if v <= .0031308 else 1.055*v**(1/2.4)-.055) + .5)))

if __name__ == '__main__':
    values = [encode(v) for v in range(1024)]
    assert values[64] == 0 and values[-1] == 255
    assert all(a <= b for a,b in zip(values, values[1:]))
    (ROOT/'src/isp_srgb.mem').write_text(''.join(f'{v:02x}\n' for v in values))
    # Inverse LUT for AE on the gamma-coded GBR888 output: Q12 linear light.
    inv = []
    for v in range(256):
        s = v/255.0
        inv.append(round(4095 * (s/12.92 if s <= .04045 else ((s+.055)/1.055)**2.4)))
    (ROOT/'sw/src/ae_linear_lut.h').write_text(
        '/* Generated by scripts/gen_isp_rtl.py */\nstatic const unsigned short AeLinear[256] = {\n' +
        ',\n'.join(','.join(map(str,inv[i:i+16])) for i in range(0,256,16)) + '\n};\n')
