// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module design_1_v_demosaic_0_0_DebayerG (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        imgBayer_dout,
        imgBayer_empty_n,
        imgBayer_read,
        imgBayer_num_data_valid,
        imgBayer_fifo_cap,
        imgG_din,
        imgG_full_n,
        imgG_write,
        imgG_num_data_valid,
        imgG_fifo_cap,
        height_val,
        width_val,
        bayerPhase_val_dout,
        bayerPhase_val_empty_n,
        bayerPhase_val_read,
        bayerPhase_val_num_data_valid,
        bayerPhase_val_fifo_cap,
        height_val4_c3_din,
        height_val4_c3_full_n,
        height_val4_c3_write,
        height_val4_c3_num_data_valid,
        height_val4_c3_fifo_cap,
        width_val8_c4_din,
        width_val8_c4_full_n,
        width_val8_c4_write,
        width_val8_c4_num_data_valid,
        width_val8_c4_fifo_cap,
        bayerPhase_val11_c5_din,
        bayerPhase_val11_c5_full_n,
        bayerPhase_val11_c5_write,
        bayerPhase_val11_c5_num_data_valid,
        bayerPhase_val11_c5_fifo_cap
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [9:0] imgBayer_dout;
input   imgBayer_empty_n;
output   imgBayer_read;
input  [2:0] imgBayer_num_data_valid;
input  [2:0] imgBayer_fifo_cap;
output  [29:0] imgG_din;
input   imgG_full_n;
output   imgG_write;
input  [31:0] imgG_num_data_valid;
input  [31:0] imgG_fifo_cap;
input  [15:0] height_val;
input  [15:0] width_val;
input  [15:0] bayerPhase_val_dout;
input   bayerPhase_val_empty_n;
output   bayerPhase_val_read;
input  [2:0] bayerPhase_val_num_data_valid;
input  [2:0] bayerPhase_val_fifo_cap;
output  [10:0] height_val4_c3_din;
input   height_val4_c3_full_n;
output   height_val4_c3_write;
input  [2:0] height_val4_c3_num_data_valid;
input  [2:0] height_val4_c3_fifo_cap;
output  [10:0] width_val8_c4_din;
input   width_val8_c4_full_n;
output   width_val8_c4_write;
input  [2:0] width_val8_c4_num_data_valid;
input  [2:0] width_val8_c4_fifo_cap;
output  [15:0] bayerPhase_val11_c5_din;
input   bayerPhase_val11_c5_full_n;
output   bayerPhase_val11_c5_write;
input  [2:0] bayerPhase_val11_c5_num_data_valid;
input  [2:0] bayerPhase_val11_c5_fifo_cap;

reg ap_done;
reg ap_idle;
reg start_write;
reg bayerPhase_val_read;
reg height_val4_c3_write;
reg width_val8_c4_write;
reg bayerPhase_val11_c5_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    bayerPhase_val_blk_n;
reg    height_val4_c3_blk_n;
reg    width_val8_c4_blk_n;
reg    bayerPhase_val11_c5_blk_n;
reg   [15:0] width_val_read_reg_537;
reg    ap_block_state1;
reg   [15:0] height_val_read_reg_542;
wire   [0:0] x_phase_fu_271_p1;
reg   [0:0] x_phase_reg_547;
wire   [16:0] loopHeight_fu_279_p2;
reg   [16:0] loopHeight_reg_552;
wire   [16:0] loopWidth_fu_289_p2;
reg   [16:0] loopWidth_reg_557;
reg   [14:0] trunc_ln_reg_562;
reg   [16:0] y_7_reg_568;
wire    ap_CS_fsm_state2;
reg   [9:0] p_lcssa50495082_load_reg_577;
reg   [9:0] p_lcssa50515084_load_reg_582;
reg   [9:0] p_lcssa50525086_load_reg_587;
reg   [9:0] p_lcssa50535088_load_reg_592;
reg   [9:0] p_lcssa50555090_load_reg_597;
reg   [9:0] p_lcssa50565092_load_reg_602;
reg   [9:0] p_lcssa50575094_load_reg_607;
reg   [9:0] p_lcssa50595096_load_reg_612;
reg   [9:0] p_lcssa50605098_load_reg_617;
reg   [9:0] p_lcssa50615100_load_reg_622;
reg   [9:0] p_lcssa50635102_load_reg_627;
reg   [9:0] p_lcssa50645104_load_reg_632;
reg   [9:0] p_lcssa50655106_load_reg_637;
reg   [9:0] p_lcssa50675108_load_reg_642;
reg   [9:0] p_lcssa50685110_load_reg_647;
reg   [9:0] p_lcssa52275233_load_reg_652;
reg   [9:0] p_lcssa52285235_load_reg_657;
reg   [9:0] p_lcssa52295237_load_reg_662;
reg   [9:0] p_lcssa52305239_load_reg_667;
reg   [9:0] p_lcssa52315241_load_reg_672;
wire   [16:0] add_ln325_fu_389_p2;
reg   [16:0] add_ln325_reg_677;
wire    ap_CS_fsm_state3;
wire   [0:0] trunc_ln439_fu_395_p1;
reg   [0:0] trunc_ln439_reg_682;
wire   [14:0] xor_ln439_fu_404_p2;
reg   [14:0] xor_ln439_reg_687;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_ap_start;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_ap_done;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_ap_idle;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_ap_ready;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_imgBayer_read;
wire   [29:0] grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_imgG_din;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_imgG_write;
wire   [9:0] grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out_ap_vld;
wire   [9:0] grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out1;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out1_ap_vld;
wire   [9:0] grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out2;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out2_ap_vld;
wire   [9:0] grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out3;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out3_ap_vld;
wire   [9:0] grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out4;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out4_ap_vld;
wire   [9:0] grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out5;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out5_ap_vld;
wire   [9:0] grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out6;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out6_ap_vld;
wire   [9:0] grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out7;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out7_ap_vld;
wire   [9:0] grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out8;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out8_ap_vld;
wire   [9:0] grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out9;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out9_ap_vld;
wire   [9:0] grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out10;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out10_ap_vld;
wire   [9:0] grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out11;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out11_ap_vld;
wire   [9:0] grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out12;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out12_ap_vld;
wire   [9:0] grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out13;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out13_ap_vld;
wire   [9:0] grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out14;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out14_ap_vld;
wire   [9:0] grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out15;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out15_ap_vld;
wire   [9:0] grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out16;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out16_ap_vld;
wire   [9:0] grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out17;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out17_ap_vld;
wire   [9:0] grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out18;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out18_ap_vld;
wire   [9:0] grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out19;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out19_ap_vld;
reg    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_ap_start_reg;
wire    ap_CS_fsm_state4;
reg   [9:0] p_lcssa52315241_fu_156;
reg   [9:0] p_lcssa52305239_fu_152;
reg   [9:0] p_lcssa52295237_fu_148;
reg   [9:0] p_lcssa52285235_fu_144;
reg   [9:0] p_lcssa52275233_fu_140;
reg   [9:0] p_lcssa50685110_fu_136;
reg   [9:0] p_lcssa50675108_fu_132;
reg   [9:0] p_lcssa50655106_fu_128;
reg   [9:0] p_lcssa50645104_fu_124;
reg   [9:0] p_lcssa50635102_fu_120;
reg   [9:0] p_lcssa50615100_fu_116;
reg   [9:0] p_lcssa50605098_fu_112;
reg   [9:0] p_lcssa50595096_fu_108;
reg   [9:0] p_lcssa50575094_fu_104;
reg   [9:0] p_lcssa50565092_fu_100;
reg   [9:0] p_lcssa50555090_fu_96;
reg   [9:0] p_lcssa50535088_fu_92;
reg   [9:0] p_lcssa50525086_fu_88;
reg   [9:0] p_lcssa50515084_fu_84;
reg   [9:0] p_lcssa50495082_fu_80;
reg   [16:0] y_fu_76;
wire   [16:0] y_8_fu_318_p2;
wire   [0:0] icmp_ln315_fu_313_p2;
wire   [16:0] zext_ln274_fu_275_p1;
wire   [16:0] zext_ln275_fu_285_p1;
wire   [14:0] zext_ln439_fu_400_p1;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_ap_start_reg = 1'b0;
#0 y_fu_76 = 17'd0;
end

design_1_v_demosaic_0_0_DebayerG_Pipeline_VITIS_LOOP_318_4 grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_ap_start),
    .ap_done(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_ap_done),
    .ap_idle(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_ap_idle),
    .ap_ready(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_ap_ready),
    .imgBayer_dout(imgBayer_dout),
    .imgBayer_empty_n(imgBayer_empty_n),
    .imgBayer_read(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_imgBayer_read),
    .imgBayer_num_data_valid(3'd0),
    .imgBayer_fifo_cap(3'd0),
    .imgG_din(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_imgG_din),
    .imgG_full_n(imgG_full_n),
    .imgG_write(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_imgG_write),
    .imgG_num_data_valid(imgG_num_data_valid),
    .imgG_fifo_cap(imgG_fifo_cap),
    .p_lcssa52315241(p_lcssa52315241_load_reg_672),
    .p_lcssa52305239(p_lcssa52305239_load_reg_667),
    .p_lcssa52295237(p_lcssa52295237_load_reg_662),
    .p_lcssa52285235(p_lcssa52285235_load_reg_657),
    .p_lcssa52275233(p_lcssa52275233_load_reg_652),
    .p_lcssa50685110(p_lcssa50685110_load_reg_647),
    .p_lcssa50675108(p_lcssa50675108_load_reg_642),
    .p_lcssa50655106(p_lcssa50655106_load_reg_637),
    .p_lcssa50645104(p_lcssa50645104_load_reg_632),
    .p_lcssa50635102(p_lcssa50635102_load_reg_627),
    .p_lcssa50615100(p_lcssa50615100_load_reg_622),
    .p_lcssa50605098(p_lcssa50605098_load_reg_617),
    .p_lcssa50595096(p_lcssa50595096_load_reg_612),
    .p_lcssa50575094(p_lcssa50575094_load_reg_607),
    .p_lcssa50565092(p_lcssa50565092_load_reg_602),
    .p_lcssa50555090(p_lcssa50555090_load_reg_597),
    .p_lcssa50535088(p_lcssa50535088_load_reg_592),
    .p_lcssa50525086(p_lcssa50525086_load_reg_587),
    .p_lcssa50515084(p_lcssa50515084_load_reg_582),
    .p_lcssa50495082(p_lcssa50495082_load_reg_577),
    .height_val(height_val_read_reg_542),
    .y(y_7_reg_568),
    .width_val(width_val_read_reg_537),
    .empty_56(trunc_ln439_reg_682),
    .trunc_ln(trunc_ln_reg_562),
    .loopWidth(loopWidth_reg_557),
    .empty(x_phase_reg_547),
    .xor_ln439(xor_ln439_reg_687),
    .out_y(add_ln325_reg_677),
    .p_out(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out),
    .p_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out_ap_vld),
    .p_out1(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out1),
    .p_out1_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out1_ap_vld),
    .p_out2(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out2),
    .p_out2_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out2_ap_vld),
    .p_out3(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out3),
    .p_out3_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out3_ap_vld),
    .p_out4(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out4),
    .p_out4_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out4_ap_vld),
    .p_out5(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out5),
    .p_out5_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out5_ap_vld),
    .p_out6(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out6),
    .p_out6_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out6_ap_vld),
    .p_out7(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out7),
    .p_out7_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out7_ap_vld),
    .p_out8(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out8),
    .p_out8_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out8_ap_vld),
    .p_out9(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out9),
    .p_out9_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out9_ap_vld),
    .p_out10(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out10),
    .p_out10_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out10_ap_vld),
    .p_out11(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out11),
    .p_out11_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out11_ap_vld),
    .p_out12(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out12),
    .p_out12_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out12_ap_vld),
    .p_out13(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out13),
    .p_out13_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out13_ap_vld),
    .p_out14(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out14),
    .p_out14_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out14_ap_vld),
    .p_out15(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out15),
    .p_out15_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out15_ap_vld),
    .p_out16(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out16),
    .p_out16_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out16_ap_vld),
    .p_out17(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out17),
    .p_out17_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out17_ap_vld),
    .p_out18(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out18),
    .p_out18_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out18_ap_vld),
    .p_out19(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out19),
    .p_out19_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out19_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((icmp_ln315_fu_313_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_ap_start_reg <= 1'b1;
        end else if ((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_ap_ready == 1'b1)) begin
            grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        y_fu_76 <= 17'd0;
    end else if (((icmp_ln315_fu_313_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        y_fu_76 <= y_8_fu_318_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        add_ln325_reg_677 <= add_ln325_fu_389_p2;
        trunc_ln439_reg_682 <= trunc_ln439_fu_395_p1;
        xor_ln439_reg_687 <= xor_ln439_fu_404_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        height_val_read_reg_542 <= height_val;
        loopHeight_reg_552 <= loopHeight_fu_279_p2;
        loopWidth_reg_557 <= loopWidth_fu_289_p2;
        trunc_ln_reg_562 <= {{bayerPhase_val_dout[15:1]}};
        width_val_read_reg_537 <= width_val;
        x_phase_reg_547 <= x_phase_fu_271_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out19_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_lcssa50495082_fu_80 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out19;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        p_lcssa50495082_load_reg_577 <= p_lcssa50495082_fu_80;
        p_lcssa50515084_load_reg_582 <= p_lcssa50515084_fu_84;
        p_lcssa50525086_load_reg_587 <= p_lcssa50525086_fu_88;
        p_lcssa50535088_load_reg_592 <= p_lcssa50535088_fu_92;
        p_lcssa50555090_load_reg_597 <= p_lcssa50555090_fu_96;
        p_lcssa50565092_load_reg_602 <= p_lcssa50565092_fu_100;
        p_lcssa50575094_load_reg_607 <= p_lcssa50575094_fu_104;
        p_lcssa50595096_load_reg_612 <= p_lcssa50595096_fu_108;
        p_lcssa50605098_load_reg_617 <= p_lcssa50605098_fu_112;
        p_lcssa50615100_load_reg_622 <= p_lcssa50615100_fu_116;
        p_lcssa50635102_load_reg_627 <= p_lcssa50635102_fu_120;
        p_lcssa50645104_load_reg_632 <= p_lcssa50645104_fu_124;
        p_lcssa50655106_load_reg_637 <= p_lcssa50655106_fu_128;
        p_lcssa50675108_load_reg_642 <= p_lcssa50675108_fu_132;
        p_lcssa50685110_load_reg_647 <= p_lcssa50685110_fu_136;
        p_lcssa52275233_load_reg_652 <= p_lcssa52275233_fu_140;
        p_lcssa52285235_load_reg_657 <= p_lcssa52285235_fu_144;
        p_lcssa52295237_load_reg_662 <= p_lcssa52295237_fu_148;
        p_lcssa52305239_load_reg_667 <= p_lcssa52305239_fu_152;
        p_lcssa52315241_load_reg_672 <= p_lcssa52315241_fu_156;
        y_7_reg_568 <= y_fu_76;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out18_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_lcssa50515084_fu_84 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out18;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out17_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_lcssa50525086_fu_88 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out17;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out16_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_lcssa50535088_fu_92 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out16;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out15_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_lcssa50555090_fu_96 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out15;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out14_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_lcssa50565092_fu_100 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out14;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out13_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_lcssa50575094_fu_104 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out13;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out12_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_lcssa50595096_fu_108 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out12;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out11_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_lcssa50605098_fu_112 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out11;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out10_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_lcssa50615100_fu_116 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out10;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out9_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_lcssa50635102_fu_120 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out9;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out8_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_lcssa50645104_fu_124 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out8;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out7_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_lcssa50655106_fu_128 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out7;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out6_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_lcssa50675108_fu_132 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out6;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out5_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_lcssa50685110_fu_136 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out5;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out4_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_lcssa52275233_fu_140 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out4;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out3_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_lcssa52285235_fu_144 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out3;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out2_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_lcssa52295237_fu_148 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out1_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_lcssa52305239_fu_152 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out1;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_lcssa52315241_fu_156 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_p_out;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln315_fu_313_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        bayerPhase_val11_c5_blk_n = bayerPhase_val11_c5_full_n;
    end else begin
        bayerPhase_val11_c5_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        bayerPhase_val11_c5_write = 1'b1;
    end else begin
        bayerPhase_val11_c5_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        bayerPhase_val_blk_n = bayerPhase_val_empty_n;
    end else begin
        bayerPhase_val_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        bayerPhase_val_read = 1'b1;
    end else begin
        bayerPhase_val_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        height_val4_c3_blk_n = height_val4_c3_full_n;
    end else begin
        height_val4_c3_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        height_val4_c3_write = 1'b1;
    end else begin
        height_val4_c3_write = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln315_fu_313_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        width_val8_c4_blk_n = width_val8_c4_full_n;
    end else begin
        width_val8_c4_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        width_val8_c4_write = 1'b1;
    end else begin
        width_val8_c4_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln315_fu_313_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln325_fu_389_p2 = ($signed(y_7_reg_568) + $signed(17'd131070));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((bayerPhase_val11_c5_full_n == 1'b0) | (width_val8_c4_full_n == 1'b0) | (height_val4_c3_full_n == 1'b0) | (bayerPhase_val_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign bayerPhase_val11_c5_din = bayerPhase_val_dout;

assign grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_ap_start = grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_ap_start_reg;

assign height_val4_c3_din = height_val[10:0];

assign icmp_ln315_fu_313_p2 = ((y_fu_76 == loopHeight_reg_552) ? 1'b1 : 1'b0);

assign imgBayer_read = grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_imgBayer_read;

assign imgG_din = grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_imgG_din;

assign imgG_write = grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_200_imgG_write;

assign loopHeight_fu_279_p2 = (zext_ln274_fu_275_p1 + 17'd2);

assign loopWidth_fu_289_p2 = (zext_ln275_fu_285_p1 + 17'd2);

assign start_out = real_start;

assign trunc_ln439_fu_395_p1 = add_ln325_fu_389_p2[0:0];

assign width_val8_c4_din = width_val[10:0];

assign x_phase_fu_271_p1 = bayerPhase_val_dout[0:0];

assign xor_ln439_fu_404_p2 = (zext_ln439_fu_400_p1 ^ trunc_ln_reg_562);

assign y_8_fu_318_p2 = (y_fu_76 + 17'd1);

assign zext_ln274_fu_275_p1 = height_val;

assign zext_ln275_fu_285_p1 = width_val;

assign zext_ln439_fu_400_p1 = trunc_ln439_fu_395_p1;

endmodule //design_1_v_demosaic_0_0_DebayerG
